<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №3</h1>

<a href="https://olgabelitskaya.github.io/README.html">&#x1F300; &nbsp; Home Page</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_2.ipynb">📓 &nbsp; Previous</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_4.ipynb">📓 &nbsp; Next</a>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Определители, миноры и алгебраические дополнения

## 1. Определители

In [1]:
M2=matrix(SR,2,var('a,b,c,d'))
M3=matrix(SR,3,var('a,b,c,d,e,f,g,h,i'))
M4=matrix(SR,4,
          var('a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p'))
A=random_matrix(ZZ,3,x=0,y=100)
B=random_matrix(ZZ,3,x=-100,y=0) 
C=random_matrix(ZZ,4,x=-100,y=100)

In [2]:
for M in [M2,M3,A,B,C]: 
    pretty_print((M,M.det()))

(
[a b]            
[c d], -b*c + a*d
)

(
[a b c]                                                
[d e f]                                                
[g h i], -(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g
)

(
[35 20 57]       
[14 59 74]       
[13 63 86], 16135
)

(
[-95 -62 -87]         
[-86 -11 -33]         
[-31 -61 -10], -256056
)

(
[ 15 -68 -31  74]           
[ 25  50  -3  -7]           
[ 41 -33 -93 -15]           
[ 20  98 -61  78], -34838865
)

In [12]:
import numpy,sympy
A1=numpy.matrix(numpy.random.randint(0,100,
                size=(3,3)))
B1=numpy.matrix(numpy.random.randint(-100,0,
                size=(3,3)))
C1=numpy.matrix(numpy.random.randint(-100,100,
                size=(4,4)))
A2=sympy.Matrix([[-3,-3,1],[-4,-7,7],[2,2,5]])
B2=sympy.Matrix([[2,10,7],[-5,-6,-2],[-8,4,-8]])
C2=sympy.Matrix([[-8,-4,5,2],[3,-5,8,-2],
                 [5,4,-8,1],[7,-2,9,5]])
mm=sympy.symbols(" ".join(list('m_%d%d' %(i,j) 
                 for i in [1,2] for j in [1,2])))
M=sympy.Matrix(int(2),int(2),mm) 
nn=sympy.symbols(" ".join(list('n_%d%d' %(i,j) 
                 for i in [1,2,3] for j in [1,2,3])))
N=sympy.Matrix(int(3),int(3),nn)

In [13]:
for m in [A1,B1,C1]:
    print([m,round(numpy.linalg.det(m))])
for m in [A2,B2,C2]:
    print([m,m.det()])
for m in [M,N]: 
    sympy.pprint(m)
    sympy.pprint(m.det())

[matrix([[16, 61, 13],
        [ 3, 83, 41],
        [60, 75, 87]]), 138660.0]
[matrix([[-95, -94,  -5],
        [-21, -32, -26],
        [-48, -97, -46]]), 70737.0]
[matrix([[ -7,  12,   6,  34],
        [  1,  35, -55, -39],
        [ 30,  25, -65, -85],
        [ 43,  59, -62, -39]]), 243150.0]
[Matrix([
[-3, -3, 1],
[-4, -7, 7],
[ 2,  2, 5]]), 51]
[Matrix([
[ 2, 10,  7],
[-5, -6, -2],
[-8,  4, -8]]), -604]
[Matrix([
[-8, -4,  5,  2],
[ 3, -5,  8, -2],
[ 5,  4, -8,  1],
[ 7, -2,  9,  5]]), -1566]
⎡m₁₁  m₁₂⎤
⎢        ⎥
⎣m₂₁  m₂₂⎦
m₁₁⋅m₂₂ - m₁₂⋅m₂₁
⎡n₁₁  n₁₂  n₁₃⎤
⎢             ⎥
⎢n₂₁  n₂₂  n₂₃⎥
⎢             ⎥
⎣n₃₁  n₃₂  n₃₃⎦
n₁₁⋅n₂₂⋅n₃₃ - n₁₁⋅n₂₃⋅n₃₂ - n₁₂⋅n₂₁⋅n₃₃ + n₁₂⋅n₂₃⋅n₃₁ + n₁₃⋅n₂₁⋅n₃₂ - n₁₃⋅n₂₂⋅
n₃₁


In [3]:
%%r
A<-matrix(sample.int(100,size=3*3,replace=T),
          nrow=3,ncol=3)
B<-matrix(sample.int(100,size=3*3,replace=T),
          nrow=3,ncol=3)
C<-matrix(sample.int(100,size=4*4,replace=T),
          nrow=4,ncol=4)
library(Matrix)

[1] "Matrix"    "tools"     "stats"     "graphics"  "grDevices" "utils"    
[7] "datasets"  "methods"   "base"


In [4]:
%%r
c(det(A),det(B),det(C))

[1]   -80788  -129720 -7780394


## 2. Свойства определителей

In [5]:
pretty_print('A.det()=A.T.det(): '+\
             str(A.det()==A.T.det()))
pretty_print('(A*B).det()=(B*A).det()=A.det()*B.det(): '+\
             str((A*B).det()==(B*A).det()==A.det()*B.det()))
pretty_print('(-2*A).det()=(-2)^A.dimensions()[0]*A.det(): '+\
             str((-2*A).det()==(-2)^A.dimensions()[0]*A.det()))
# linear dependence
[matrix([[1,2,3],[0,0,0],[7,8,9]]).det(),
 matrix([[1,2,3],[2,4,6],[7,8,9]]).det()]

'A.det()=A.T.det(): True'

'(A*B).det()=(B*A).det()=A.det()*B.det(): True'

'(-2*A).det()=(-2)^A.dimensions()[0]*A.det(): True'

[0, 0]

In [14]:
print(round(numpy.linalg.det(A1))==\
round(numpy.linalg.det(A1.T)),\
round(numpy.linalg.det(A1*B1))==\
round(numpy.linalg.det(B1*A1))==\
round(numpy.linalg.det(A1))*round(numpy.linalg.det(B1)),\
round(numpy.linalg.det(-2*A1))==\
-2**A2.shape[0]*round(numpy.linalg.det(A1))) 
# linear dependence
round(numpy.linalg.det(numpy.matrix([[1,2,3],[0,0,0],[7,8,9]]))),\
round(numpy.linalg.det(numpy.matrix([[1,2,3],[2,4,6],[7,8,9]])))

(True, True, True)


(0.0, 0.0)

In [15]:
print([A2.det()==A2.T.det(),
      (A2*B2).det()==(B2*A2).det()==A2.det()*B2.det(),
      (-2*A2).det()==(-2)^A2.shape[0]*A2.det()])
# linear dependence
[sympy.Matrix([[1,2,3],[0,0,0],[7,8,9]]).det(),
sympy.Matrix([[1,2,3],[2,4,6],[7,8,9]]).det()]

[True, True, True]


[0, 0]

In [6]:
%%r
print(c(all.equal(det(A),det(t(A))),
        all.equal(det(A%*%B),
        det(B%*%A),det(A)*det(B)),
        all.equal(det(-2*A),(-2)^(dim(A)[1])*det(A))))
# linear dependence
c(det(matrix(c(1,3,5,0,0,0,2,4,6),
             nrow=3,ncol=3)),
  det(matrix(c(1,3,5,2,6,10,2,4,6),
             nrow=3,ncol=3)))

[1] TRUE TRUE TRUE
[1] 0.000000e+00 3.552714e-15


## 3. Миноры и алгебраические дополнения
Матрицы знаков для определителей 3-ого и 4-ого порядка 

In [7]:
%%latex
$ SIGN_{(3,3)} = 
 \begin{pmatrix}
+ & - & +  \\
- & + & - \\
+ & - & +  \\
 \end{pmatrix} \ \
SIGN_{(4,4)} = 
 \begin{pmatrix}
+ & - & + & - \\
- & + & - & + \\
+ & - & + & - \\
- & + & - & +
 \end{pmatrix}$

<IPython.core.display.Latex object>

Алгебраическое дополнение = Минор & Знак (+/-)

In [8]:
[M3.minors(2),M4.minors(3),
 A.minors(2),B.minors(2),C.minors(3)]

[[-b*d + a*e,
  -c*d + a*f,
  -c*e + b*f,
  -b*g + a*h,
  -c*g + a*i,
  -c*h + b*i,
  -e*g + d*h,
  -f*g + d*i,
  -f*h + e*i],
 [-(g*j - f*k)*a + (c*j - b*k)*e - (c*f - b*g)*i,
  -(h*j - f*l)*a + (d*j - b*l)*e - (d*f - b*h)*i,
  -(h*k - g*l)*a + (d*k - c*l)*e - (d*g - c*h)*i,
  -(h*k - g*l)*b + (d*k - c*l)*f - (d*g - c*h)*j,
  -(g*n - f*o)*a + (c*n - b*o)*e - (c*f - b*g)*m,
  -(h*n - f*p)*a + (d*n - b*p)*e - (d*f - b*h)*m,
  -(h*o - g*p)*a + (d*o - c*p)*e - (d*g - c*h)*m,
  -(h*o - g*p)*b + (d*o - c*p)*f - (d*g - c*h)*n,
  -(k*n - j*o)*a + (c*n - b*o)*i - (c*j - b*k)*m,
  -(l*n - j*p)*a + (d*n - b*p)*i - (d*j - b*l)*m,
  -(l*o - k*p)*a + (d*o - c*p)*i - (d*k - c*l)*m,
  -(l*o - k*p)*b + (d*o - c*p)*j - (d*k - c*l)*n,
  -(k*n - j*o)*e + (g*n - f*o)*i - (g*j - f*k)*m,
  -(l*n - j*p)*e + (h*n - f*p)*i - (h*j - f*l)*m,
  -(l*o - k*p)*e + (h*o - g*p)*i - (h*k - g*l)*m,
  -(l*o - k*p)*f + (h*o - g*p)*j - (h*k - g*l)*n],
 [1785, 1792, -1883, 1945, 2269, -1871, 115, 242, 412],
 [-4287, -4347, 

In [9]:
# разложение определителя по первому столбцу
M3.det()==M3[0,0]*M3.minors(2)[8]-\
M3[1,0]*M3.minors(2)[5]+M3[2,0]*M3.minors(2)[2]

-(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g == -(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g

In [10]:
def minor(m,i,j): 
    return [row[:j]+row[j+1:] 
            for row in (m[:i]+m[i+1:])]
def deternminant(m):
    if len(m)==2: 
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]
    det=0
    for c in range(len(m)): 
        det+=((-1)**c)*m[0][c]*deternminant(minor(m,0,c))
    return det
[minor([[1,2,3],[-4,5,-6],[-7,8,-9]],1,1),
deternminant([[1,2,3],[-4,5,-6],[-7,8,-9]])]

[[[1, 3], [-7, -9]], 24]

In [16]:
sympy.pprint(A2)
sympy.pprint(A2.minorMatrix(0,0))

⎡-3  -3  1⎤
⎢         ⎥
⎢-4  -7  7⎥
⎢         ⎥
⎣2   2   5⎦
⎡-7  7⎤
⎢     ⎥
⎣2   5⎦


In [17]:
# разложение определителя по первому столбцу
B2.det()==B2[0,0]*B2.minorMatrix(0,0).det()-\
B2[1,0]*B2.minorMatrix(1,0).det()+\
B2[2,0]*B2.minorMatrix(2,0).det()

True

In [18]:
%%r
minor_matrix<-function(A,i,j) A[-i,-j]
minor<-function(A,i,j) det(A[-i,-j])
cofactor<-function(A,i,j) (-1)^(i+j)*minor(A,i,j)
c(minor_matrix(A,1,2),minor(A,1,2),cofactor(A,1,2))

[1]   97    6   81    8  290 -290


In [19]:
%%r
c(det(A),
 (A[1,1]*minor(A,1,1)-
 A[2,1]*minor(A,2,1)+
 A[3,1]*minor(A,3,1)))

[1] -80788 -80788


## 4. Задание

Инициировать матрицу $A(3x3)$, рассчитать определитель и исследовать его свойства 

с использованием SageMath, Numpy, SymPy, R.

Вычислить определитель с помощью разложения по третьему столбцу.