<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №9</h1>

### Программные средства

[LaTeX. Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Sage. Linear Algebra](http://doc.sagemath.org/html/en/tutorial/tour_linalg.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[R Functions - Tutorialspoint](https://www.tutorialspoint.com/r/r_functions.htm)

[Quick-R: User-Defined Functions](https://www.statmethods.net/management/userfunctions.html)

### Конспекты лекций

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

[Прямые и плоскости](http://hoster.bmstu.ru/~fn1/wp-content/uploads/2012/10/uchebno-metod/Surf_and_lines_ST_metod.pdf)

[Computational Mathematics with SageMath](http://dl.lateralis.org/public/sagebook/sagebook-ba6596d.pdf)

[Introduction to Symbolic Computation](http://homepages.math.uic.edu/~jan/mcs320/mcs320.pdf)

# Плоскость

## 1. Уравнения.

Общий вид

$\pi: \ a * x + b * y + c * z + d = 0$

$\overrightarrow{n}\{a;b;c\} \perp \pi$

Проходящая через точку $A_0(x_0;y_0;z_0)$ и перпендикулярная $\overrightarrow{n}\{a;b;c\}$

$\pi: \ a * (x - x_0) + b * (y - y_0) + c * (z -z_0) = 0$

Через три точки $A_1 (x_1;y_1;z_1), A_2 (x_2,y_2,z_2), A_3 (x_3,y_3,z_3)$

$\begin {vmatrix}
x - x_1 & y - y_1 & z - z_1 \\
x_2 - x_1 & y_2 - y_1 & z_2 - z_1 \\
x_3 - x_1 & y_3 - y_1 & z_3 - z_1
\end{vmatrix} = 0$

В отрезках

$\pi: \frac{x}{\alpha} + \frac{x}{\beta} + \frac{z}{\gamma} = 1$

$\alpha = -\frac{d}{a}, \ \beta = -\frac{d}{b}, \ \gamma = -\frac{d}{c}$

Параметрические уравнения плоскости

$\pi: \begin {cases} 
x = x_0 + p_1 * t_1 + p_2 * t_2 \\
y = y_0 + q_1 * t_1 + q_2 * t_2 \\
z = z_0 + r_1 * t_1 + r_2 * t_2 
\end {cases}, \ t_1, t_2 \in \mathbb{R}$

$\overrightarrow{s_1}\{p_1;q_1;r_1\}, \ \overrightarrow{s_2}\{p_2;q_2;r_2\} \parallel \pi, 
\ A_0(x_0;y_0;z_0) \in \pi$

Нормальное уравнение плоскости

$P$ - проекция начала координат $O(0;0;0)$ на плоскость $\pi$

$ |\overrightarrow{OP}| = p, \ 
\angle(\overrightarrow{OP}, \overrightarrow{OX}) = \alpha, \ 
\angle(\overrightarrow{OP}, \overrightarrow{OY}) = \beta, \ 
\angle(\overrightarrow{OP}, \overrightarrow{OZ}) = \gamma, \ $

$\pi: x \cdot \cos \alpha + y \cdot \cos \beta + z \cdot \cos \gamma = p$

$\cos^2 \alpha + \cos^2 \beta + \cos^2 \gamma = 1$

In [8]:
# sage
x,y,z,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,y3,z3 = var('x,y,z,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,y3,z3')
a,b,c,d,p1,q1,r1,p2,q2,r2,t1,t2 = var('a,b,c,d,p1,q1,r1,p2,q2,r2,t1,t2')
eq1 = a*x+b*y+c*z+d==0
eq2 = a*(x-x0)+b*(y-y0)+c*(z-z0)==0
P = Matrix(SR, 3, [x-x1, y-y1, z-z1, 
                   x2-x1, y2-y1, z2-z1, 
                   x3-x1, y3-y1, z3-z1])
eq3 = P.det()==0
eq4 = x==x0+p1*t1+p2*t2
eq5 = y==y0+q1*t1+q2*t2
eq6 = z==z0+r1*t1+r2*t2

In [9]:
solve([eq1, a==3, b==-1, c==-1, d==2], 
      a,b,c,d,x,y,z)

[[a == 3, b == -1, c == -1, d == 2, x == r1, y == r2, z == 3*r1 - r2 + 2]]

In [10]:
solve([eq2, a==3, b==2, c==-1, x0==1, y0==-1, z0==2], 
      a,b,c,d,x0,y0,z0,x,y,z)

[[a == 3, b == 2, c == -1, d == r3, x0 == 1, y0 == -1, z0 == 2, x == r4, y == r5, z == 3*r4 + 2*r5 + 1]]

In [11]:
solve([eq3, x1==-3, y1==2, z1==1, x2==1, y2==-3, z2==3, x3==-2, y3==1, z3==1], 
      x1,y1,z1,x2,y2,z2,x3,y3,z3,x,y,z)

[[x1 == -3, y1 == 2, z1 == 1, x2 == 1, y2 == -3, z2 == 3, x3 == -2, y3 == 1, z3 == 1, x == r6, y == r7, z == -2*r6 - 2*r7 - 1]]

In [12]:
solve([eq4, eq5, eq6, x0==-1, y0==2, z0==-2, p1==2, q1==1, r1==-1, p2==-2, q2==-3, r2==2],
      x0,y0,z0,p1,q1,r1,p2,q2,r2,t1,t2,x,y,z)

[[x0 == -1, y0 == 2, z0 == -2, p1 == 2, q1 == 1, r1 == -1, p2 == -2, q2 == -3, r2 == 2, t1 == r8, t2 == r9, x == 2*r8 - 2*r9 - 1, y == r8 - 3*r9 + 2, z == -r8 + 2*r9 - 2]]

In [42]:
# sympy
import sympy
sympy.init_printing(use_unicode=True)
x,y,z,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,y3,z3 = sympy.symbols('x,y,z,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,y3,z3')
a,b,c,d,p1,q1,r1,p2,q2,r2,t1,t2 = sympy.symbols('a,b,c,d,p1,q1,r1,p2,q2,r2,t1,t2')
eq1 = a*x+b*y+c*z+d
eq2 = a*(x-x0)+b*(y-y0)+c*(z-z0)
P = sympy.Matrix([[x-x1,y-y1,z-z1],[x2-x1,y2-y1,z2-z1],[x3-x1,y3-y1,z3-z1]])
eq3 = P.det()
eq4 = x-x0-p1*t1-p2*t2
eq5 = y-y0-q1*t1-q2*t2
eq6 = z-z0-r1*t1-r2*t2

In [43]:
sympy.solve([eq1, a-3, b+1, c+1, d-2], a,b,c,d,z)

In [44]:
sympy.solve([eq2, a-3, b-2, c+1, x0-1, y0+1, z0-2], a,b,c,d,x0,y0,z0,z)

In [45]:
sympy.solve([eq3, x1+3, y1-2, z1-1, x2-1, y2+3, z2-3, x3+2, y3-1, z3-1], 
            x1,y1,z1,x2,y2,z2,x3,y3,z3,z)

In [46]:
sympy.solve([eq4, eq5, eq6, x0+1, y0-2, z0+2, p1-2, q1-1, r1+1, p2+2, q2+3, r2-2],
            x0,y0,z0,p1,q1,r1,p2,q2,r2,x,y,z)

## 2. Взаимное расположение точек, прямых и плоскостей.

Расстояние от точки $M(x_M;y_M;z_M)$ до плоскости $\pi: \ a * x + b * y + c * z + d = 0$

$\rho(M, \pi) = \frac{|a * x_M + b * y_M + c * z_M + d|}{\sqrt{a^2 + b^2 + c^2}}$

Две плоскости $\pi_1: \ a_1 * x + b_1 * y + c_1 * z + d_1 = 0$, $\pi_2: \ a_2 * x + b_2 * y + c_2 * z + d_2 = 0$



In [21]:
%%latex
$A(1;1;3), B(1;2;2), C(7;3;1) \in \pi \\
O(x_0;y_0;z_0): O \in \pi, \ AO = BO = CO = R \\
(x_0;y_0;z_0), \ R - ? $

<IPython.core.display.Latex object>

Решение с уравнениями второго порядка

In [23]:
# sage
x0,y0,z0 = var('x0,y0,z0')
x1,y1,z1 = 1,1,3
x2,y2,z2 = -1,2,2
x3,y3,z3 = 7,-3,1

P = Matrix(SR, 3, [x0-x1, y0-y1, z0-z1, 
                   x2-x1, y2-y1, z2-z1, 
                   x3-x1, y3-y1, z3-z1])
eq1 = P.det()==0
eq2 = (x0-x1)^2+(y0-y1)^2+(z0-z1)^2==(x0-x2)^2+(y0-y2)^2+(z0-z2)^2
eq3 = (x0-x3)^2+(y0-y3)^2+(z0-z3)^2==(x0-x2)^2+(y0-y2)^2+(z0-z2)^2

solve([eq1,eq2,eq3], x0,y0,z0) # O

[[x0 == 2, y0 == -1, z0 == -4]]

In [24]:
x0,y0,z0 = 2,-1,-4
sqrt((x0-x1)^2+(y0-y1)^2+(z0-z1)^2) # R

3*sqrt(6)

In [47]:
# sympy
x0,y0,z0 = sympy.symbols('x0,y0,z0')
x1,y1,z1 = 1,1,3
x2,y2,z2 = -1,2,2
x3,y3,z3 = 7,-3,1

P = sympy.Matrix([[x0-x1,y0-y1,z0-z1],[x2-x1,y2-y1,z2-z1],[x3-x1,y3-y1,z3-z1]])
eq1 = P.det()
eq2 = (x0-x1)**2+(y0-y1)**2+(z0-z1)**2-(x0-x2)**2-(y0-y2)**2-(z0-z2)**2
eq3 = (x0-x3)**2+(y0-y3)**2+(z0-z3)**2-(x0-x2)**2-(y0-y2)**2-(z0-z2)**2

sympy.solve([eq1,eq2,eq3], x0,y0,z0) # O

In [48]:
x0,y0,z0 = 2,-1,-4
sympy.sqrt((x0-x1)**2+(y0-y1)**2+(z0-z1)**2) # R

Решение с уравнениями первого порядка

$\pi : A,B,C \in \pi$

$\pi : \\
(x-x_A)[(y_B-y_A)(z_C-z_A)-(y_C-y_A)(z_B-z_A)]-\\
-(y-y_A)[(x_B-x_A)(z_C-z_A)-(x_C-x_A)(z_B-z_A)]+\\
+(z-z_A)[(x_B-x_A)(y_C-y_A)-(x_C-x_A)(y_B-y_A)] = 0$

$D: AD=BD \implies D(\frac{x_A+x_B}{2};\frac{y_A+y_B}{2};\frac{z_A+z_B}{2})$

$E: AE=CE \implies E(\frac{x_A+x_C}{2};\frac{y_A+y_C}{2};\frac{z_A+z_C}{2})$

$\overrightarrow{AB}\{x_B-x_A;y_B-y_A;z_B-z_A\},\
\overrightarrow{AC}\{x_C-x_A;y_C-y_A;z_C-z_A\}$

$\pi_1 : \overrightarrow{AB} \perp \pi_1, D \in \pi_1$

$\pi_1 : (x_B-x_A)*(x-\frac{x_A+x_B}{2})+(y_B-y_A)*(y-\frac{y_A+y_B}{2})+(z_B-z_A)*(z-\frac{z_A+z_B}{2})=0$

$\pi_2 : \overrightarrow{AC} \perp \pi_2, E \in \pi_2$

$\pi_2 : (x_C-x_A)*(x-\frac{x_A+x_C}{2})+(y_C-y_A)*(y-\frac{y_A+y_C}{2})+(z_C-z_A)*(z-\frac{z_A+z_C}{2})=0$

$O \in \pi, \pi_1, \pi_2$

In [73]:
import numpy
xA,yA,zA = 1,1,3
xB,yB,zB = -1,2,2
xC,yC,zC = 7,-3,1
# π
a1 = numpy.array([(yB-yA)*(zC-zA)-(yC-yA)*(zB-zA), 
                  -(xB-xA)*(zC-zA)+(xC-xA)*(zB-zA), 
                  (xB-xA)*(yC-yA)-(xC-xA)*(yB-yA)])
b1 = sum(numpy.array([xA,yA,zA]) * a1)
# π1
a2 = numpy.array([xB-xA,yB-yA,zB-zA])
b2 = sum(numpy.array([(xA+xB)/2,(yA+yB)/2,(zA+zB)/2]) * a2)
# π2
a3 = numpy.array([xC-xA,yC-yA,zC-zA])
b3 = sum(numpy.array([(xA+xC)/2,(yA+yC)/2,(zA+zC)/2]) * a3)

a = numpy.array([a1,a2,a3])
b = numpy.array([b1,b2,b3])
O = numpy.linalg.solve(a,b)
print(a); print(b); print(O)

[[ -6 -10   2]
 [ -2   1  -1]
 [  6  -4  -2]]
[-10.  -1.  24.]
[ 2. -1. -4.]
