<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №2</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы

## 1. Операции над матрицами
### 1.1 Возведение в степень

In [7]:
# sage
A1 = random_matrix(ZZ,5,x=0,y=100)
C1 = random_matrix(ZZ,5,x=-100,y=0)
B1 = matrix([[1.1,3.2,5.0,7.6],[2.2,4.1,6.5,8.1]])
A1, B1, C1

(
[ 4 33  1  7 59]
[13 76 83 66 70]
[12 24 76 95  8]
[20 94 54 67 79]
[42 94 77 78 85],

[1.10000000000000 3.20000000000000 5.00000000000000 7.60000000000000]
[2.20000000000000 4.10000000000000 6.50000000000000 8.10000000000000],

[-31 -45 -21 -93 -29]
[-74 -32 -98 -27  -8]
[-18 -22  -3 -91  -9]
[-51 -18 -93 -59 -49]
[-20  -4 -85 -32  -9]
)

In [4]:
A1^3

[1903139 1407412  430391 2135404 1027929]
[3037405 2319981  677216 2463603 1352851]
[4192550 3342288 1136504 4016230 2271365]
[2542433 1982484  554519 1823154 1020706]
[1550282 1174324  345948 1392686  784439]

In [6]:
A1^3 == A1 * A1 * A1

True

In [14]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(5,5)))
C2 = numpy.matrix(numpy.random.randint(-100, 0, size=(5,5)))
B2 = numpy.matrix([[1,3,5,7],[2,4,6,8]])
print(A2)
print(B2)
print(C2)

[[21  3 92 98 23]
 [ 2 93 65 27 21]
 [43 88 19 49 51]
 [34 31 89 65  5]
 [13 70 94 56 29]]
[[1 3 5 7]
 [2 4 6 8]]
[[-72 -78 -51 -46 -48]
 [-18 -15 -15 -23 -74]
 [-11 -49 -16 -12 -78]
 [-55 -80 -79 -89 -74]
 [-98 -68 -55 -71 -67]]


In [18]:
A2 ** int(3) == A2 * A2 * A2

matrix([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]], dtype=bool)

In [19]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3, -6,-3], [-4, -7, 8,-7], [2, -3, 9, -5], [6, -3, 8, 2]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8], [7, 4, -6]])
C3 = sympy.Matrix([[-8, -4, 5, 2], [3, -5, 8, -2], [5, 4, -8, 1], [7, -2, 9, 5]])
print(A3, B3, C3)

(Matrix([
[-3, -3, -6, -3],
[-4, -7,  8, -7],
[ 2, -3,  9, -5],
[ 6, -3,  8,  2]]), Matrix([
[ 2, 10,  7],
[-5, -6, -2],
[-8,  4, -8],
[ 7,  4, -6]]), Matrix([
[-8, -4,  5,  2],
[ 3, -5,  8, -2],
[ 5,  4, -8,  1],
[ 7, -2,  9,  5]]))


In [21]:
A3^3 == A3 * A3 * A3

True

In [24]:
sympy.MatPow(A3, 3).as_explicit()

Matrix([
[ -45, -282,  186,  156],
[-264, -421,  292, -354],
[-224,  102, -215, -108],
[-100,  138, -360,  -83]])

In [25]:
%%r
A4 <- matrix(rexp(25, rate=0.1), nrow=5, ncol=5)
B4 <- matrix(c(1,3,5,7,2,4,6,8), nrow=2, ncol=4)
C4 <- matrix(rexp(25, rate=0.2), nrow=5, ncol=5)
D4 <- matrix(sample.int(100, size=3*4, replace=T), nrow=3, ncol=4)
A4; B4; D4





          [,1]      [,2]       [,3]       [,4]        [,5]
[1,]  9.423773 18.555664  0.2288297 12.6718144 13.62604867
[2,] 26.408819  4.740174  3.4295191 11.4775862  0.08964574
[3,]  6.027099 11.172584  1.3450325  8.6214268  0.20625451
[4,] 11.788261 18.301193  0.9501415  0.9755198  0.70827746
[5,] 23.088658 44.437817 12.4730859 31.0452286  9.44632553
     [,1] [,2] [,3] [,4]
[1,]    1    5    2    6
[2,]    3    7    4    8
     [,1] [,2] [,3] [,4]
[1,]   45   38   56   49
[2,]   86   38   76   61
[3,]   53   58    8   34


In [34]:
%%r 
require(matrixcalc)
matrix.power(A4,3)


         [,1]     [,2]      [,3]     [,4]      [,5]
[1,] 55716.69 53363.55  8426.515 37093.58 17453.453
[2,] 39089.35 38291.07  7822.746 27764.37 11128.061
[3,] 18702.66 19173.39  2726.560 13405.02  7423.997
[4,] 24555.27 28934.91  3989.446 18465.41 10486.499
[5,] 92435.68 91806.61 13525.140 63656.86 33121.563


In [36]:
%%r
matrix.power(A4,3) == A4 %*% A4 %*% A4

     [,1] [,2] [,3] [,4] [,5]
[1,] TRUE TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE TRUE
[4,] TRUE TRUE TRUE TRUE TRUE
[5,] TRUE TRUE TRUE TRUE TRUE


### 1.2 Транспонирование

In [38]:
# sage
A1, A1.transpose()

(
[ 4 33  1  7 59]  [ 4 13 12 20 42]
[13 76 83 66 70]  [33 76 24 94 94]
[12 24 76 95  8]  [ 1 83 76 54 77]
[20 94 54 67 79]  [ 7 66 95 67 78]
[42 94 77 78 85], [59 70  8 79 85]
)

In [39]:
# python numpy
A2, numpy.transpose(A2)

(matrix([[21,  3, 92, 98, 23],
         [ 2, 93, 65, 27, 21],
         [43, 88, 19, 49, 51],
         [34, 31, 89, 65,  5],
         [13, 70, 94, 56, 29]]), matrix([[21,  2, 43, 34, 13],
         [ 3, 93, 88, 31, 70],
         [92, 65, 19, 89, 94],
         [98, 27, 49, 65, 56],
         [23, 21, 51,  5, 29]]))

In [40]:
# python sympy
A3, A3.T

(Matrix([
 [-3, -3, -6, -3],
 [-4, -7,  8, -7],
 [ 2, -3,  9, -5],
 [ 6, -3,  8,  2]]), Matrix([
 [-3, -4,  2,  6],
 [-3, -7, -3, -3],
 [-6,  8,  9,  8],
 [-3, -7, -5,  2]]))

In [41]:
%%r
A4; t(A4)

          [,1]      [,2]       [,3]       [,4]        [,5]
[1,]  9.423773 18.555664  0.2288297 12.6718144 13.62604867
[2,] 26.408819  4.740174  3.4295191 11.4775862  0.08964574
[3,]  6.027099 11.172584  1.3450325  8.6214268  0.20625451
[4,] 11.788261 18.301193  0.9501415  0.9755198  0.70827746
[5,] 23.088658 44.437817 12.4730859 31.0452286  9.44632553
           [,1]        [,2]       [,3]       [,4]      [,5]
[1,]  9.4237731 26.40881853  6.0270994 11.7882608 23.088658
[2,] 18.5556635  4.74017434 11.1725836 18.3011928 44.437817
[3,]  0.2288297  3.42951907  1.3450325  0.9501415 12.473086
[4,] 12.6718144 11.47758623  8.6214268  0.9755198 31.045229
[5,] 13.6260487  0.08964574  0.2062545  0.7082775  9.446326


## 2. След матрицы

## 3. Норма матрицы