<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №4</h1>

<a href="https://olgabelitskaya.github.io/README.html">&#x1F300; &nbsp; Home Page</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_3.ipynb">📓 &nbsp; Previous</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_5.ipynb">📓 &nbsp; Next</a>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.html)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Обратная матрица, ранг матрицы

## 1. Обратная матрица
Обратная матрица = Транспонированная матрица алгебраических дополнений / Определитель      
    <p>$A^{-1} = \frac{A_S^T}{\Delta_A}$</p>
Вычисление определителя 4-ого порядка      
    <p>$| M | = \begin{vmatrix} A & B \\ C & D \end{vmatrix} = | A | * |D - C * A^{-1} * B|$</p>

In [22]:
%%latex
$\large{\mathbb{A^{-1}=\frac{A_S^T}{\Delta_A}\;\;}
\mathscr{|M|=\begin{vmatrix}A&B\\C&D\end{vmatrix}=
|A|*|D-C*A^{-1}*B|}}$

<IPython.core.display.Latex object>

In [1]:
S=matrix(SR,2,var('a,b,c,d'))
M2=random_matrix(ZZ,2,x=0,y=100)
M3=random_matrix(ZZ,3,x=-100,y=0)
M4=random_matrix(ZZ,4,x=-100,y=100)

In [2]:
pretty_print(S^(-1),S.inverse())
pretty_print(S*S^(-1),(S*S^(-1)).simplify_rational(),
             S^(-1)*S,(S^(-1)*S).simplify_rational())
(S*S^(-1)).simplify_rational()==(S^(-1)*S)\
.simplify_rational()==identity_matrix(2)

[1/a - b*c/(a^2*(b*c/a - d))           b/(a*(b*c/a - d))]
[          c/(a*(b*c/a - d))              -1/(b*c/a - d)] [1/a - b*c/(a^2*(b*c/a - d))           b/(a*(b*c/a - d))]
[          c/(a*(b*c/a - d))              -1/(b*c/a - d)]

[a*(1/a - b*c/(a^2*(b*c/a - d))) + b*c/(a*(b*c/a - d))                                                     0]
[c*(1/a - b*c/(a^2*(b*c/a - d))) + c*d/(a*(b*c/a - d))                   b*c/(a*(b*c/a - d)) - d/(b*c/a - d)] [1 0]
[0 1] [a*(1/a - b*c/(a^2*(b*c/a - d))) + b*c/(a*(b*c/a - d)) b*(1/a - b*c/(a^2*(b*c/a - d))) + b*d/(a*(b*c/a - d))]
[                                                    0                   b*c/(a*(b*c/a - d)) - d/(b*c/a - d)] [1 0]
[0 1]

True

In [3]:
M3m=M3.minors(2); M3m.reverse()
pretty_print(matrix(3,M3m).T,M3.adjugate())
M3*M3^(-1)==identity_matrix(3),
M3.adjugate()/M3.det()==M3.inverse()==M3^(-1)

[-2803 -1017  2424]
[-1440  -890 -2220]
[ 2528 -1708 -5914] [-2803  1017  2424]
[ 1440  -890  2220]
[ 2528  1708 -5914]

True

In [7]:
A,B,C,D=M4[0:2,0:2],M4[0:2,2:4],M4[2:4,0:2],M4[2:4,2:4]
pretty_print(M4,A,B,C,D)
A.det()*(D-C*A.inverse()*B).det()==M4.det()

[  8  91 -93 -13]
[ 47  16 -83  87]
[ 67  49 -59 -85]
[-48 -80  -1 -12] [ 8 91]
[47 16] [-93 -13]
[-83  87] [ 67  49]
[-48 -80] [-59 -85]
[ -1 -12]

True

In [23]:
import numpy,sympy
MN2=numpy.matrix(numpy.random.randint(0,100,size=(2,2)))
MN3=numpy.matrix(numpy.random.randint(-100,0,size=(3,3)))
MN4=numpy.matrix(numpy.random.randint(-100,100,size=(4,4)))
def minor_matrix(M,x,y):
    return numpy.matrix([[M[i,j] for j in range(len(M)) if j!=y] 
                         for i in range(len(M)) if i!=x])
def minor(M,x,y):
    return numpy.linalg.det(minor_matrix(M,x,y))
def cofactor_matrix(M):
    return numpy.matrix([[(-1)**(i+j)*minor(M,i,j) 
                          for j in range(len(M))] 
                         for i in range(len(M))])
MS2=sympy.Matrix([[-3,1],[-4,-7]])
MS3=sympy.Matrix([[2,10,7],[-5,-6,-2],[-8,4,5]])
MS4=sympy.Matrix([[3,2,8,-5],[-1,-3,6,4],
                  [-6,2,5,-3],[2,-7,1,5]])

In [25]:
print(round(MN3*numpy.linalg.inv(MN3)))
print(round(MN4*numpy.linalg.inv(MN4)))
[MS2*MS2.inv(),MS3*MS3.inv(),MS4*MS4.inv()]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


[Matrix([
 [1, 0],
 [0, 1]]), Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]])]

In [26]:
print(numpy.round(cofactor_matrix(MN3).T/numpy.linalg.det(MN3),8)\
==numpy.round(numpy.linalg.inv(MN3),8))
MS3.adjugate()/MS3.det(),MS3.inv(),MS3^-1

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


(Matrix([
 [    1/5,  1/5,   -1/5],
 [-41/110, -3/5, 31/110],
 [  34/55,  4/5, -19/55]]), Matrix([
 [    1/5,  1/5,   -1/5],
 [-41/110, -3/5, 31/110],
 [  34/55,  4/5, -19/55]]), Matrix([
 [    1/5,  1/5,   -1/5],
 [-41/110, -3/5, 31/110],
 [  34/55,  4/5, -19/55]]))

In [27]:
A,B,C,D=MN4[0:2,0:2],MN4[0:2,2:4],MN4[2:4,0:2],MN4[2:4,2:4]
for m in [MN4,A,B,C,D]:
    print(numpy.array_str(m,precision=2,suppress_small=True))
print(numpy.linalg.det(A)*\
      numpy.linalg.det(D-C*numpy.linalg.inv(A)*B),
      numpy.linalg.det(MN4))
print(round(numpy.linalg.det(A)*\
            numpy.linalg.det(D-C*numpy.linalg.inv(A)*B))==\
      round(numpy.linalg.det(MN4)))
print(30*'=%=')
A,B,C,D=MS4[0:2,0:2],MS4[0:2,2:4],MS4[2:4,0:2],MS4[2:4,2:4]
sympy.pprint('A.det()*(D-C*A^(-1)*B).det()=MS4.det(): %s'\
             %str(A.det()*(D-C*A.inv()*B).det()==MS4.det()))
MS4,A,B,C,D

[[ 12  60  94  29]
 [ 30  83  61 -24]
 [-96   7  64 -11]
 [ 61  70  60  74]]
[[12 60]
 [30 83]]
[[ 94  29]
 [ 61 -24]]
[[-96   7]
 [ 61  70]]
[[ 64 -11]
 [ 60  74]]
(21287192.999999996, 21287192.999999996)
True
=%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%==%=
A.det()*(D-C*A^(-1)*B).det()=MS4.det(): True


(Matrix([
 [ 3,  2, 8, -5],
 [-1, -3, 6,  4],
 [-6,  2, 5, -3],
 [ 2, -7, 1,  5]]), Matrix([
 [ 3,  2],
 [-1, -3]]), Matrix([
 [8, -5],
 [6,  4]]), Matrix([
 [-6,  2],
 [ 2, -7]]), Matrix([
 [5, -3],
 [1,  5]]))

In [28]:
%%r
A<-matrix(sample.int(100,size=2*2,replace=T),
          nrow=2,ncol=2)
B<-matrix(sample.int(100,size=3*3,replace=T),
          nrow=3,ncol=3)
M<-matrix(sample.int(100,size=4*4,replace=T),
          nrow=4,ncol=4)
minor_matrix<-function(A,i,j) A[-i,-j]
minor<-function(A,i,j) det(A[-i,-j])
cofactor<-function(A,i,j) (-1)^(i+j)*minor(A,i,j)
cofactor_matrix<-function(A){
    n<-sqrt(length(A))
    M<-matrix(rep(0,len=n*n),nrow=n)
    for (i in 1:n){for (j in 1:n){M[i,j]<-cofactor(A,i,j)}}
    return(M)}
library(Matrix)

[1] "Matrix"    "tools"     "stats"     "graphics"  "grDevices" "utils"    
[7] "datasets"  "methods"   "base"


In [30]:
%%r
list(round(A%*%solve(A)),
     round(B%*%solve(B)),
     round(M%*%solve(M)))

[[1]]
     [,1] [,2]
[1,]    1    0
[2,]    0    1

[[2]]
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1


In [31]:
%%r
list(t(cofactor_matrix(B))/det(B),solve(B),B^(-1)) 
# !!! solve(B) != B^(-1) in R

[[1]]
            [,1]         [,2]         [,3]
[1,]  0.01098424 -0.014381429  0.010399170
[2,] -0.01550574  0.009992046  0.008147859
[3,]  0.01035064  0.007066690 -0.012046536

[[2]]
            [,1]         [,2]         [,3]
[1,]  0.01098424 -0.014381429  0.010399170
[2,] -0.01550574  0.009992046  0.008147859
[3,]  0.01035064  0.007066690 -0.012046536

[[3]]
           [,1]       [,2]       [,3]
[1,] 0.01515152 0.02702703 0.01219512
[2,] 0.02631579 0.01123596 0.01075269
[3,] 0.01265823 0.01190476 0.02380952


In [32]:
%%r
A<-M[1:2,1:2]; B<-M[1:2,3:4]; C<-M[3:4,1:2]; D<-M[3:4,3:4]
print(c(det(A)*det(D-C%*%solve(A)%*%B),det(M)))
list(M,A,B,C,D)

[1] -2032098 -2032098
[[1]]
     [,1] [,2] [,3] [,4]
[1,]   55   47   68    3
[2,]   34   46   44   29
[3,]   61    6   55   16
[4,]   62   19   77   69

[[2]]
     [,1] [,2]
[1,]   55   47
[2,]   34   46

[[3]]
     [,1] [,2]
[1,]   68    3
[2,]   44   29

[[4]]
     [,1] [,2]
[1,]   61    6
[2,]   62   19

[[5]]
     [,1] [,2]
[1,]   55   16
[2,]   77   69


## 2. Ранг матрицы
Ранг матрицы не меняется в результате элементарных преобразований.

_Элементарные преобразования:_

1) отбрасывание нулевой строки (столбца);

2) изменение порядка строк (столбцов);

3) умножение всех элементов строки (столбца) на число, не равное 0;

4) транспонирование;

5) прибавление к каждому элементу одной строки (столбца) 

   соответствующих элементов другой строки (столбца), умноженных на любое число.

In [33]:
M2.rank(),M3.rank(),M4.rank(),S.rank()

(2, 3, 4, 2)

In [34]:
print([numpy.linalg.matrix_rank(MN2),
       numpy.linalg.matrix_rank(MN3),
       numpy.linalg.matrix_rank(MN4)])
sympy.pprint([MS2.rank(),MS3.rank(),MS4.rank()])

[2, 3, 4]
[2, 3, 4]


In [35]:
%%r
print(c(qr(A)$rank,qr(M)$rank))
qr(M)

[1] 2 4
$qr
             [,1]        [,2]        [,3]       [,4]
[1,] -108.3789647 -52.5286435 -123.317288 -59.098184
[2,]    0.3137140 -44.3028398  -12.082976   5.018808
[3,]    0.5628398  -0.7033527   12.682594  35.151670
[4,]    0.5720667  -0.4236683   -0.692744  33.370291

$rank
[1] 4

$qraux
[1]  1.507479  1.570789  1.721184 33.370291

$pivot
[1] 1 2 3 4

attr(,"class")
[1] "qr"


## 3. Задание

Инициировать случайную матрицу $A(3x3)$, рассчитать для нее определитель, ранг и обратную матрицу

с использованием SageMath, Numpy, SymPy, R.