<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №1</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы. 

## 1. Способы инициализации.

In [70]:
%%latex
$A = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}$

<IPython.core.display.Latex object>

In [130]:
# sage
A1 = random_matrix(ZZ,5,x=0,y=100)
C1 = random_matrix(ZZ,5,x=-100,y=0)
B1 = matrix([[1.1,3.2,5.0,7.6],[2.2,4.1,6.5,8.1]])
A1, B1

(
[22 15 78 52 90]
[50 22 60 16 74]
[49  4 96 41 53]
[26 24  8 71 96]
[13 52 69 17 16],

[1.10000000000000 3.20000000000000 5.00000000000000 7.60000000000000]
[2.20000000000000 4.10000000000000 6.50000000000000 8.10000000000000]
)

In [104]:
A1.base_ring(), B1.base_ring()

(Integer Ring, Real Field with 53 bits of precision)

In [100]:
A1.ncols(), A1.nrows(), A1.dimensions()

(5, 5, (5, 5))

In [105]:
latex(A1)

\left(\begin{array}{rrrrr}
9 & 88 & 20 & 40 & 33 \\
50 & 18 & 89 & 99 & 41 \\
33 & 5 & 87 & 12 & 32 \\
49 & 51 & 22 & 80 & 33 \\
11 & 87 & 60 & 19 & 73
\end{array}\right)

In [106]:
html(B1)

<script type="math/tex">\left(\begin{array}{rrrr} 1.10000000000000 & 3.20000000000000 & 5.00000000000000 & 7.60000000000000 \\ 2.20000000000000 & 4.10000000000000 & 6.50000000000000 & 8.10000000000000 \end{array}\right)</script>

In [107]:
print(html(B1))

<script type="math/tex">\left(\begin{array}{rrrr} 1.10000000000000 & 3.20000000000000 & 5.00000000000000 & 7.60000000000000 \\ 2.20000000000000 & 4.10000000000000 & 6.50000000000000 & 8.10000000000000 \end{array}\right)</script>


In [108]:
E1 = matrix.identity(3)
E1

[1 0 0]
[0 1 0]
[0 0 1]

In [132]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(5,7)))
C2 = numpy.matrix(numpy.random.randint(-100, 0, size=(5,7)))
B2 = numpy.matrix([[1,3,5,7],[2,4,6,8]])
print(A2)
print(B2)

[[98 73 22 72 10 94 38]
 [67 77 99 76 17 14 92]
 [ 0 19 87 70 10 37 86]
 [67 50 54  3 34 63 70]
 [42 15 25 74  8  1 54]]
[[1 3 5 7]
 [2 4 6 8]]


In [119]:
A2.shape

(5, 7)

In [120]:
E2 = numpy.identity(3)
E2

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [135]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3, -6,-3], [-4, -7, 8,-7]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8], [7, 4, -6]])
C3 = sympy.Matrix([[-8, -4, 5, 2], [3, -5, 8, -2]])
print(A3, B3)

(Matrix([
[-3, -3, -6, -3],
[-4, -7,  8, -7]]), Matrix([
[ 2, 10,  7],
[-5, -6, -2],
[-8,  4, -8],
[ 7,  4, -6]]))


In [113]:
A3.shape

(2, 4)

In [114]:
E3 = sympy.Identity(3)
E3.as_explicit()

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [137]:
%%r
A4 <- matrix(rexp(25, rate=0.1), nrow=5, ncol=5)
B4 <- matrix(c(1,3,5,7,2,4,6,8), nrow=2, ncol=4)
C4 <- matrix(rexp(25, rate=0.2), nrow=5, ncol=5)
D4 <- matrix(sample.int(100, size=3*4, replace=T), nrow=3, ncol=4)
A4; B4; D4





          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
     [,1] [,2] [,3] [,4]
[1,]    1    5    2    6
[2,]    3    7    4    8
     [,1] [,2] [,3] [,4]
[1,]   64   23    5   83
[2,]   88   32   52   62
[3,]   52   46   99   90


In [88]:
%%r
dim(A4)

[1] 5 5


In [128]:
%%r
E4 <- matrix(0, 5, 5)
diag(E4) <- 1
E4



     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    1    0    0    0
[3,]    0    0    1    0    0
[4,]    0    0    0    1    0
[5,]    0    0    0    0    1


## 2. Операции над матрицами.
### 2.1 Умножение на число

In [122]:
A1, 2*A1

(
[ 9 88 20 40 33]  [ 18 176  40  80  66]
[50 18 89 99 41]  [100  36 178 198  82]
[33  5 87 12 32]  [ 66  10 174  24  64]
[49 51 22 80 33]  [ 98 102  44 160  66]
[11 87 60 19 73], [ 22 174 120  38 146]
)

In [123]:
A2, -3*A2

(matrix([[66, 15, 19, 52, 98,  0, 66],
         [59,  0, 97, 56, 84, 20, 31],
         [10, 94, 45, 22, 29, 25,  6],
         [71, 95, 51, 98, 57, 39, 22],
         [69, 91, 33, 19, 74, 14, 24]]),
 matrix([[-198,  -45,  -57, -156, -294,    0, -198],
         [-177,    0, -291, -168, -252,  -60,  -93],
         [ -30, -282, -135,  -66,  -87,  -75,  -18],
         [-213, -285, -153, -294, -171, -117,  -66],
         [-207, -273,  -99,  -57, -222,  -42,  -72]]))

In [124]:
A3, 1.5*A3

(Matrix([
 [-3, -3, -6, -3],
 [-4, -7,  8, -7]]), Matrix([
 [-4.5,  -4.5, -9.0,  -4.5],
 [-6.0, -10.5, 12.0, -10.5]]))

In [126]:
%%r
A4; 5*A4

          [,1]      [,2]      [,3]       [,4]       [,5]
[1,]  9.733919  1.220253 18.856894  5.9963881  0.4458297
[2,] 12.894345 17.439791  9.749427  0.1861919  0.2675028
[3,]  4.695959 15.531201 10.316556  7.6798607  5.0276754
[4,]  9.903369 15.528524 10.104245 10.7261280 22.1038481
[5,] 10.642159  2.494848 16.307512  1.6457923  1.8189122
         [,1]      [,2]     [,3]       [,4]       [,5]
[1,] 48.66959  6.101266 94.28447 29.9819407   2.229149
[2,] 64.47172 87.198955 48.74713  0.9309594   1.337514
[3,] 23.47980 77.656005 51.58278 38.3993033  25.138377
[4,] 49.51685 77.642618 50.52123 53.6306398 110.519241
[5,] 53.21079 12.474242 81.53756  8.2289614   9.094561


### 2.2 Сложение и вычитание матриц

In [131]:
A1, C1, A1 + C1

(
[22 15 78 52 90]  [-15 -44 -48 -32 -27]  [  7 -29  30  20  63]
[50 22 60 16 74]  [-87 -70 -48 -36 -39]  [-37 -48  12 -20  35]
[49  4 96 41 53]  [-99  -1 -27  -8 -29]  [-50   3  69  33  24]
[26 24  8 71 96]  [-22 -40 -19 -34 -39]  [  4 -16 -11  37  57]
[13 52 69 17 16], [-35 -64  -7 -28 -94], [-22 -12  62 -11 -78]
)

In [133]:
A2, C2, A2 - C2

(matrix([[98, 73, 22, 72, 10, 94, 38],
         [67, 77, 99, 76, 17, 14, 92],
         [ 0, 19, 87, 70, 10, 37, 86],
         [67, 50, 54,  3, 34, 63, 70],
         [42, 15, 25, 74,  8,  1, 54]]),
 matrix([[-19, -14, -92, -67, -59, -67, -18],
         [-91, -75, -89, -77, -35, -68, -40],
         [ -1, -68, -20, -80, -79, -75, -32],
         [-12, -71, -94, -64, -73, -76, -38],
         [ -4, -93, -19, -75, -34, -42, -26]]),
 matrix([[117,  87, 114, 139,  69, 161,  56],
         [158, 152, 188, 153,  52,  82, 132],
         [  1,  87, 107, 150,  89, 112, 118],
         [ 79, 121, 148,  67, 107, 139, 108],
         [ 46, 108,  44, 149,  42,  43,  80]]))

In [136]:
A3, C3, A3 + C3

(Matrix([
 [-3, -3, -6, -3],
 [-4, -7,  8, -7]]), Matrix([
 [-8, -4, 5,  2],
 [ 3, -5, 8, -2]]), Matrix([
 [-11,  -7, -1, -1],
 [ -1, -12, 16, -9]]))

In [139]:
%%r
A4; C4; A4 - C4

          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
          [,1]      [,2]      [,3]      [,4]       [,5]
[1,]  5.971833 4.5704932  2.116315 2.6474938  2.0918457
[2,]  4.244769 3.4688824  2.578513 0.7312220  8.2971376
[3,]  5.447669 0.3404288  4.022721 9.8283240  0.5694052
[4,] 16.116502 6.0128435  0.405711 0.9847488 12.8393433
[5,]  6.620679 6.1495929 10.603066 7.7490383 22.0010271
            [,1]      [,2]       [,3]       [,4]      [,5]
[1,]   0.8555462 -2.922484 16.4272144 -0.9360693  8.840943
[2,]  -2.8750991  5.175831 -0.4938241  2.2462329 -3.277765
[3,]  29.9059194  4.509505  3.0886813 32.1145632 32.922896
[4,] -14.4954228 -4.797962 -0.3549455  8.4075973 -7.092713
[5,]   2.7972426 -2.024267 -7.180

### 2.3 Умножение матриц

In [140]:
# sage
A1, C1, A1 * C1

(
[22 15 78 52 90]  [-15 -44 -48 -32 -27]
[50 22 60 16 74]  [-87 -70 -48 -36 -39]
[49  4 96 41 53]  [-99  -1 -27  -8 -29]
[26 24  8 71 96]  [-22 -40 -19 -34 -39]
[13 52 69 17 16], [-35 -64  -7 -28 -94],

[-13651  -9936  -5500  -6156 -13929]
[-11546  -9176  -5898  -5488 -11528]
[-13344  -7564  -6286  -5358 -10844]
[ -8192 -11816  -4637  -6862 -13663]
[-12484  -5985  -5418  -3866  -6547]
)

In [141]:
A1, C1, C1 * A1

(
[22 15 78 52 90]  [-15 -44 -48 -32 -27]
[50 22 60 16 74]  [-87 -70 -48 -36 -39]
[49  4 96 41 53]  [-99  -1 -27  -8 -29]
[26 24  8 71 96]  [-22 -40 -19 -34 -39]
[13 52 69 17 16], [-35 -64  -7 -28 -94],

[ -6065  -3557 -10537  -6183 -10654]
[ -9209  -5929 -18573 -10831 -19634]
[ -4136  -3315 -12439  -7332 -11647]
[ -4806  -4130  -8903  -5640  -9835]
[ -6263  -7521 -13952  -6717 -12449]
)

In [146]:
# python numpy
A2, C2.T, A2 * C2.T

(matrix([[98, 73, 22, 72, 10, 94, 38],
         [67, 77, 99, 76, 17, 14, 92],
         [ 0, 19, 87, 70, 10, 37, 86],
         [67, 50, 54,  3, 34, 63, 70],
         [42, 15, 25, 74,  8,  1, 54]]), matrix([[-19, -91,  -1, -12,  -4],
         [-14, -75, -68, -71, -93],
         [-92, -89, -20, -94, -19],
         [-67, -77, -80, -64, -75],
         [-59, -35, -79, -73, -34],
         [-67, -68, -75, -76, -42],
         [-18, -40, -32, -38, -26]]), matrix([[-17304, -30157, -20318, -22353, -18275],
         [-20148, -31762, -18700, -26242, -18568],
         [-17577, -20864, -14949, -20817, -12800],
         [-14629, -23158, -14438, -19552, -11791],
         [ -9777, -15378,  -9917, -11367,  -9306]]))

In [147]:
A2, C2.T, C2.T * A2

(matrix([[98, 73, 22, 72, 10, 94, 38],
         [67, 77, 99, 76, 17, 14, 92],
         [ 0, 19, 87, 70, 10, 37, 86],
         [67, 50, 54,  3, 34, 63, 70],
         [42, 15, 25, 74,  8,  1, 54]]), matrix([[-19, -91,  -1, -12,  -4],
         [-14, -75, -68, -71, -93],
         [-92, -89, -20, -94, -19],
         [-67, -77, -80, -64, -75],
         [-59, -35, -79, -73, -34],
         [-67, -68, -75, -76, -42],
         [-18, -40, -32, -38, -26]]), matrix([[ -8931,  -9073, -10262,  -8686,  -2187,  -3857, -10236],
         [-15060, -13034, -19808, -18563,  -5253,  -9448, -23272],
         [-22075, -18934, -18126, -16476,  -5981, -16575, -21010],
         [-19163, -16665, -21388, -22018,  -5555, -14443, -25040],
         [-14446, -12663, -16428, -15173,  -4729, -13592, -19202],
         [-17978, -15982, -19885, -18578,  -5496, -14855, -22840],
         [ -8082,  -7292,  -9842,  -8614,  -2680,  -5856, -11180]]))

In [159]:
numpy.dot(A2, C2.T) == A2 * C2.T

matrix([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]], dtype=bool)

In [161]:
numpy.dot(A2, C2.T), C2.T * A2

(matrix([[-17304, -30157, -20318, -22353, -18275],
         [-20148, -31762, -18700, -26242, -18568],
         [-17577, -20864, -14949, -20817, -12800],
         [-14629, -23158, -14438, -19552, -11791],
         [ -9777, -15378,  -9917, -11367,  -9306]]),
 matrix([[ -8931,  -9073, -10262,  -8686,  -2187,  -3857, -10236],
         [-15060, -13034, -19808, -18563,  -5253,  -9448, -23272],
         [-22075, -18934, -18126, -16476,  -5981, -16575, -21010],
         [-19163, -16665, -21388, -22018,  -5555, -14443, -25040],
         [-14446, -12663, -16428, -15173,  -4729, -13592, -19202],
         [-17978, -15982, -19885, -18578,  -5496, -14855, -22840],
         [ -8082,  -7292,  -9842,  -8614,  -2680,  -5856, -11180]]))

In [6]:
# python numpy 
# !!! умножение матриц отличается от умножения массивов !!!
a = numpy.random.random((3,3))
b = numpy.random.random((3,3))
a * b # elementwise product

array([[ 0.18001901,  0.00992128,  0.00199871],
       [ 0.33168696,  0.1134861 ,  0.39432957],
       [ 0.41010049,  0.00384317,  0.03939812]])

In [7]:
a.dot(b) # matrix product

array([[ 0.33140171,  0.11166035,  0.02537534],
       [ 1.19231095,  0.41621232,  0.28124379],
       [ 1.39924161,  0.52571291,  0.41865095]])

In [148]:
A3, C3.T, A3 * C3.T

(Matrix([
 [-3, -3, -6, -3],
 [-4, -7,  8, -7]]), Matrix([
 [-8,  3],
 [-4, -5],
 [ 5,  8],
 [ 2, -2]]), Matrix([
 [ 0, -36],
 [86, 101]]))

In [149]:
A3, C3.T, C3.T * A3

(Matrix([
 [-3, -3, -6, -3],
 [-4, -7,  8, -7]]), Matrix([
 [-8,  3],
 [-4, -5],
 [ 5,  8],
 [ 2, -2]]), Matrix([
 [ 12,   3,  72,   3],
 [ 32,  47, -16,  47],
 [-47, -71,  34, -71],
 [  2,   8, -28,   8]]))

#### in R
- $A * B$ - element-wise multiplication

- $A \%*\% B$	- matrix multiplication

- $A \% o \% B$	- outer product AB'

In [155]:
%%r
A4; C4; A4 %*% C4

          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
          [,1]      [,2]      [,3]      [,4]       [,5]
[1,]  5.971833 4.5704932  2.116315 2.6474938  2.0918457
[2,]  4.244769 3.4688824  2.578513 0.7312220  8.2971376
[3,]  5.447669 0.3404288  4.022721 9.8283240  0.5694052
[4,] 16.116502 6.0128435  0.405711 0.9847488 12.8393433
[5,]  6.620679 6.1495929 10.603066 7.7490383 22.0010271
          [,1]      [,2]      [,3]      [,4]      [,5]
[1,]  248.7511 120.75672 209.90916 287.93624  301.0205
[2,]  137.4488  85.72732  88.00400  72.26375  224.4385
[3,] 1168.1675 638.98814 488.06990 467.87428 1393.6282
[4,]  204.5326 103.45484  71.50999  59.45904  260.5233
[5,]  293.6831 207.58618 259.20918 221.53676  552.491

In [156]:
%%r
A4; C4; C4 %*% A4

          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
          [,1]      [,2]      [,3]      [,4]       [,5]
[1,]  5.971833 4.5704932  2.116315 2.6474938  2.0918457
[2,]  4.244769 3.4688824  2.578513 0.7312220  8.2971376
[3,]  5.447669 0.3404288  4.022721 9.8283240  0.5694052
[4,] 16.116502 6.0128435  0.405711 0.9847488 12.8393433
[5,]  6.620679 6.1495929 10.603066 7.7490383 22.0010271
         [,1]      [,2]     [,3]     [,4]     [,5]
[1,] 145.8440  71.46216 142.6111 146.3097 216.3770
[2,] 204.2187  84.60527 132.7172 167.7155 321.1802
[3,] 201.1723  45.71987 132.7837 273.7815 263.9237
[4,] 255.1287 134.66995 358.2722 126.0728 483.7381
[5,] 648.2470 215.67214 286.6899 640.2297 945.1926


In [157]:
%%r
A4 %*% C4 == C4 %*% A4

      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE
[4,] FALSE FALSE FALSE FALSE FALSE
[5,] FALSE FALSE FALSE FALSE FALSE


## 3. Задание.

Инициировать матрицы $A(2x4)$ и $B(4x2)$ и рассчитать их сумму ($A+B$) и произведения ($A*B, \ B*A$)

с использованием SageMath, Numpy, SymPy, R.