<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №2</h1>

<a href="https://olgabelitskaya.github.io/README.html">&#x1F300; &nbsp; Home Page</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_1.ipynb">📓 &nbsp; Previous</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_3.ipynb">📓 &nbsp; Next</a>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы

## 1. Операции над матрицами
### 1.1 Возведение в степень

In [1]:
A=random_matrix(ZZ,5,x=0,y=100)
B=random_matrix(ZZ,5,x=-100,y=0)
mm=" ".join(list('m_%d%d'%(i,j) 
            for i in [1..3] for j in [1..3]))
M=matrix(SR,3,var(mm)) 
nn=" ".join(list('n_%d%d'%(i,j) 
            for i in [1..3] for j in [1..3]))
N=matrix(SR,3,var(nn))

In [2]:
pretty_print(A,B); pretty_print(M,N)
pretty_print(M^2)
pretty_print('A^3 = A*A*A: %s'%str(A^3==A*A*A))
pretty_print(A^3)

[65 75 32 54 10]
[12 83 39 31  8]
[56 11 67 34 87]
[20 88 93  7 22]
[ 1 84 29 21  4] [ -21  -53 -100  -32  -68]
[ -55  -20  -86  -72  -70]
[ -30  -11  -58   -3   -2]
[ -83  -83  -49 -100  -70]
[ -18  -88  -49  -19  -76]

[m_11 m_12 m_13]
[m_21 m_22 m_23]
[m_31 m_32 m_33] [n_11 n_12 n_13]
[n_21 n_22 n_23]
[n_31 n_32 n_33]

[   m_11^2 + m_12*m_21 + m_13*m_31 m_11*m_12 + m_12*m_22 + m_13*m_32 m_11*m_13 + m_12*m_23 + m_13*m_33]
[m_11*m_21 + m_21*m_22 + m_23*m_31    m_12*m_21 + m_22^2 + m_23*m_32 m_13*m_21 + m_22*m_23 + m_23*m_33]
[m_11*m_31 + m_21*m_32 + m_31*m_33 m_12*m_31 + m_22*m_32 + m_32*m_33    m_13*m_31 + m_23*m_32 + m_33^2]

'A^3 = A*A*A: True'

[1578281 3255224 2606948 1547495 1486819]
[1064711 2256093 1826816 1063011 1080255]
[1588568 3413056 2662088 1582783 1490343]
[1457691 3161351 2466851 1438697 1385622]
[ 808568 1757617 1429944  817932  844432]

In [9]:
import numpy,sympy
A1=numpy.matrix(numpy.random.randint(0,100,size=(5,5)))
B1=numpy.matrix(numpy.random.randint(-100,0,size=(5,5)))
A2=sympy.Matrix([[-3,-3,-6,-3],[-4,-7,8,-7],
                 [2,-3,9,-5],[6,-3,8,2]])
B2=sympy.Matrix([[-8,-4,5,2],[3,-5,8,-2],
                 [5,4,-8,1],[7,-2,9,5]])
mm=sympy.symbols(" ".join(list('m_%d%d' %(i,j) 
                 for i in [1,2,3] for j in [1,2,3])))
M=sympy.Matrix(int(3),int(3),mm) 
nn=sympy.symbols(" ".join(list('n_%d%d' %(i,j) 
                 for i in [1,2,3] for j in [1,2,3])))
N=sympy.Matrix(int(3),int(3),nn)

In [10]:
for el in [A1,B1]: print(el)
for el in [A2,B2,M,N]: sympy.pprint(el)
print(A1**int(3)==A1*A1*A1); print(A2^3==A2*A2*A2)
print(A1**int(3)); sympy.pprint(A2^3)

[[57 35 82  8 29]
 [97  0 62 35 26]
 [30  8 80  1 60]
 [98 46 60 94 21]
 [29 60 51  1 38]]
[[ -60  -80  -61  -91 -100]
 [ -64  -85  -79  -68  -29]
 [ -18  -95  -57  -74   -2]
 [ -46  -31  -52  -91  -50]
 [ -92  -45  -57  -85  -35]]
⎡-3  -3  -6  -3⎤
⎢              ⎥
⎢-4  -7  8   -7⎥
⎢              ⎥
⎢2   -3  9   -5⎥
⎢              ⎥
⎣6   -3  8   2 ⎦
⎡-8  -4  5   2 ⎤
⎢              ⎥
⎢3   -5  8   -2⎥
⎢              ⎥
⎢5   4   -8  1 ⎥
⎢              ⎥
⎣7   -2  9   5 ⎦
⎡m₁₁  m₁₂  m₁₃⎤
⎢             ⎥
⎢m₂₁  m₂₂  m₂₃⎥
⎢             ⎥
⎣m₃₁  m₃₂  m₃₃⎦
⎡n₁₁  n₁₂  n₁₃⎤
⎢             ⎥
⎢n₂₁  n₂₂  n₂₃⎥
⎢             ⎥
⎣n₃₁  n₃₂  n₃₃⎦
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
True
[[2037215 1140623 3002919  515649 1742693]
 [2481294 1222219 3364264  754791 1900565]
 [1586223  860572 2342649  332083 1408928]
 [4238389 2082513 5366976 1601685 2852296]
 [1757828  985763 2547290  

In [11]:
%%r
A<-matrix(rexp(49,rate=0.1),nrow=7,ncol=7) 
B<-matrix(rexp(49,rate=1.0),nrow=7,ncol=7)
library(Matrix)

[1] "Matrix"    "tools"     "stats"     "graphics"  "grDevices" "utils"    
[7] "datasets"  "methods"   "base"


In [12]:
%%r
AP<-A%*%A%*%A # Matrix Power 
expm(B) # Matrix Exponential
matrix(c(A,B,AP,B),nrow=7)

           [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
[1,]  8.5905794 28.055757  5.544592 46.036219 10.673266  2.542988  6.466423
[2,]  4.1642001  5.789427 12.885968  1.332868 65.185268  8.732660  8.305124
[3,]  0.5360842 12.038240  0.665423  4.745214 14.563884 24.863652 20.589531
[4,] 37.7957455  6.835676 12.857274  4.182911  3.910649 26.330004 17.266585
[5,]  9.0514115 11.014719  4.589773  5.839543 22.800490  1.741804 14.076278
[6,]  7.8284320  1.451585  4.425303  1.356473  1.123814  7.074737 14.074253
[7,]  4.9746267  2.158784  9.964632 19.930931  4.724029 32.408054 35.351161
          [,8]       [,9]      [,10]       [,11]     [,12]     [,13]     [,14]
[1,] 0.5200754 2.43683592 0.08059778 1.652155571 2.0057791 0.9052351 0.2082438
[2,] 1.0335650 2.54848983 0.83361777 2.039018299 0.2728333 2.1047306 0.5650266
[3,] 1.1171442 0.03778145 0.87132942 0.008152395 0.5455714 0.2311155 1.4975198
[4,] 0.5685954 0.73730024 0.49788886 0.241557481 4.3933869 0.2894384 0.43767

### 1.2 Транспонирование

In [3]:
[M.T.T==M,(M+N).T==M.T+N.T,(M-N).T==\
 M.T-N.T,(var('k')*M).T==var('k')*M.T,
 (M*N).T==N.T*M.T]

[True, True, True, True, True]

In [4]:
pretty_print(M,'->',M.T)
pretty_print((M+N).T,(M*N).T)

[m_11 m_12 m_13]
[m_21 m_22 m_23]
[m_31 m_32 m_33] '->' [m_11 m_21 m_31]
[m_12 m_22 m_32]
[m_13 m_23 m_33]

[m_11 + n_11 m_21 + n_21 m_31 + n_31]
[m_12 + n_12 m_22 + n_22 m_32 + n_32]
[m_13 + n_13 m_23 + n_23 m_33 + n_33] [m_11*n_11 + m_12*n_21 + m_13*n_31 m_21*n_11 + m_22*n_21 + m_23*n_31 m_31*n_11 + m_32*n_21 + m_33*n_31]
[m_11*n_12 + m_12*n_22 + m_13*n_32 m_21*n_12 + m_22*n_22 + m_23*n_32 m_31*n_12 + m_32*n_22 + m_33*n_32]
[m_11*n_13 + m_12*n_23 + m_13*n_33 m_21*n_13 + m_22*n_23 + m_23*n_33 m_31*n_13 + m_32*n_23 + m_33*n_33]

In [13]:
print(A1); print(numpy.transpose(A1))
sympy.pprint(A2); sympy.pprint(A2.T)

[[57 35 82  8 29]
 [97  0 62 35 26]
 [30  8 80  1 60]
 [98 46 60 94 21]
 [29 60 51  1 38]]
[[57 97 30 98 29]
 [35  0  8 46 60]
 [82 62 80 60 51]
 [ 8 35  1 94  1]
 [29 26 60 21 38]]
⎡-3  -3  -6  -3⎤
⎢              ⎥
⎢-4  -7  8   -7⎥
⎢              ⎥
⎢2   -3  9   -5⎥
⎢              ⎥
⎣6   -3  8   2 ⎦
⎡-3  -4  2   6 ⎤
⎢              ⎥
⎢-3  -7  -3  -3⎥
⎢              ⎥
⎢-6  8   9   8 ⎥
⎢              ⎥
⎣-3  -7  -5  2 ⎦


In [14]:
print(numpy.transpose(A1+B1))
print(numpy.transpose(A1*B1))
sympy.pprint((A2+B2).T)
sympy.pprint((A2*B2).T)

[[ -3  33  12  52 -63]
 [-45 -85 -87  15  15]
 [ 21 -17  23   8  -6]
 [-83 -33 -73   3 -84]
 [-71  -3  58 -29   3]]
[[-10172 -10938  -9318 -16160 -10040]
 [-16878 -15905 -13411 -21309 -14006]
 [-12985 -12753 -10494 -19117 -11634]
 [-16828 -18810 -14385 -26825 -13814]
 [ -8294 -12484  -5542 -16689  -6122]]
⎡-11  -1   7   13⎤
⎢                ⎥
⎢-7   -12  1   -5⎥
⎢                ⎥
⎢-1   16   1   17⎥
⎢                ⎥
⎣-1   -9   -4  7 ⎦
⎡-36   2    -15   -3 ⎤
⎢                    ⎥
⎢ 9    97    53   19 ⎥
⎢                    ⎥
⎢-18  -203  -131  -40⎥
⎢                    ⎥
⎣-21  -21    -6   36 ⎦


In [15]:
%%r
matrix(c(A,t(A)),nrow=7)

           [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
[1,]  8.5905794 28.055757  5.544592 46.036219 10.673266  2.542988  6.466423
[2,]  4.1642001  5.789427 12.885968  1.332868 65.185268  8.732660  8.305124
[3,]  0.5360842 12.038240  0.665423  4.745214 14.563884 24.863652 20.589531
[4,] 37.7957455  6.835676 12.857274  4.182911  3.910649 26.330004 17.266585
[5,]  9.0514115 11.014719  4.589773  5.839543 22.800490  1.741804 14.076278
[6,]  7.8284320  1.451585  4.425303  1.356473  1.123814  7.074737 14.074253
[7,]  4.9746267  2.158784  9.964632 19.930931  4.724029 32.408054 35.351161
          [,8]      [,9]      [,10]     [,11]     [,12]     [,13]     [,14]
[1,]  8.590579  4.164200  0.5360842 37.795745  9.051412  7.828432  4.974627
[2,] 28.055757  5.789427 12.0382395  6.835676 11.014719  1.451585  2.158784
[3,]  5.544592 12.885968  0.6654230 12.857274  4.589773  4.425303  9.964632
[4,] 46.036219  1.332868  4.7452137  4.182911  5.839543  1.356473 19.930931
[5,] 10.6732

In [16]:
%%r
matrix(c(t(A),t(B),t(A+B),t(A%*%B)),nrow=7)

          [,1]      [,2]       [,3]      [,4]      [,5]      [,6]      [,7]
[1,]  8.590579  4.164200  0.5360842 37.795745  9.051412  7.828432  4.974627
[2,] 28.055757  5.789427 12.0382395  6.835676 11.014719  1.451585  2.158784
[3,]  5.544592 12.885968  0.6654230 12.857274  4.589773  4.425303  9.964632
[4,] 46.036219  1.332868  4.7452137  4.182911  5.839543  1.356473 19.930931
[5,] 10.673266 65.185268 14.5638835  3.910649 22.800490  1.123814  4.724029
[6,]  2.542988  8.732660 24.8636518 26.330004  1.741804  7.074737 32.408054
[7,]  6.466423  8.305124 20.5895312 17.266585 14.076278 14.074253 35.351161
           [,8]      [,9]       [,10]     [,11]     [,12]     [,13]     [,14]
[1,] 0.52007538 1.0335650 1.117144171 0.5685954 3.6321777 1.0342282 3.3405553
[2,] 2.43683592 2.5484898 0.037781448 0.7373002 0.2274117 1.1092115 1.0673944
[3,] 0.08059778 0.8336178 0.871329420 0.4978889 0.4719980 0.1311454 6.1946473
[4,] 1.65215557 2.0390183 0.008152395 0.2415575 2.4099854 1.9763582 0.3069290
[5

## 2. След матрицы
<table border="1">
        <thead>
            <tr>
                <th>-</th>
                <th>1</th>
                <th>2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="font-weight:bold;">1</td>
                <td style="color:#3636ff;">$A_{11}$</td>
                <td>$A_{12}$</td>
                <td>$A_{13}$</td>
                <td>$A_{14}$</td>
                <td>$A_{15}$</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">2</td>
                <td>$A_{21}$</td>
                <td style="color:#3636ff;">$A_{22}$</td>
                <td>$A_{23}$</td>
                <td>$A_{24}$</td>
                <td>$A_{25}$</td>
            </tr>
                        <tr>
                <td style="font-weight:bold;">3</td>
                <td>$A_{31}$</td>
                <td>$A_{32}$</td>
                <td style="color:#3636ff;">$A_{33}$</td>
                <td>$A_{34}$</td>
                <td>$A_{35}$</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">4</td>
                <td>$A_{41}$</td>
                <td>$A_{42}$</td>
                <td>$A_{43}$</td>
                <td style="color:#3636ff;">$A_{44}$</td>
                <td>$A_{45}$</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">5</td>
                <td>$A_{51}$</td>
                <td>$A_{52}$</td>
                <td>$A_{53}$</td>
                <td>$A_{54}$</td>
                <td style="color:#3636ff;">$A_{55}$</td>
            </tr>
        </tbody>
    </table>
    
$TR = A_{11} + A_{22} + A_{33} + A_{44} + A_{55}$ 

In [5]:
pretty_print(A,'->',A.trace())
pretty_print(B,'->',B.trace())

[65 75 32 54 10]
[12 83 39 31  8]
[56 11 67 34 87]
[20 88 93  7 22]
[ 1 84 29 21  4] '->' 226

[ -21  -53 -100  -32  -68]
[ -55  -20  -86  -72  -70]
[ -30  -11  -58   -3   -2]
[ -83  -83  -49 -100  -70]
[ -18  -88  -49  -19  -76] '->' -275

In [17]:
print(numpy.trace(A1),
      sum(numpy.diagonal(A1))==numpy.trace(A1))
[sympy.trace(A2),
sum([A2[i,j] for i in [0..A2.shape[0]-1] 
             for j in [0..A2.shape[0]-1] 
             if i==j])==sympy.trace(A2)]

(269, True)


[1, True]

In [18]:
%%r
print(c(dim(A)[1]==dim(A)[2],
        dim(B)[1]==dim(B)[2]))
c(sum(diag(A)),sum(diag(B)))

[1] TRUE TRUE
[1] 84.45473 10.63454


## 3. Норма матрицы

In [6]:
pretty_print(A.norm(p=1),
             ' - the largest column-sum norm')
pretty_print(A.norm(p=1)>=0,
             (-1*A).norm(p=1)==abs(-1)*A.norm(p=1),
             (A+B).norm(p=1)<=A.norm(p=1)+B.norm(p=1),
             (A*B).norm(p=1)<=A.norm(p=1)*B.norm(p=1))
pretty_print(A.norm(p=2),' - the Euclidean norm')
pretty_print(A.norm(p=2)>=0,
             (-2*A).norm(p=2)==abs(-2)*A.norm(p=2),
             (A+B).norm(p=2)<=A.norm(p=2)+B.norm(p=2),
             (A*B).norm(p=2)<=A.norm(p=2)*B.norm(p=2))
pretty_print(A.norm(p=oo),
             ' - the largest row-sum norm norm')
pretty_print(A.norm(p=oo)>=0,
             (-3*A).norm(p=oo)==abs(-3)*A.norm(p=oo),
             (A+B).norm(p=oo)<=A.norm(p=oo)+B.norm(p=oo),
             (A*B).norm(p=oo)<=A.norm(p=oo)*B.norm(p=oo))
pretty_print(A.norm(p='frob'),
             ' - the Frobenius (sum of squares) norm')
pretty_print(A.norm(p=oo)>=0,
             (-4*A).norm(p=oo)==abs(-4)*A.norm(p='frob'),
             (A+B).norm(p='frob')<=A.norm(p='frob')+B.norm(p='frob'),
             (A*B).norm(p='frob')<=A.norm(p='frob')*B.norm(p='frob'))

341.0 ' - the largest column-sum norm'

True True True True

224.4288329283189 ' - the Euclidean norm'

True True True True

255.0 ' - the largest row-sum norm norm'

True True True True

256.1659618294359 ' - the Frobenius (sum of squares) norm'

True False True True

In [21]:
print(str(numpy.linalg.norm(A1,1))+\
      ' - the largest column-sum norm')
print(numpy.linalg.norm(A1,1)==numpy.max(sum(abs(A1),
      axis=0)))
print(str(numpy.linalg.norm(A1,-1))+\
      ' - the smalest column-sum norm')
print(numpy.linalg.norm(A1,-1)==numpy.min(sum(abs(A1),axis=0)))
print(str(numpy.linalg.norm(A1,2))+\
      ' - the Euclidean norm (which is equal'+\
      ' to the largest singular value of a matrix)')
print(str(numpy.linalg.norm(A1,-2))+\
      ' - the smallest singular value')
print(str(numpy.linalg.norm(A1,numpy.inf))+\
      ' - the largest row-sum norm')
print(numpy.linalg.norm(A1,numpy.infty)==numpy.max(sum(abs(A1),
      axis=1)))
print(str(numpy.linalg.norm(A1,-numpy.inf))+\
      ' - the smallest row-sum norm')
print(numpy.linalg.norm(A1,
      -numpy.infty)==numpy.min(sum(abs(A1),
      axis=1)))
print(str(numpy.linalg.norm(A1,'fro'))+\
      ' - the Frobenius (sum of squares) norm')
print(str(numpy.linalg.norm(A1,'nuc'))+\
      '- the nuclear norm')
print(30*'=-=')
[A2.norm(1),A2.norm(oo),
 A2.norm('fro'),round(A2.norm('fro'),2)]

335.0 - the largest column-sum norm
True
139.0 - the smalest column-sum norm
True
242.21860667987545 - the Euclidean norm (which is equal to the largest singular value of a matrix)
15.035837774067339 - the smallest singular value
319.0 - the largest row-sum norm
True
179.0 - the smallest row-sum norm
True
267.0318333083155 - the Frobenius (sum of squares) norm
434.1275277780401- the nuclear norm
=-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-=


[31, 26, sqrt(473), 21.75]

#### In R
Matrix norm (type):

- "O", "o" or "1"
  - maximum absolute column sum;

- "I" or "i"
  - maximum absolute row sum;

- "F" or "f"
  - the Euclidean norm of a matrix treated as if it were a vector;

- "M" or "m"
  - the maximum modulus of all the elements in a matrix; 

- "2"
  - the “spectral” or 2-norm, which is the largest singular value (svd) of a matrix.

In [22]:
%%r
A<-matrix(rexp(49,rate=0.1),nrow=7,ncol=7)
#"O", "o" or "1" - the maximum absolute column sum
print(norm(A,type="O")) 
#"I" or "i" - the maximum absolute row sum
print(norm(A,type="I"))
#"F" or "f" - the Euclidean norm of a matrix treated as if it were a vector
print(norm(A,type="F"))
#"M" or "m" - the maximum modulus of all the elements in a matrix
print(norm(A,type="M"))
#"2" - the “spectral” or 2-norm, 
#which is the largest singular value (svd) of a matrix
norm(A,type="2")

[1] 69.44913
[1] 91.81856
[1] 70.21392
[1] 26.88156
[1] 58.74793


## 4. Задание.

Инициировать матрицу $A(3x3)$ и рассчитать $A^2$, $A^T$, 

а также найти след и нормы матрицы с использованием SageMath, Numpy, SymPy, R.