<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №1</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы. 

## 1. Способы инициализации.

In [22]:
%%latex
$A = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}$

<IPython.core.display.Latex object>

In [23]:
# sage
A1 = random_matrix(ZZ,5,x=0,y=100)
C1 = random_matrix(ZZ,5,x=-100,y=0)
B1 = matrix([[1.1,3.2,5.0,7.6],[2.2,4.1,6.5,8.1]])
A1, B1

(
[69 10 12 34 90]
[86 19 30 51 93]
[ 9 85 37 44 77]
[91  2 72 48 54]
[86 35 30 99 39],

[1.10000000000000 3.20000000000000 5.00000000000000 7.60000000000000]
[2.20000000000000 4.10000000000000 6.50000000000000 8.10000000000000]
)

In [24]:
A1.base_ring(), B1.base_ring()

(Integer Ring, Real Field with 53 bits of precision)

In [25]:
A1.ncols(), A1.nrows(), A1.dimensions()

(5, 5, (5, 5))

In [26]:
latex(A1)

\left(\begin{array}{rrrrr}
69 & 10 & 12 & 34 & 90 \\
86 & 19 & 30 & 51 & 93 \\
9 & 85 & 37 & 44 & 77 \\
91 & 2 & 72 & 48 & 54 \\
86 & 35 & 30 & 99 & 39
\end{array}\right)

In [27]:
html(B1)

<script type="math/tex">\left(\begin{array}{rrrr} 1.10000000000000 & 3.20000000000000 & 5.00000000000000 & 7.60000000000000 \\ 2.20000000000000 & 4.10000000000000 & 6.50000000000000 & 8.10000000000000 \end{array}\right)</script>

In [28]:
print(html(B1))

<script type="math/tex">\left(\begin{array}{rrrr} 1.10000000000000 & 3.20000000000000 & 5.00000000000000 & 7.60000000000000 \\ 2.20000000000000 & 4.10000000000000 & 6.50000000000000 & 8.10000000000000 \end{array}\right)</script>


In [29]:
E1 = matrix.identity(3)
E1

[1 0 0]
[0 1 0]
[0 0 1]

In [36]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(5,7)))
C2 = numpy.matrix(numpy.random.randint(-100, 0, size=(5,7)))
B2 = numpy.matrix([[1,3,5,7],[2,4,6,8]])
print(A2) 
print(B2)

[[61 49 90 76 81  5 67]
 [ 2 44 24 78 58 16 23]
 [13 31  5  5 61 97  0]
 [88 34 79 12 86 45 19]
 [83 44 86 17 83 20 28]]
[[1 3 5 7]
 [2 4 6 8]]


In [119]:
A2.shape

(5, 7)

In [41]:
E2 = numpy.matrix(numpy.eye(3))
print(E2)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [42]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3, -6,-3], [-4, -7, 8,-7]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8], [7, 4, -6]])
C3 = sympy.Matrix([[-8, -4, 5, 2], [3, -5, 8, -2]])
sympy.pprint(A3)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦


In [43]:
A3.shape

(2, 4)

In [44]:
E3 = sympy.Identity(3)
sympy.pprint(E3.as_explicit())

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦


In [137]:
%%r
A4 <- matrix(rexp(25, rate=0.1), nrow=5, ncol=5)
B4 <- matrix(c(1,3,5,7,2,4,6,8), nrow=2, ncol=4)
C4 <- matrix(rexp(25, rate=0.2), nrow=5, ncol=5)
D4 <- matrix(sample.int(100, size=3*4, replace=T), nrow=3, ncol=4)
A4; B4; D4





          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
     [,1] [,2] [,3] [,4]
[1,]    1    5    2    6
[2,]    3    7    4    8
     [,1] [,2] [,3] [,4]
[1,]   64   23    5   83
[2,]   88   32   52   62
[3,]   52   46   99   90


In [ ]:
%%r
require(DT)
datatable(A4)

In [88]:
%%r
dim(A4)

[1] 5 5


In [128]:
%%r
E4 <- matrix(0, 5, 5)
diag(E4) <- 1
E4



     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    1    0    0    0
[3,]    0    0    1    0    0
[4,]    0    0    0    1    0
[5,]    0    0    0    0    1


## 2. Операции над матрицами.
### 2.1 Умножение на число

In [50]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i')) 
html(var('k') * M)

<script type="math/tex">\left(\begin{array}{rrr} a k & b k & c k \\ d k & e k & f k \\ g k & h k & i k \end{array}\right)</script>

In [122]:
A1, 2*A1

(
[ 9 88 20 40 33]  [ 18 176  40  80  66]
[50 18 89 99 41]  [100  36 178 198  82]
[33  5 87 12 32]  [ 66  10 174  24  64]
[49 51 22 80 33]  [ 98 102  44 160  66]
[11 87 60 19 73], [ 22 174 120  38 146]
)

In [45]:
print(A2)
print(-3*A2)

[[61 49 90 76 81  5 67]
 [ 2 44 24 78 58 16 23]
 [13 31  5  5 61 97  0]
 [88 34 79 12 86 45 19]
 [83 44 86 17 83 20 28]]
[[-183 -147 -270 -228 -243  -15 -201]
 [  -6 -132  -72 -234 -174  -48  -69]
 [ -39  -93  -15  -15 -183 -291    0]
 [-264 -102 -237  -36 -258 -135  -57]
 [-249 -132 -258  -51 -249  -60  -84]]


In [47]:
sympy.pprint(A3)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦


In [48]:
sympy.pprint(1.5*A3)

⎡-4.5  -4.5   -9.0  -4.5 ⎤
⎢                        ⎥
⎣-6.0  -10.5  12.0  -10.5⎦


In [126]:
%%r
A4; 5*A4

          [,1]      [,2]      [,3]       [,4]       [,5]
[1,]  9.733919  1.220253 18.856894  5.9963881  0.4458297
[2,] 12.894345 17.439791  9.749427  0.1861919  0.2675028
[3,]  4.695959 15.531201 10.316556  7.6798607  5.0276754
[4,]  9.903369 15.528524 10.104245 10.7261280 22.1038481
[5,] 10.642159  2.494848 16.307512  1.6457923  1.8189122
         [,1]      [,2]     [,3]       [,4]       [,5]
[1,] 48.66959  6.101266 94.28447 29.9819407   2.229149
[2,] 64.47172 87.198955 48.74713  0.9309594   1.337514
[3,] 23.47980 77.656005 51.58278 38.3993033  25.138377
[4,] 49.51685 77.642618 50.52123 53.6306398 110.519241
[5,] 53.21079 12.474242 81.53756  8.2289614   9.094561


### 2.2 Сложение и вычитание матриц

In [51]:
M1 = matrix(SR, 3, var('a1,b1,c1,d1,e1,f1,g1,h1,i1')) 
M2 = matrix(SR, 3, var('a2,b2,c2,d2,e2,f2,g2,h2,i2'))
html(M1 + M2)

<script type="math/tex">\left(\begin{array}{rrr} a_{1} + a_{2} & b_{1} + b_{2} & c_{1} + c_{2} \\ d_{1} + d_{2} & e_{1} + e_{2} & f_{1} + f_{2} \\ g_{1} + g_{2} & h_{1} + h_{2} & i_{1} + i_{2} \end{array}\right)</script>

In [64]:
M1 + M2 == M2 + M1

True

In [131]:
A1, C1, A1 + C1

(
[22 15 78 52 90]  [-15 -44 -48 -32 -27]  [  7 -29  30  20  63]
[50 22 60 16 74]  [-87 -70 -48 -36 -39]  [-37 -48  12 -20  35]
[49  4 96 41 53]  [-99  -1 -27  -8 -29]  [-50   3  69  33  24]
[26 24  8 71 96]  [-22 -40 -19 -34 -39]  [  4 -16 -11  37  57]
[13 52 69 17 16], [-35 -64  -7 -28 -94], [-22 -12  62 -11 -78]
)

In [62]:
print(A2)
print(C2)
print(A2 - C2)

[[61 49 90 76 81  5 67]
 [ 2 44 24 78 58 16 23]
 [13 31  5  5 61 97  0]
 [88 34 79 12 86 45 19]
 [83 44 86 17 83 20 28]]
[[ -75  -95  -31  -83  -80  -83  -25]
 [ -72  -44  -43  -27   -3  -32  -42]
 [ -22  -91  -51  -18  -78  -31  -56]
 [  -9  -93  -53  -92  -45  -97  -26]
 [  -5  -68  -57   -5  -36 -100  -86]]
[[136 144 121 159 161  88  92]
 [ 74  88  67 105  61  48  65]
 [ 35 122  56  23 139 128  56]
 [ 97 127 132 104 131 142  45]
 [ 88 112 143  22 119 120 114]]


In [63]:
sympy.pprint(A3), sympy.pprint(C3), sympy.pprint(A3 + C3)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-8  -4  5  2 ⎤
⎢             ⎥
⎣3   -5  8  -2⎦
⎡-11  -7   -1  -1⎤
⎢                ⎥
⎣-1   -12  16  -9⎦


(None, None, None)

In [139]:
%%r
A4; C4; A4 - C4

          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
          [,1]      [,2]      [,3]      [,4]       [,5]
[1,]  5.971833 4.5704932  2.116315 2.6474938  2.0918457
[2,]  4.244769 3.4688824  2.578513 0.7312220  8.2971376
[3,]  5.447669 0.3404288  4.022721 9.8283240  0.5694052
[4,] 16.116502 6.0128435  0.405711 0.9847488 12.8393433
[5,]  6.620679 6.1495929 10.603066 7.7490383 22.0010271
            [,1]      [,2]       [,3]       [,4]      [,5]
[1,]   0.8555462 -2.922484 16.4272144 -0.9360693  8.840943
[2,]  -2.8750991  5.175831 -0.4938241  2.2462329 -3.277765
[3,]  29.9059194  4.509505  3.0886813 32.1145632 32.922896
[4,] -14.4954228 -4.797962 -0.3549455  8.4075973 -7.092713
[5,]   2.7972426 -2.024267 -7.180

### 2.3 Умножение матриц

In [20]:
M1, M2

(
[a1 b1 c1]  [a2 b2 c2]
[d1 e1 f1]  [d2 e2 f2]
[g1 h1 i1], [g2 h2 i2]
)

In [12]:
html(M1 * M2)

<script type="math/tex">\left(\begin{array}{rrr} a_{1} a_{2} + b_{1} d_{2} + c_{1} g_{2} & a_{1} b_{2} + b_{1} e_{2} + c_{1} h_{2} & a_{1} c_{2} + b_{1} f_{2} + c_{1} i_{2} \\ a_{2} d_{1} + d_{2} e_{1} + f_{1} g_{2} & b_{2} d_{1} + e_{1} e_{2} + f_{1} h_{2} & c_{2} d_{1} + e_{1} f_{2} + f_{1} i_{2} \\ a_{2} g_{1} + d_{2} h_{1} + g_{2} i_{1} & b_{2} g_{1} + e_{2} h_{1} + h_{2} i_{1} & c_{2} g_{1} + f_{2} h_{1} + i_{1} i_{2} \end{array}\right)</script>

In [52]:
# sage
A1, C1, A1 * C1

(
[69 10 12 34 90]  [-84 -64  -7 -14 -65]
[86 19 30 51 93]  [-85 -67 -47 -59 -35]
[ 9 85 37 44 77]  [-24 -86 -65 -69 -93]
[91  2 72 48 54]  [-74 -49 -10 -77 -42]
[86 35 30 99 39], [-49 -37 -70 -68 -68],

[-13860 -11114  -8373 -11122 -13499]
[-17890 -15297 -10465 -14646 -17511]
[-15898 -14458 -12293 -16318 -14085]
[-15740 -16500  -9671 -13728 -18369]
[-20156 -16723  -7917 -15614 -16415]
)

In [53]:
A1, C1, C1 * A1

(
[69 10 12 34 90]  [-84 -64  -7 -14 -65]
[86 19 30 51 93]  [-85 -67 -47 -59 -35]
[ 9 85 37 44 77]  [-24 -86 -65 -69 -93]
[91  2 72 48 54]  [-74 -49 -10 -77 -42]
[86 35 30 99 39], [-49 -37 -70 -68 -68],

[-18227  -4954  -6145 -13535 -17342]
[-20429  -7461 -10067 -14672 -22051]
[-23914 -10792 -13031 -20581 -22516]
[-20029  -4145  -9532 -13309 -17783]
[-19229  -9659 -11224 -16629 -19565]
)

In [54]:
# python numpy
print(A2)
print(C2.T)
print(A2 * C2.T)

[[61 49 90 76 81  5 67]
 [ 2 44 24 78 58 16 23]
 [13 31  5  5 61 97  0]
 [88 34 79 12 86 45 19]
 [83 44 86 17 83 20 28]]
[[ -75  -72  -22   -9   -5]
 [ -95  -44  -91  -93  -68]
 [ -31  -43  -51  -53  -57]
 [ -83  -27  -18  -92   -5]
 [ -80   -3  -78  -45  -36]
 [ -83  -32  -31  -97 -100]
 [ -25  -42  -56  -26  -86]]
[[-26898 -15687 -21984 -22740 -18325]
 [-18091  -6870 -12984 -17318 -10426]
 [-17421  -5937 -11217 -15879 -14379]
 [-24365 -14049 -18442 -17974 -16545]
 [-23482 -14134 -19184 -17364 -15790]]


In [55]:
print(A2)
print(C2.T)
print(C2.T * A2)

[[61 49 90 76 81  5 67]
 [ 2 44 24 78 58 16 23]
 [13 31  5  5 61 97  0]
 [88 34 79 12 86 45 19]
 [83 44 86 17 83 20 28]]
[[ -75  -72  -22   -9   -5]
 [ -95  -44  -91  -93  -68]
 [ -31  -43  -51  -53  -57]
 [ -83  -27  -18  -92   -5]
 [ -80   -3  -78  -45  -36]
 [ -83  -32  -31  -97 -100]
 [ -25  -42  -56  -26  -86]]
[[ -6212  -8051  -9729 -11619 -12782  -4166  -6992]
 [-20894 -15566 -23256 -13379 -29440 -15551 -11048]
 [-12035  -9302 -13166  -7570 -17405  -9315  -5669]
 [-13862  -9161 -15906  -9693 -17714  -6833  -8070]
 [-12848  -9584 -14313  -7856 -18270 -10759  -7292]
 [-22366 -14134 -24656 -11823 -27112 -10299 -10940]
 [-11763  -9477 -12988  -7230 -17251  -9119  -5543]]


In [56]:
print(numpy.dot(A2, C2.T) == A2 * C2.T)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [57]:
print(numpy.dot(A2, C2.T))
print(C2.T * A2)

[[-26898 -15687 -21984 -22740 -18325]
 [-18091  -6870 -12984 -17318 -10426]
 [-17421  -5937 -11217 -15879 -14379]
 [-24365 -14049 -18442 -17974 -16545]
 [-23482 -14134 -19184 -17364 -15790]]
[[ -6212  -8051  -9729 -11619 -12782  -4166  -6992]
 [-20894 -15566 -23256 -13379 -29440 -15551 -11048]
 [-12035  -9302 -13166  -7570 -17405  -9315  -5669]
 [-13862  -9161 -15906  -9693 -17714  -6833  -8070]
 [-12848  -9584 -14313  -7856 -18270 -10759  -7292]
 [-22366 -14134 -24656 -11823 -27112 -10299 -10940]
 [-11763  -9477 -12988  -7230 -17251  -9119  -5543]]


In [58]:
# python numpy 
# !!! умножение матриц отличается от умножения массивов !!!
a = numpy.random.random((3,3))
b = numpy.random.random((3,3))
a * b # elementwise product

array([[ 0.00644113,  0.04917177,  0.25242828],
       [ 0.06741362,  0.00398764,  0.00486118],
       [ 0.1965309 ,  0.25350929,  0.16868733]])

In [65]:
a * b == b * a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [59]:
a.dot(b) # matrix product

array([[ 0.29969124,  0.62906997,  0.71883981],
       [ 0.31210013,  0.60110247,  0.644157  ],
       [ 0.18283911,  0.29339274,  0.47325683]])

In [66]:
a.dot(b) == b.dot(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [60]:
sympy.pprint(A3), sympy.pprint(C3.T), sympy.pprint(A3 * C3.T)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-8  3 ⎤
⎢      ⎥
⎢-4  -5⎥
⎢      ⎥
⎢5   8 ⎥
⎢      ⎥
⎣2   -2⎦
⎡0   -36⎤
⎢       ⎥
⎣86  101⎦


(None, None, None)

In [61]:
sympy.pprint(A3), sympy.pprint(C3.T), sympy.pprint(C3.T * A3)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-8  3 ⎤
⎢      ⎥
⎢-4  -5⎥
⎢      ⎥
⎢5   8 ⎥
⎢      ⎥
⎣2   -2⎦
⎡12    3   72    3 ⎤
⎢                  ⎥
⎢32   47   -16  47 ⎥
⎢                  ⎥
⎢-47  -71  34   -71⎥
⎢                  ⎥
⎣ 2    8   -28   8 ⎦


(None, None, None)

#### in R
- $A * B$ - element-wise multiplication

- $A \%*\% B$	- matrix multiplication

- $A \% o \% B$	- outer product AB'

In [155]:
%%r
A4; C4; A4 %*% C4

          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
          [,1]      [,2]      [,3]      [,4]       [,5]
[1,]  5.971833 4.5704932  2.116315 2.6474938  2.0918457
[2,]  4.244769 3.4688824  2.578513 0.7312220  8.2971376
[3,]  5.447669 0.3404288  4.022721 9.8283240  0.5694052
[4,] 16.116502 6.0128435  0.405711 0.9847488 12.8393433
[5,]  6.620679 6.1495929 10.603066 7.7490383 22.0010271
          [,1]      [,2]      [,3]      [,4]      [,5]
[1,]  248.7511 120.75672 209.90916 287.93624  301.0205
[2,]  137.4488  85.72732  88.00400  72.26375  224.4385
[3,] 1168.1675 638.98814 488.06990 467.87428 1393.6282
[4,]  204.5326 103.45484  71.50999  59.45904  260.5233
[5,]  293.6831 207.58618 259.20918 221.53676  552.491

In [156]:
%%r
A4; C4; C4 %*% A4

          [,1]     [,2]        [,3]      [,4]      [,5]
[1,]  6.827380 1.648009 18.54352941  1.711424 10.932788
[2,]  1.369670 8.644714  2.08468850  2.977455  5.019373
[3,] 35.353589 4.849933  7.11140207 41.942887 33.492301
[4,]  1.621079 1.214881  0.05076546  9.392346  5.746630
[5,]  9.417921 4.125326  3.42271047  4.230890 20.103201
          [,1]      [,2]      [,3]      [,4]       [,5]
[1,]  5.971833 4.5704932  2.116315 2.6474938  2.0918457
[2,]  4.244769 3.4688824  2.578513 0.7312220  8.2971376
[3,]  5.447669 0.3404288  4.022721 9.8283240  0.5694052
[4,] 16.116502 6.0128435  0.405711 0.9847488 12.8393433
[5,]  6.620679 6.1495929 10.603066 7.7490383 22.0010271
         [,1]      [,2]     [,3]     [,4]     [,5]
[1,] 145.8440  71.46216 142.6111 146.3097 216.3770
[2,] 204.2187  84.60527 132.7172 167.7155 321.1802
[3,] 201.1723  45.71987 132.7837 273.7815 263.9237
[4,] 255.1287 134.66995 358.2722 126.0728 483.7381
[5,] 648.2470 215.67214 286.6899 640.2297 945.1926


In [157]:
%%r
A4 %*% C4 == C4 %*% A4

      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE
[4,] FALSE FALSE FALSE FALSE FALSE
[5,] FALSE FALSE FALSE FALSE FALSE


## 3. Задание.

Инициировать матрицы $A(2x4)$ и $B(4x2)$ и рассчитать их сумму ($A+B$) и произведения ($A*B, \ B*A$)

с использованием SageMath, Numpy, SymPy, R.