<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №3</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы

## 1. Определители

In [7]:
M = matrix(SR, 2, var('a,b,c,d')) 
M, M.det()

(
[a b]            
[c d], -b*c + a*d
)

In [8]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i')) 
M, M.det()

(
[a b c]                                                
[d e f]                                                
[g h i], -(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g
)

In [29]:
# sage
A1 = random_matrix(ZZ,2,x=0,y=100)
B1 = random_matrix(ZZ,3,x=-100,y=0)
C1 = random_matrix(ZZ,4,x=-100,y=100)
A1, B1, C1

(
                           [ 45  13  94 -85]
         [ -70  -13  -79]  [-34 -20 -58  67]
[60 93]  [ -52  -53  -87]  [-58  68 -31  28]
[93 75], [ -58  -75 -100], [ 11  25  17  47]
)

In [30]:
A1.det(), B1.det(), C1.det()

(-4149, 22498, -7293820)

In [31]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(2,2)))
B2 = numpy.matrix(numpy.random.randint(-100, 0, size=(3,3)))
C2 = numpy.matrix(numpy.random.randint(-100, 100, size=(4,4)))
print(A2)
print(B2)
print(C2)

[[32 17]
 [39 31]]
[[-11 -99 -25]
 [-84 -42 -26]
 [-51 -40 -48]]
[[ 87   9 -22  82]
 [-27  63  24  67]
 [-66  28  37 -27]
 [-25  94  62 -61]]


In [32]:
round(numpy.linalg.det(A2)), round(numpy.linalg.det(B2)), round(numpy.linalg.det(C2))

(329.0, 226708.0, -8725969.0)

In [55]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3], [-4, -7]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8]])
C3 = sympy.Matrix([[-8, -4, 5, 2], [3, -5, 8, -2], [5, 4, -8, 1], [7, -2, 9, 5]])
sympy.pprint(C3)

⎡-8  -4  5   2 ⎤
⎢              ⎥
⎢3   -5  8   -2⎥
⎢              ⎥
⎢5   4   -8  1 ⎥
⎢              ⎥
⎣7   -2  9   5 ⎦


In [57]:
A3.det(), B3.det(), C3.det()

(9, -604, -1566)

In [66]:
%%r
A4 <- matrix(sample.int(100, size=2*2, replace=T), nrow=2, ncol=2)
B4 <- matrix(sample.int(100, size=3*3, replace=T), nrow=3, ncol=3)
C4 <- matrix(sample.int(100, size=4*4, replace=T), nrow=4, ncol=4)
A4; B4; C4




     [,1] [,2]
[1,]   28   80
[2,]   74    5
     [,1] [,2] [,3]
[1,]   63   78   51
[2,]   22   17    5
[3,]   42   21   68
     [,1] [,2] [,3] [,4]
[1,]   83   16   55   73
[2,]   33   47   94   96
[3,]   75   13   88   18
[4,]   80    3    3   52


In [67]:
%%r
det(A4); det(B4); det(C4)

[1] -5780
[1] -46947
[1] -4006338


## 2. Свойства определителей

In [131]:
# sage
A1 = random_matrix(ZZ,3,x=0,y=100)
B1 = random_matrix(ZZ,3,x=-100,y=0)
A1.det() == A1.T.det()

True

In [170]:
(A1 * B1).det() == (B1 * A1).det() == A1.det() * B1.det()

True

In [142]:
(-2 * A1).det() == (-2)^A1.dimensions()[0] * A1.det()

True

In [145]:
# строка или столбец состоит из нулей
C1 = matrix([[1,2,3],[0,0,0],[7,8,9]])
C1.det()

0

In [146]:
# линейно-зависимые строки или столбцы
C1 = matrix([[1,2,3],[2,4,6],[7,8,9]])
C1.det()

0

In [183]:
# python numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(3,3)))
B2 = numpy.matrix(numpy.random.randint(-100, 0, size=(3,3)))
round(numpy.linalg.det(A2)) == round(numpy.linalg.det(A2.T))

True

In [188]:
round(numpy.linalg.det(A2 * B2)) == \
round(numpy.linalg.det(B2 * A2)) == \
round(numpy.linalg.det(A2)) * round(numpy.linalg.det(B2))

True

In [186]:
round(numpy.linalg.det(-2 * A2)) == -2 ** A2.shape[0] * round(numpy.linalg.det(A2))

True

In [189]:
# строка или столбец состоит из нулей
C2 = numpy.matrix([[1,2,3],[0,0,0],[7,8,9]])
round(numpy.linalg.det(C2))

0.0

In [190]:
# линейно-зависимые строки или столбцы
C2 = numpy.matrix([[1,2,3],[2,4,6],[7,8,9]])
round(numpy.linalg.det(C2))

0.0

In [147]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3, 1], [-4, -7, 5], [2, 8, -7]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8]])
A3.det() == A3.T.det()

True

In [171]:
(A3 * B3).det() == (B3 * A3).det() == A3.det() * B3.det()

True

In [151]:
(-2 * A3).det() == (-2)^A3.shape[0] * A3.det()

True

In [152]:
# строка или столбец состоит из нулей
C3 = sympy.Matrix([[1,2,3],[0,0,0],[7,8,9]])
C3.det()

0

In [154]:
# линейно-зависимые строки или столбцы
C3 = sympy.Matrix([[1,2,3],[2,4,6],[7,8,9]])
C3.det()

0

In [156]:
%%r
A4 <- matrix(sample.int(100, size=3*3, replace=T), nrow=3, ncol=3)
B4 <- matrix(sample.int(100, size=3*3, replace=T), nrow=3, ncol=3)
det(A4) == det(t(A4))



[1] TRUE


In [160]:
%%r
det(A4 %*% B4) == det(A4) * det(B4)

[1] FALSE


In [172]:
%%r
all.equal(det(A4 %*% B4), det(B4 %*% A4), det(A4) * det(B4))

[1] TRUE


In [168]:
%%r
det(-2 * A4) == (-2)^(dim(A4)[1]) * det(A4)

[1] FALSE


In [169]:
%%r
all.equal(det(-2 * A4), (-2)^(dim(A4)[1]) * det(A4))

[1] TRUE


In [173]:
%%r
C4 <- matrix(c(1,3,5,0,0,0,2,4,6), nrow=3, ncol=3)
det(C4)


[1] 0


In [181]:
%%r
C4 <- matrix(c(1,3,5,2,6,10,-1,-2,-3), nrow=3, ncol=3)
det(C4); round(det(C4))


[1] -1.776357e-15
[1] 0


## 3. Миноры и алгебраические дополнения
Матрицы знаков для определителей 3-ого и 4-ого порядка 

In [63]:
%%latex
$ SIGN_{(3,3)} = 
 \begin{pmatrix}
+ & - & +  \\
- & + & - \\
+ & - & +  \\
 \end{pmatrix} \ \
SIGN_{(4,4)} = 
 \begin{pmatrix}
+ & - & + & - \\
- & + & - & + \\
+ & - & + & - \\
- & + & - & +
 \end{pmatrix}$

<IPython.core.display.Latex object>

Алгебраическое дополнение = Минор & Знак (+/-)

In [84]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i'))
M.minors(2)

[-b*d + a*e,
 -c*d + a*f,
 -c*e + b*f,
 -b*g + a*h,
 -c*g + a*i,
 -c*h + b*i,
 -e*g + d*h,
 -f*g + d*i,
 -f*h + e*i]

In [103]:
# разложение определителя по первому столбцу
M.det() == M[0,0] * M.minors(2)[8] - M[1,0] * M.minors(2)[5] + M[2,0] * M.minors(2)[2]

-(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g == -(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g

In [47]:
M = matrix(SR, 4, var('a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p'))
M.minors(3)

[-(g*j - f*k)*a + (c*j - b*k)*e - (c*f - b*g)*i,
 -(h*j - f*l)*a + (d*j - b*l)*e - (d*f - b*h)*i,
 -(h*k - g*l)*a + (d*k - c*l)*e - (d*g - c*h)*i,
 -(h*k - g*l)*b + (d*k - c*l)*f - (d*g - c*h)*j,
 -(g*n - f*o)*a + (c*n - b*o)*e - (c*f - b*g)*m,
 -(h*n - f*p)*a + (d*n - b*p)*e - (d*f - b*h)*m,
 -(h*o - g*p)*a + (d*o - c*p)*e - (d*g - c*h)*m,
 -(h*o - g*p)*b + (d*o - c*p)*f - (d*g - c*h)*n,
 -(k*n - j*o)*a + (c*n - b*o)*i - (c*j - b*k)*m,
 -(l*n - j*p)*a + (d*n - b*p)*i - (d*j - b*l)*m,
 -(l*o - k*p)*a + (d*o - c*p)*i - (d*k - c*l)*m,
 -(l*o - k*p)*b + (d*o - c*p)*j - (d*k - c*l)*n,
 -(k*n - j*o)*e + (g*n - f*o)*i - (g*j - f*k)*m,
 -(l*n - j*p)*e + (h*n - f*p)*i - (h*j - f*l)*m,
 -(l*o - k*p)*e + (h*o - g*p)*i - (h*k - g*l)*m,
 -(l*o - k*p)*f + (h*o - g*p)*j - (h*k - g*l)*n]

In [37]:
# sage
B1.minors(2)

[3034, 1982, -3056, 4496, 2418, -4625, 826, 154, -1225]

In [53]:
print(C1.minors(2))
print(C1.minors(3))

[-458, 586, 125, 1126, -829, 1368, 3814, 4057, -3670, -6795, 6144, -3, 982, -269, 3050, -2129, 2736, 5863, -3472, -2310, 2934, 4564, -5116, 453, -630, 60, -2335, 1110, -2615, -3865, -2198, -645, -3034, 1931, 2496, -1933]
[-90958, 26758, -59061, 98853, -10050, -33770, 40465, 101215, -111332, 338592, 253036, -423888, 48930, -292810, -153465, 312805]


In [78]:
# python only, i,j start from 0
def minor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i] + m[i+1:])]

def deternminant(m):
    if len(m) == 2:
        return m[0][0] * m[1][1] - m[0][1] * m[1][0]

    det = 0
    for c in range(len(m)):
        det += ((-1) ** c) * m[0][c] * deternminant(minor(m,0,c))
    return det

In [79]:
minor([[1,2,3],[-4,5,-6],[-7,8,-9]],1,1)

[[1, 3], [-7, -9]]

In [80]:
deternminant([[1,2,3],[-4,5,-6],[-7,8,-9]])

24

In [97]:
# python sympy
sympy.pprint(B3)

⎡2   10  7 ⎤
⎢          ⎥
⎢-5  -6  -2⎥
⎢          ⎥
⎣-8  4   -8⎦


In [96]:
B3[0,0]

2

In [105]:
sympy.pprint(B3.minorMatrix(0,0))

⎡-6  -2⎤
⎢      ⎥
⎣4   -8⎦


In [107]:
# разложение определителя по первому столбцу
B3.det() == \
B3[0,0] * B3.minorMatrix(0,0).det() - \
B3[1,0] * B3.minorMatrix(1,0).det() + \
B3[2,0] * B3.minorMatrix(2,0).det()

True

In [110]:
%%r
minor_matrix <- function(A, i, j) A[-i,-j]
minor <- function(A, i, j) det( A[-i,-j] )
cofactor <- function(A, i, j) (-1)^(i+j) * minor(A,i,j)

In [112]:
%%r
B4; B4[1,2]; minor_matrix(B4,1,2); minor(B4,1,2); cofactor(B4,1,2)

     [,1] [,2] [,3]
[1,]   63   78   51
[2,]   22   17    5
[3,]   42   21   68
[1] 78
     [,1] [,2]
[1,]   22    5
[2,]   42   68
[1] 1286
[1] -1286


In [128]:
%%r
det(B4) == (B4[1,1] * minor(B4,1,1) - B4[2,1] * minor(B4,2,1) + B4[3,1] * minor(B4,3,1))

[1] FALSE


In [126]:
%%r
all.equal(det(B4), (B4[1,1] * minor(B4,1,1) - B4[2,1] * minor(B4,2,1) + B4[3,1] * minor(B4,3,1)))

[1] TRUE


In [127]:
%%r
det(B4); (B4[1,1] * minor(B4,1,1) - B4[2,1] * minor(B4,2,1) + B4[3,1] * minor(B4,3,1))

[1] -46947
[1] -46947


## 4. Задание.

Инициировать матрицу $A(3x3)$, рассчитать определитель и исследовать его свойства 

с использованием SageMath, Numpy, SymPy, R.

Вычислить определитель с помощью разложения по третьему столбцу.