<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №14</h1>

### Программные средства

[LaTeX. Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Sage. Linear Algebra](http://doc.sagemath.org/html/en/tutorial/tour_linalg.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[R Functions - Tutorialspoint](https://www.tutorialspoint.com/r/r_functions.htm)

[Quick-R: User-Defined Functions](https://www.statmethods.net/management/userfunctions.html)

### Конспекты

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

[Курс лекций по линейной алгебре и геометрии](http://mech.math.msu.su/~manuilov/linalg2008.pdf)

[Computational Mathematics with SageMath](http://dl.lateralis.org/public/sagebook/sagebook-ba6596d.pdf)

[Introduction to Symbolic Computation](http://homepages.math.uic.edu/~jan/mcs320/mcs320.pdf)

# Тензоры

## 1. Основные понятия.
    
Тензор  типа $(p, q)$ - полилинейная функция:

- от $p$ векторов линейного простанства $V$ на полем $\mathbb{K}$ 

- и $q$ линейных функций двойственного к нему пространства $V'$, 

- принимающая значения в $\mathbb{K}$,

- линейная по каждому аргументу при фиксированных остальных аргументах.

_Примеры:_

1) скаляры — тензоры типа (0, 0) $\mathbb{K}$;

2) векторы — тензоры типа (0, 1) $\mathbb{K} \to V$;

3) линейные функции — тензоры типа (1, 0) $V \to \mathbb{K}$;

4) билинейные функции — тензоры типа (2, 0) $V \times V \to \mathbb{K}$;

5) линейные операторы — тензоры типа (1, 1) $V \to V$.

In [27]:
M = FiniteRankFreeModule(ZZ, 3, name='M')
e = M.basis('e')

T00 = M.tensor_module(0,0); T10 = M.tensor_module(1,0); T01 = M.tensor_module(0,1)
T11 = M.tensor_module(1,1); T20 = M.tensor_module(2,0); T02 = M.tensor_module(0,2)
T21 = M.tensor_module(2,1); T12 = M.tensor_module(1,2)
T30 = M.tensor_module(3,0); T03 = M.tensor_module(0,3)
T = [T00, T10, T01, T11, T20, T02, T21, T12, T30, T03]
T[3]

Free module of type-(1,1) tensors on the Rank-3 free module M over the Integer Ring

In [28]:
for t in T: 
    print(t.rank(), t.base_ring())
    if t != T00: print(t.an_element().tensor_type())

(1, Integer Ring)
(3, Integer Ring)
(1, 0)
(3, Integer Ring)
(0, 1)
(9, Integer Ring)
(1, 1)
(9, Integer Ring)
(2, 0)
(9, Integer Ring)
(0, 2)
(27, Integer Ring)
(2, 1)
(27, Integer Ring)
(1, 2)
(27, Integer Ring)
(3, 0)
(27, Integer Ring)
(0, 3)


In [41]:
A = M.linear_form(name='A') ; A[:] = (-1, 2, -3)
B = M([4,-5,6], name='B')
print(A.display(e), A.tensor_type())
print(B.display(e), B.tensor_type())

(A = -e^0 + 2 e^1 - 3 e^2, (0, 1))
(B = 4 e_0 - 5 e_1 + 6 e_2, (1, 0))


In [46]:
AB = A*B
print(AB.display(e))
print(AB.tensor_type())
MAB = matrix(AB.comp(e)); MAB

A*B = -4 e_0*e^0 + 8 e_0*e^1 - 12 e_0*e^2 + 5 e_1*e^0 - 10 e_1*e^1 + 15 e_1*e^2 - 6 e_2*e^0 + 12 e_2*e^1 - 18 e_2*e^2
(1, 1)


[ -4   8 -12]
[  5 -10  15]
[ -6  12 -18]

In [51]:
v1 = matrix(SR, 3, [1,2,3]); MAB * v1

[-24]
[ 30]
[-36]