<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №3</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы

## 1. Определители

In [7]:
M = matrix(SR, 2, var('a,b,c,d')) 
M, M.det()

(
[a b]            
[c d], -b*c + a*d
)

In [8]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i')) 
M, M.det()

(
[a b c]                                                
[d e f]                                                
[g h i], -(f*h - e*i)*a + (c*h - b*i)*d - (c*e - b*f)*g
)

In [29]:
# sage
A1 = random_matrix(ZZ,2,x=0,y=100)
B1 = random_matrix(ZZ,3,x=-100,y=0)
C1 = random_matrix(ZZ,4,x=-100,y=100)
A1, B1, C1

(
                           [ 45  13  94 -85]
         [ -70  -13  -79]  [-34 -20 -58  67]
[60 93]  [ -52  -53  -87]  [-58  68 -31  28]
[93 75], [ -58  -75 -100], [ 11  25  17  47]
)

In [30]:
A1.det(), B1.det(), C1.det()

(-4149, 22498, -7293820)

In [31]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(2,2)))
B2 = numpy.matrix(numpy.random.randint(-100, 0, size=(3,3)))
C2 = numpy.matrix(numpy.random.randint(-100, 100, size=(4,4)))
print(A2)
print(B2)
print(C2)

[[32 17]
 [39 31]]
[[-11 -99 -25]
 [-84 -42 -26]
 [-51 -40 -48]]
[[ 87   9 -22  82]
 [-27  63  24  67]
 [-66  28  37 -27]
 [-25  94  62 -61]]


In [32]:
round(numpy.linalg.det(A2)), round(numpy.linalg.det(B2)), round(numpy.linalg.det(C2))

(329.0, 226708.0, -8725969.0)

In [55]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3], [-4, -7]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8]])
C3 = sympy.Matrix([[-8, -4, 5, 2], [3, -5, 8, -2], [5, 4, -8, 1], [7, -2, 9, 5]])
sympy.pprint(C3)

⎡-8  -4  5   2 ⎤
⎢              ⎥
⎢3   -5  8   -2⎥
⎢              ⎥
⎢5   4   -8  1 ⎥
⎢              ⎥
⎣7   -2  9   5 ⎦


In [57]:
A3.det(), B3.det(), C3.det()

(9, -604, -1566)

In [66]:
%%r
A4 <- matrix(sample.int(100, size=2*2, replace=T), nrow=2, ncol=2)
B4 <- matrix(sample.int(100, size=3*3, replace=T), nrow=3, ncol=3)
C4 <- matrix(sample.int(100, size=4*4, replace=T), nrow=4, ncol=4)
A4; B4; C4




     [,1] [,2]
[1,]   28   80
[2,]   74    5
     [,1] [,2] [,3]
[1,]   63   78   51
[2,]   22   17    5
[3,]   42   21   68
     [,1] [,2] [,3] [,4]
[1,]   83   16   55   73
[2,]   33   47   94   96
[3,]   75   13   88   18
[4,]   80    3    3   52


In [67]:
%%r
det(A4); det(B4); det(C4)

[1] -5780
[1] -46947
[1] -4006338


## 2. Миноры и алгебраические дополнения
Матрицы знаков для определителей 3-ого и 4-ого порядка 

In [63]:
%%latex
$ SIGN_{(3,3)} = 
 \begin{pmatrix}
+ & - & +  \\
- & + & - \\
+ & - & +  \\
 \end{pmatrix} \ \
SIGN_{(4,4)} = 
 \begin{pmatrix}
+ & - & + & - \\
- & + & - & + \\
+ & - & + & - \\
- & + & - & +
 \end{pmatrix}$

<IPython.core.display.Latex object>

In [42]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i'))
M.minors(2)

[-b*d + a*e,
 -c*d + a*f,
 -c*e + b*f,
 -b*g + a*h,
 -c*g + a*i,
 -c*h + b*i,
 -e*g + d*h,
 -f*g + d*i,
 -f*h + e*i]

In [47]:
M = matrix(SR, 4, var('a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p'))
M.minors(3)

[-(g*j - f*k)*a + (c*j - b*k)*e - (c*f - b*g)*i,
 -(h*j - f*l)*a + (d*j - b*l)*e - (d*f - b*h)*i,
 -(h*k - g*l)*a + (d*k - c*l)*e - (d*g - c*h)*i,
 -(h*k - g*l)*b + (d*k - c*l)*f - (d*g - c*h)*j,
 -(g*n - f*o)*a + (c*n - b*o)*e - (c*f - b*g)*m,
 -(h*n - f*p)*a + (d*n - b*p)*e - (d*f - b*h)*m,
 -(h*o - g*p)*a + (d*o - c*p)*e - (d*g - c*h)*m,
 -(h*o - g*p)*b + (d*o - c*p)*f - (d*g - c*h)*n,
 -(k*n - j*o)*a + (c*n - b*o)*i - (c*j - b*k)*m,
 -(l*n - j*p)*a + (d*n - b*p)*i - (d*j - b*l)*m,
 -(l*o - k*p)*a + (d*o - c*p)*i - (d*k - c*l)*m,
 -(l*o - k*p)*b + (d*o - c*p)*j - (d*k - c*l)*n,
 -(k*n - j*o)*e + (g*n - f*o)*i - (g*j - f*k)*m,
 -(l*n - j*p)*e + (h*n - f*p)*i - (h*j - f*l)*m,
 -(l*o - k*p)*e + (h*o - g*p)*i - (h*k - g*l)*m,
 -(l*o - k*p)*f + (h*o - g*p)*j - (h*k - g*l)*n]

In [37]:
# sage
B1.minors(2)

[3034, 1982, -3056, 4496, 2418, -4625, 826, 154, -1225]

In [53]:
print(C1.minors(2))
print(C1.minors(3))

[-458, 586, 125, 1126, -829, 1368, 3814, 4057, -3670, -6795, 6144, -3, 982, -269, 3050, -2129, 2736, 5863, -3472, -2310, 2934, 4564, -5116, 453, -630, 60, -2335, 1110, -2615, -3865, -2198, -645, -3034, 1931, 2496, -1933]
[-90958, 26758, -59061, 98853, -10050, -33770, 40465, 101215, -111332, 338592, 253036, -423888, 48930, -292810, -153465, 312805]
