<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №0</h1>

### Программные средства

[LaTeX. Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Sage. Basic Algebra and Calculus](http://doc.sagemath.org/html/en/tutorial/tour_algebra.html)

[Sympy. Iterables](https://docs.sympy.org/latest/modules/utilities/iterables.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[R Tutorial](https://www.tutorialspoint.com/r/index.htm)

### Конспекты лекций

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

[Computational Mathematics with SageMath](http://dl.lateralis.org/public/sagebook/sagebook-ba6596d.pdf)

[Семинары по алгебре](https://www.mccme.ru/~yasinsky/teaching/)

[Python Data Science Handbook by Jake VanderPlas](https://www.oreilly.com/library/view/python-data-science/9781491912126/ch04.html)

# Подстановка (таблица перестановки элементов)
## 1. Перестановки, размещения, сочетания

In [77]:
S = Arrangements(["☜","☞","☝︎","☟"],4).list()
for i in range(len(S)):
    print(ascii_art(S[i][0],S[i][1],S[i][2],S[i][3], sep=' || '))

☜ || ☞ || ☝︎ || ☟
☜ || ☞ || ☟ || ☝︎
☜ || ☝︎ || ☞ || ☟
☜ || ☝︎ || ☟ || ☞
☜ || ☟ || ☞ || ☝︎
☜ || ☟ || ☝︎ || ☞
☞ || ☜ || ☝︎ || ☟
☞ || ☜ || ☟ || ☝︎
☞ || ☝︎ || ☜ || ☟
☞ || ☝︎ || ☟ || ☜
☞ || ☟ || ☜ || ☝︎
☞ || ☟ || ☝︎ || ☜
☝︎ || ☜ || ☞ || ☟
☝︎ || ☜ || ☟ || ☞
☝︎ || ☞ || ☜ || ☟
☝︎ || ☞ || ☟ || ☜
☝︎ || ☟ || ☜ || ☞
☝︎ || ☟ || ☞ || ☜
☟ || ☜ || ☞ || ☝︎
☟ || ☜ || ☝︎ || ☞
☟ || ☞ || ☜ || ☝︎
☟ || ☞ || ☝︎ || ☜
☟ || ☝︎ || ☜ || ☞
☟ || ☝︎ || ☞ || ☜


In [73]:
len(S) == factorial(4)

True

In [80]:
S = Arrangements(["🍊","🍋","🍎","🍐","🍑"],3).list()
for i in range(len(S)):
    print(ascii_art(S[i][0],S[i][1],S[i][2], sep=' || '))

🍊 || 🍋 || 🍎
🍊 || 🍋 || 🍐
🍊 || 🍋 || 🍑
🍊 || 🍎 || 🍋
🍊 || 🍎 || 🍐
🍊 || 🍎 || 🍑
🍊 || 🍐 || 🍋
🍊 || 🍐 || 🍎
🍊 || 🍐 || 🍑
🍊 || 🍑 || 🍋
🍊 || 🍑 || 🍎
🍊 || 🍑 || 🍐
🍋 || 🍊 || 🍎
🍋 || 🍊 || 🍐
🍋 || 🍊 || 🍑
🍋 || 🍎 || 🍊
🍋 || 🍎 || 🍐
🍋 || 🍎 || 🍑
🍋 || 🍐 || 🍊
🍋 || 🍐 || 🍎
🍋 || 🍐 || 🍑
🍋 || 🍑 || 🍊
🍋 || 🍑 || 🍎
🍋 || 🍑 || 🍐
🍎 || 🍊 || 🍋
🍎 || 🍊 || 🍐
🍎 || 🍊 || 🍑
🍎 || 🍋 || 🍊
🍎 || 🍋 || 🍐
🍎 || 🍋 || 🍑
🍎 || 🍐 || 🍊
🍎 || 🍐 || 🍋
🍎 || 🍐 || 🍑
🍎 || 🍑 || 🍊
🍎 || 🍑 || 🍋
🍎 || 🍑 || 🍐
🍐 || 🍊 || 🍋
🍐 || 🍊 || 🍎
🍐 || 🍊 || 🍑
🍐 || 🍋 || 🍊
🍐 || 🍋 || 🍎
🍐 || 🍋 || 🍑
🍐 || 🍎 || 🍊
🍐 || 🍎 || 🍋
🍐 || 🍎 || 🍑
🍐 || 🍑 || 🍊
🍐 || 🍑 || 🍋
🍐 || 🍑 || 🍎
🍑 || 🍊 || 🍋
🍑 || 🍊 || 🍎
🍑 || 🍊 || 🍐
🍑 || 🍋 || 🍊
🍑 || 🍋 || 🍎
🍑 || 🍋 || 🍐
🍑 || 🍎 || 🍊
🍑 || 🍎 || 🍋
🍑 || 🍎 || 🍐
🍑 || 🍐 || 🍊
🍑 || 🍐 || 🍋
🍑 || 🍐 || 🍎


In [75]:
len(S) == factorial(5)/factorial(5-3)

True

In [78]:
S = Combinations(["♔","♕","♖","♗","♘","♙"],3).list()
for i in range(len(S)):
    print(ascii_art(S[i][0],S[i][1],S[i][2], sep=' || '))

♔ || ♕ || ♖
♔ || ♕ || ♗
♔ || ♕ || ♘
♔ || ♕ || ♙
♔ || ♖ || ♗
♔ || ♖ || ♘
♔ || ♖ || ♙
♔ || ♗ || ♘
♔ || ♗ || ♙
♔ || ♘ || ♙
♕ || ♖ || ♗
♕ || ♖ || ♘
♕ || ♖ || ♙
♕ || ♗ || ♘
♕ || ♗ || ♙
♕ || ♘ || ♙
♖ || ♗ || ♘
♖ || ♗ || ♙
♖ || ♘ || ♙
♗ || ♘ || ♙


In [79]:
len(S) == factorial(6)/(factorial(6-3)*factorial(3))

True

In [96]:
import sympy
S = sympy.utilities.iterables.multiset_permutations(["☜","☞","☝︎","☟"])
C = 0
for s in S:
    print(ascii_art(s))
    C +=1

[ ☜, ☝︎, ☞, ☟ ]
[ ☜, ☝︎, ☟, ☞ ]
[ ☜, ☞, ☝︎, ☟ ]
[ ☜, ☞, ☟, ☝︎ ]
[ ☜, ☟, ☝︎, ☞ ]
[ ☜, ☟, ☞, ☝︎ ]
[ ☝︎, ☜, ☞, ☟ ]
[ ☝︎, ☜, ☟, ☞ ]
[ ☝︎, ☞, ☜, ☟ ]
[ ☝︎, ☞, ☟, ☜ ]
[ ☝︎, ☟, ☜, ☞ ]
[ ☝︎, ☟, ☞, ☜ ]
[ ☞, ☜, ☝︎, ☟ ]
[ ☞, ☜, ☟, ☝︎ ]
[ ☞, ☝︎, ☜, ☟ ]
[ ☞, ☝︎, ☟, ☜ ]
[ ☞, ☟, ☜, ☝︎ ]
[ ☞, ☟, ☝︎, ☜ ]
[ ☟, ☜, ☝︎, ☞ ]
[ ☟, ☜, ☞, ☝︎ ]
[ ☟, ☝︎, ☜, ☞ ]
[ ☟, ☝︎, ☞, ☜ ]
[ ☟, ☞, ☜, ☝︎ ]
[ ☟, ☞, ☝︎, ☜ ]


In [97]:
C == sympy.factorial(4)

True

In [98]:
S = sympy.utilities.iterables.multiset_permutations(["🍊","🍋","🍎","🍐","🍑"], 3)
C = 0
for s in S:
    print(ascii_art(s))
    C +=1

[ 🍊, 🍋, 🍎 ]
[ 🍊, 🍋, 🍐 ]
[ 🍊, 🍋, 🍑 ]
[ 🍊, 🍎, 🍋 ]
[ 🍊, 🍎, 🍐 ]
[ 🍊, 🍎, 🍑 ]
[ 🍊, 🍐, 🍋 ]
[ 🍊, 🍐, 🍎 ]
[ 🍊, 🍐, 🍑 ]
[ 🍊, 🍑, 🍋 ]
[ 🍊, 🍑, 🍎 ]
[ 🍊, 🍑, 🍐 ]
[ 🍋, 🍊, 🍎 ]
[ 🍋, 🍊, 🍐 ]
[ 🍋, 🍊, 🍑 ]
[ 🍋, 🍎, 🍊 ]
[ 🍋, 🍎, 🍐 ]
[ 🍋, 🍎, 🍑 ]
[ 🍋, 🍐, 🍊 ]
[ 🍋, 🍐, 🍎 ]
[ 🍋, 🍐, 🍑 ]
[ 🍋, 🍑, 🍊 ]
[ 🍋, 🍑, 🍎 ]
[ 🍋, 🍑, 🍐 ]
[ 🍎, 🍊, 🍋 ]
[ 🍎, 🍊, 🍐 ]
[ 🍎, 🍊, 🍑 ]
[ 🍎, 🍋, 🍊 ]
[ 🍎, 🍋, 🍐 ]
[ 🍎, 🍋, 🍑 ]
[ 🍎, 🍐, 🍊 ]
[ 🍎, 🍐, 🍋 ]
[ 🍎, 🍐, 🍑 ]
[ 🍎, 🍑, 🍊 ]
[ 🍎, 🍑, 🍋 ]
[ 🍎, 🍑, 🍐 ]
[ 🍐, 🍊, 🍋 ]
[ 🍐, 🍊, 🍎 ]
[ 🍐, 🍊, 🍑 ]
[ 🍐, 🍋, 🍊 ]
[ 🍐, 🍋, 🍎 ]
[ 🍐, 🍋, 🍑 ]
[ 🍐, 🍎, 🍊 ]
[ 🍐, 🍎, 🍋 ]
[ 🍐, 🍎, 🍑 ]
[ 🍐, 🍑, 🍊 ]
[ 🍐, 🍑, 🍋 ]
[ 🍐, 🍑, 🍎 ]
[ 🍑, 🍊, 🍋 ]
[ 🍑, 🍊, 🍎 ]
[ 🍑, 🍊, 🍐 ]
[ 🍑, 🍋, 🍊 ]
[ 🍑, 🍋, 🍎 ]
[ 🍑, 🍋, 🍐 ]
[ 🍑, 🍎, 🍊 ]
[ 🍑, 🍎, 🍋 ]
[ 🍑, 🍎, 🍐 ]
[ 🍑, 🍐, 🍊 ]
[ 🍑, 🍐, 🍋 ]
[ 🍑, 🍐, 🍎 ]


In [99]:
C == factorial(5)/factorial(5-3)

True

In [106]:
S = sympy.utilities.iterables.multiset_combinations(["♔","♕","♖","♗","♘","♙"], 3)
C = 0
for s in S:
    print(ascii_art(s))
    C +=1

[ ♔, ♕, ♖ ]
[ ♔, ♕, ♗ ]
[ ♔, ♕, ♘ ]
[ ♔, ♕, ♙ ]
[ ♔, ♖, ♗ ]
[ ♔, ♖, ♘ ]
[ ♔, ♖, ♙ ]
[ ♔, ♗, ♘ ]
[ ♔, ♗, ♙ ]
[ ♔, ♘, ♙ ]
[ ♕, ♖, ♗ ]
[ ♕, ♖, ♘ ]
[ ♕, ♖, ♙ ]
[ ♕, ♗, ♘ ]
[ ♕, ♗, ♙ ]
[ ♕, ♘, ♙ ]
[ ♖, ♗, ♘ ]
[ ♖, ♗, ♙ ]
[ ♖, ♘, ♙ ]
[ ♗, ♘, ♙ ]


In [107]:
C == factorial(6)/(factorial(6-3)*factorial(3))

True

## 2. Свойства перестановок
Пример для конечного множества элементов

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_3 a_2 a_4 a_1 a_5 a_7 a_6\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
3 \ 2 \ 4 \ 1 \ 5 \ 7 \ 6 
\end{cases}$

Тождественная перестановка

$ e = 
\begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7
\end{cases}$

$\tau \circ e = e \circ \tau = \tau \\
\tau \circ \tau ^{-1} = \tau ^ {-1} \circ \tau = e \\
\tau_1 \circ (\tau_2 \circ \tau_3) = (\tau_1 \circ \tau_2) \circ \tau_3$

В общем случае

$\tau_1 \circ \tau_2 \neq \tau_2 \circ \tau_1$

Цикл

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_2 a_3 a_4 a_5 a_6 a_7 a_1\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
2 \ 3 \ 4 \ 5 \ 6 \ 7 \ 1 
\end{cases}$

Любая перестановка - произведение циклов.

Транспозиция

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_2 a_1 a_3 a_4 a_5 a_6 a_7\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
2 \ 1 \ 3 \ 4 \ 5 \ 6 \ 7  
\end{cases}$

Любой цикл - произведение транспозиций, любая перестановка - произведение транспозиций.

Инверсии в подстановке

$\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
3 \ 2 \ 4 \ 1 \ 5 \ 7 \ 6 
\end{cases} \\
(2,1), (3,1), (4,1), \\ (3,2), \\ (7,6)$

Четность подстановки - количество инверсий.

In [19]:
Permutation([3,2,4,1,5,7,6]).to_cycles()

[(1, 3, 4), (2,), (5,), (6, 7)]

In [28]:
Permutation([3,2,4,1,5,6,7]) * Permutation([1,2,3,4,5,7,6]) 

[3, 2, 4, 1, 5, 7, 6]

In [24]:
Permutation([3,2,4,1,5,7,6]).fixed_points()

[2, 5]

In [20]:
Permutation([3,2,4,1,5,7,6]).inversions()

[(1, 2), (1, 4), (2, 4), (3, 4), (6, 7)]

In [22]:
Permutation([3,2,4,1,5,7,6]).number_of_inversions()

5

In [23]:
Permutation([3,2,4,1,5,7,6]).is_even()

False

In [27]:
Permutation([3,2,4,1,5,7,6]).to_matrix()

[0 0 0 1 0 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[0 0 0 0 0 1 0]

## 3. В формуле определителя n-ого порядка

$\large{\displaystyle{| \Delta | = \sum_i (-1)^{t(j)} a_{1j_1}a_{2j_2}}...a_{nj_n}}$, где

$\{j_1, j_2, ..., j_n\}$ - все возможные перестановки из чисел $\{1, 2, ..., n\}$;

$t(j)$ - число транспозиций для перехода от $\{1, 2, ..., n\}$ к $\{j_1, j_2, ..., j_n\}$. 

In [1]:
aa = " ".join(list('a_%d%d' %(i,j) for i in (1..2) for j in (1..2)))
A = matrix(SR, 2, var(aa))
A.det() 

-a_12*a_21 + a_11*a_22

In [2]:
aa = " ".join(list('a_%d%d' %(i,j) for i in (1..3) for j in (1..3)))
A = matrix(SR, 3, var(aa))
A.det().expand()   

-a_13*a_22*a_31 + a_12*a_23*a_31 + a_13*a_21*a_32 - a_11*a_23*a_32 - a_12*a_21*a_33 + a_11*a_22*a_33

In [3]:
aa = " ".join(list('a_%d%d' %(i,j) for i in (1..4) for j in (1..4)))
A = matrix(SR, 4, var(aa))
A.det().expand() 

a_14*a_23*a_32*a_41 - a_13*a_24*a_32*a_41 - a_14*a_22*a_33*a_41 + a_12*a_24*a_33*a_41 + a_13*a_22*a_34*a_41 - a_12*a_23*a_34*a_41 - a_14*a_23*a_31*a_42 + a_13*a_24*a_31*a_42 + a_14*a_21*a_33*a_42 - a_11*a_24*a_33*a_42 - a_13*a_21*a_34*a_42 + a_11*a_23*a_34*a_42 + a_14*a_22*a_31*a_43 - a_12*a_24*a_31*a_43 - a_14*a_21*a_32*a_43 + a_11*a_24*a_32*a_43 + a_12*a_21*a_34*a_43 - a_11*a_22*a_34*a_43 - a_13*a_22*a_31*a_44 + a_12*a_23*a_31*a_44 + a_13*a_21*a_32*a_44 - a_11*a_23*a_32*a_44 - a_12*a_21*a_33*a_44 + a_11*a_22*a_33*a_44