<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №2</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы

## 1. Операции над матрицами
### 1.1 Возведение в степень

In [116]:
import sympy
M = sympy.MatrixSymbol('M', 3, 3)
sympy.printing.pprint((M^2).as_explicit())

⎡    2                                                                        
⎢ M₀₀  + M₀₁⋅M₁₀ + M₀₂⋅M₂₀    M₀₀⋅M₀₁ + M₀₁⋅M₁₁ + M₀₂⋅M₂₁  M₀₀⋅M₀₂ + M₀₁⋅M₁₂ +
⎢                                                                             
⎢                                           2                                 
⎢M₀₀⋅M₁₀ + M₁₀⋅M₁₁ + M₁₂⋅M₂₀   M₀₁⋅M₁₀ + M₁₁  + M₁₂⋅M₂₁    M₀₂⋅M₁₀ + M₁₁⋅M₁₂ +
⎢                                                                             
⎢                                                                             
⎣M₀₀⋅M₂₀ + M₁₀⋅M₂₁ + M₂₀⋅M₂₂  M₀₁⋅M₂₀ + M₁₁⋅M₂₁ + M₂₁⋅M₂₂   M₀₂⋅M₂₀ + M₁₂⋅M₂₁ 

        ⎤
 M₀₂⋅M₂₂⎥
        ⎥
        ⎥
 M₁₂⋅M₂₂⎥
        ⎥
     2  ⎥
+ M₂₂   ⎦


In [117]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i')) 
M^2

[a^2 + b*d + c*g a*b + b*e + c*h a*c + b*f + c*i]
[a*d + d*e + f*g b*d + e^2 + f*h c*d + e*f + f*i]
[a*g + d*h + g*i b*g + e*h + h*i c*g + f*h + i^2]

In [64]:
# sage
A1 = random_matrix(ZZ,5,x=0,y=100)
C1 = random_matrix(ZZ,5,x=-100,y=0)
B1 = matrix([[1.1,3.2,5.0,7.6],[2.2,4.1,6.5,8.1]])
A1, B1, C1

(
[59 57 83 29 42]
[55 51 61 66 92]
[65 50 50 12 88]
[84 63 93  0 85]
[56 58 22 85 21],

[1.10000000000000 3.20000000000000 5.00000000000000 7.60000000000000]
[2.20000000000000 4.10000000000000 6.50000000000000 8.10000000000000],

[-33 -53 -63 -49 -36]
[-68 -81 -31 -39 -61]
[-79 -44 -76 -36 -52]
[-16 -79 -60 -72 -40]
[-27 -66 -73 -53 -10]
)

In [4]:
A1^3

[1903139 1407412  430391 2135404 1027929]
[3037405 2319981  677216 2463603 1352851]
[4192550 3342288 1136504 4016230 2271365]
[2542433 1982484  554519 1823154 1020706]
[1550282 1174324  345948 1392686  784439]

In [6]:
A1^3 == A1 * A1 * A1

True

In [14]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(5,5)))
C2 = numpy.matrix(numpy.random.randint(-100, 0, size=(5,5)))
B2 = numpy.matrix([[1,3,5,7],[2,4,6,8]])
print(A2)
print(B2)
print(C2)

[[21  3 92 98 23]
 [ 2 93 65 27 21]
 [43 88 19 49 51]
 [34 31 89 65  5]
 [13 70 94 56 29]]
[[1 3 5 7]
 [2 4 6 8]]
[[-72 -78 -51 -46 -48]
 [-18 -15 -15 -23 -74]
 [-11 -49 -16 -12 -78]
 [-55 -80 -79 -89 -74]
 [-98 -68 -55 -71 -67]]


In [18]:
A2 ** int(3) == A2 * A2 * A2

matrix([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]], dtype=bool)

In [93]:
# python sympy
import sympy
A3 = sympy.Matrix([[-3, -3, -6,-3], [-4, -7, 8,-7], [2, -3, 9, -5], [6, -3, 8, 2]])
B3 = sympy.Matrix([[2, 10, 7], [-5, -6, -2], [-8, 4, -8], [7, 4, -6]])
C3 = sympy.Matrix([[-8, -4, 5, 2], [3, -5, 8, -2], [5, 4, -8, 1], [7, -2, 9, 5]])
sympy.pprint(A3)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎢-4  -7  8   -7⎥
⎢              ⎥
⎢2   -3  9   -5⎥
⎢              ⎥
⎣6   -3  8   2 ⎦


In [21]:
A3^3 == A3 * A3 * A3

True

In [92]:
sympy.pprint(sympy.MatPow(A3, 3).as_explicit())

⎡-45   -282  186   156 ⎤
⎢                      ⎥
⎢-264  -421  292   -354⎥
⎢                      ⎥
⎢-224  102   -215  -108⎥
⎢                      ⎥
⎣-100  138   -360  -83 ⎦


In [113]:
%%r
A4 <- matrix(rexp(25, rate=0.1), nrow=5, ncol=5)
B4 <- matrix(c(1,3,5,7,2,4,6,8), nrow=2, ncol=4)
C4 <- matrix(rexp(25, rate=0.2), nrow=5, ncol=5)
D4 <- matrix(sample.int(100, size=3*4, replace=T), nrow=3, ncol=4)
A4; B4; D4





          [,1]      [,2]      [,3]      [,4]      [,5]
[1,]  5.145262 7.6355023 17.804171  9.190138 17.022647
[2,] 22.127271 6.2519561 11.310773  2.006535 15.860863
[3,]  4.765332 1.9121855 11.133964  7.669811  2.371183
[4,]  1.985914 0.2554269  4.387942  1.655704  4.891216
[5,] 29.849628 1.8712198 17.227341 17.670541  3.348429
     [,1] [,2] [,3] [,4]
[1,]    1    5    2    6
[2,]    3    7    4    8
     [,1] [,2] [,3] [,4]
[1,]   99    3   41   30
[2,]   30   22   80   26
[3,]   55   73   25   53


In [34]:
%%r 
require(matrixcalc)
matrix.power(A4,3)


         [,1]     [,2]      [,3]     [,4]      [,5]
[1,] 55716.69 53363.55  8426.515 37093.58 17453.453
[2,] 39089.35 38291.07  7822.746 27764.37 11128.061
[3,] 18702.66 19173.39  2726.560 13405.02  7423.997
[4,] 24555.27 28934.91  3989.446 18465.41 10486.499
[5,] 92435.68 91806.61 13525.140 63656.86 33121.563


In [36]:
%%r
matrix.power(A4,3) == A4 %*% A4 %*% A4

     [,1] [,2] [,3] [,4] [,5]
[1,] TRUE TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE TRUE
[4,] TRUE TRUE TRUE TRUE TRUE
[5,] TRUE TRUE TRUE TRUE TRUE


### 1.2 Транспонирование

In [122]:
M = matrix(SR, 3, var('a,b,c,d,e,f,g,h,i'))
N = matrix(SR, 3, var('j,k,l,m,n,o,p,q,r'))
html(M.T)

<script type="math/tex">\left(\begin{array}{rrr} a & d & g \\ b & e & h \\ c & f & i \end{array}\right)</script>

In [119]:
M.T.T == M

True

In [124]:
html((M + N).T)

<script type="math/tex">\left(\begin{array}{rrr} a + j & d + m & g + p \\ b + k & e + n & h + q \\ c + l & f + o & i + r \end{array}\right)</script>

In [127]:
(M + N).T == M.T + N.T, (M - N).T == M.T - N.T, (var('k') * M).T == var('k') * M.T

(True, True, True)

In [128]:
html((M * N).T)

<script type="math/tex">\left(\begin{array}{rrr} a j + b m + c p & d j + e m + f p & g j + h m + i p \\ a k + b n + c q & d k + e n + f q & g k + h n + i q \\ a l + b o + c r & d l + e o + f r & g l + h o + i r \end{array}\right)</script>

In [129]:
(M * N).T == N.T * M.T

True

In [38]:
# sage
A1, A1.transpose()

(
[ 4 33  1  7 59]  [ 4 13 12 20 42]
[13 76 83 66 70]  [33 76 24 94 94]
[12 24 76 95  8]  [ 1 83 76 54 77]
[20 94 54 67 79]  [ 7 66 95 67 78]
[42 94 77 78 85], [59 70  8 79 85]
)

In [107]:
# python numpy
print(A2)
print(numpy.transpose(A2))

[[21  3 92 98 23]
 [ 2 93 65 27 21]
 [43 88 19 49 51]
 [34 31 89 65  5]
 [13 70 94 56 29]]
[[21  2 43 34 13]
 [ 3 93 88 31 70]
 [92 65 19 89 94]
 [98 27 49 65 56]
 [23 21 51  5 29]]


In [108]:
# python sympy
sympy.pprint(A3), sympy.pprint(A3.T)

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎢-4  -7  8   -7⎥
⎢              ⎥
⎢2   -3  9   -5⎥
⎢              ⎥
⎣6   -3  8   2 ⎦
⎡-3  -4  2   6 ⎤
⎢              ⎥
⎢-3  -7  -3  -3⎥
⎢              ⎥
⎢-6  8   9   8 ⎥
⎢              ⎥
⎣-3  -7  -5  2 ⎦


(None, None)

In [41]:
%%r
A4; t(A4)

          [,1]      [,2]       [,3]       [,4]        [,5]
[1,]  9.423773 18.555664  0.2288297 12.6718144 13.62604867
[2,] 26.408819  4.740174  3.4295191 11.4775862  0.08964574
[3,]  6.027099 11.172584  1.3450325  8.6214268  0.20625451
[4,] 11.788261 18.301193  0.9501415  0.9755198  0.70827746
[5,] 23.088658 44.437817 12.4730859 31.0452286  9.44632553
           [,1]        [,2]       [,3]       [,4]      [,5]
[1,]  9.4237731 26.40881853  6.0270994 11.7882608 23.088658
[2,] 18.5556635  4.74017434 11.1725836 18.3011928 44.437817
[3,]  0.2288297  3.42951907  1.3450325  0.9501415 12.473086
[4,] 12.6718144 11.47758623  8.6214268  0.9755198 31.045229
[5,] 13.6260487  0.08964574  0.2062545  0.7082775  9.446326


## 2. След матрицы
<table border="1">
        <thead>
            <tr>
                <th>-</th>
                <th>1</th>
                <th>2</th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="font-weight:bold;">1</td>
                <td style="color:#3636ff;">$A_{11}$</td>
                <td>$A_{12}$</td>
                <td>$A_{13}$</td>
                <td>$A_{14}$</td>
                <td>$A_{15}$</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">2</td>
                <td>$A_{21}$</td>
                <td style="color:#3636ff;">$A_{22}$</td>
                <td>$A_{23}$</td>
                <td>$A_{24}$</td>
                <td>$A_{25}$</td>
            </tr>
                        <tr>
                <td style="font-weight:bold;">3</td>
                <td>$A_{31}$</td>
                <td>$A_{32}$</td>
                <td style="color:#3636ff;">$A_{33}$</td>
                <td>$A_{34}$</td>
                <td>$A_{35}$</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">4</td>
                <td>$A_{41}$</td>
                <td>$A_{42}$</td>
                <td>$A_{43}$</td>
                <td style="color:#3636ff;">$A_{44}$</td>
                <td>$A_{45}$</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">5</td>
                <td>$A_{51}$</td>
                <td>$A_{52}$</td>
                <td>$A_{53}$</td>
                <td>$A_{54}$</td>
                <td style="color:#3636ff;">$A_{55}$</td>
            </tr>
        </tbody>
    </table>
    
$TR = A_{11} + A_{22} + A_{33} + A_{44} + A_{55}$ 

In [45]:
# sage
A1, A1.trace(), 4 + 76 + 76 + 67 + 85

(
[ 4 33  1  7 59]          
[13 76 83 66 70]          
[12 24 76 95  8]          
[20 94 54 67 79]          
[42 94 77 78 85], 308, 308
)

In [47]:
# python numpy
A2, numpy.trace(A2), 21 + 93 + 19 + 65 + 29

(matrix([[21,  3, 92, 98, 23],
         [ 2, 93, 65, 27, 21],
         [43, 88, 19, 49, 51],
         [34, 31, 89, 65,  5],
         [13, 70, 94, 56, 29]]), 227, 227)

In [53]:
# python sympy
A3, sympy.trace(A3), -3 -7 + 9 + 2

(Matrix([
 [-3, -3, -6, -3],
 [-4, -7,  8, -7],
 [ 2, -3,  9, -5],
 [ 6, -3,  8,  2]]), 1, 1)

In [56]:
%%r
require(matrixcalc)
A4; matrix.trace(A4); 9.423773 + 4.740174 + 1.3450325 + 0.9755198 + 9.44632553


          [,1]      [,2]       [,3]       [,4]        [,5]
[1,]  9.423773 18.555664  0.2288297 12.6718144 13.62604867
[2,] 26.408819  4.740174  3.4295191 11.4775862  0.08964574
[3,]  6.027099 11.172584  1.3450325  8.6214268  0.20625451
[4,] 11.788261 18.301193  0.9501415  0.9755198  0.70827746
[5,] 23.088658 44.437817 12.4730859 31.0452286  9.44632553
[1] 25.93083
[1] 25.93082


## 3. Норма матрицы

In [137]:
# sage
# the largest column-sum norm
A1.norm(p=1)

328.0

In [158]:
A1.norm(p=1) >= 0, (-2*A1).norm(p=1) == abs(-2)*A1.norm(p=1)

(True, True)

In [161]:
(A1 + C1).norm(p=1) <= A1.norm(p=1) + C1.norm(p=1)

True

In [162]:
(A1 * C1).norm(p=1) <= A1.norm(p=1) * C1.norm(p=1)

True

In [138]:
# the Euclidean norm
A1.norm(p=2)

293.15364020430553

In [139]:
# the largest row-sum norm
A1.norm(p=oo)

325.0

In [141]:
# the Frobenius (sum of squares) norm
A1.norm(p='frob')

311.5333048006264

In [142]:
# python numpy
# the largest column-sum norm
numpy.linalg.norm(A2, 1)

359.0

In [149]:
numpy.linalg.norm(A2, 1) == numpy.max(sum(abs(A2), axis=0))

True

In [166]:
# the smalest column-sum norm
numpy.linalg.norm(A2, -1)

113.0

In [150]:
numpy.linalg.norm(A2, -1) == numpy.min(sum(abs(A2), axis=0))

True

In [151]:
# the Euclidean norm (which is equal to the largest singular value of a matrix)
numpy.linalg.norm(A2, 2)

256.75120834956067

In [157]:
# the smallest singular value
numpy.linalg.norm(A2, -2)

6.5850356145855979

In [164]:
# the largest row-sum norm
numpy.linalg.norm(A2, numpy.inf)

262.0

In [167]:
numpy.linalg.norm(A2, numpy.infty) == numpy.max(sum(abs(A2), axis=1))

True

In [165]:
# the smalest row-sum norm
numpy.linalg.norm(A2, -numpy.inf)

208.0

In [168]:
numpy.linalg.norm(A2, -numpy.infty) == numpy.min(sum(abs(A2), axis=1))

True

In [169]:
# the Frobenius (sum of squares) norm
numpy.linalg.norm(A2, 'fro')

283.23311953230331

In [170]:
# nuclear norm
numpy.linalg.norm(A2, 'nuc')

445.25853270705431

In [176]:
# python sympy
A3.norm(1)

31

In [181]:
A3.norm(oo)

26

In [184]:
A3.norm('fro'), round(A3.norm('fro'), 2)

(sqrt(473), 21.75)

#### In R
Matrix norm (type):

- "O", "o" or "1"
  - maximum absolute column sum;

- "I" or "i"
  - maximum absolute row sum;

- "F" or "f"
  - the Euclidean norm of a matrix treated as if it were a vector;

- "M" or "m"
  - the maximum modulus of all the elements in a matrix; 

- "2"
  - the “spectral” or 2-norm, which is the largest singular value (svd) of a matrix.

In [193]:
%%r
norm(A4, type="O")

[1] 63.87341


In [194]:
%%r
norm(A4, type="I")

[1] 69.96716


In [195]:
%%r
norm(A4, type="F")

[1] 58.88694


In [196]:
%%r
norm(A4, type="M")

[1] 29.84963


In [197]:
%%r
norm(A4, type="2")

[1] 53.71423


## 4. Задание.

Инициировать матрицу $A(3x3)$ и рассчитать $A^2$, $A^T$, 

а также найти след и нормы матрицы с использованием SageMath, Numpy, SymPy, R.