<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №1</h1>

<a href="https://olgabelitskaya.github.io/README.html">&#x1F300; &nbsp; Home Page</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_0.ipynb">📓 &nbsp; Previous</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_2.ipynb">📓 &nbsp; Next</a>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы. Часть 1

## 1. Способы инициализации.

In [69]:
%%html
<p style="color:slategray;">
$\mathscr{A=\begin{bmatrix} 
1 & 2 & 3 \\ 4 & 5 & 6 \\ 
7 & 8 & 9 \\ 10 & 11 & 12         
\end{bmatrix}}$</p>

In [70]:
# sage
A=random_matrix(ZZ,3,x=0,y=100) 
B=random_matrix(ZZ,3,x=-100,y=0)
C=matrix([[1.1,3.2,5.0,7.6],[2.2,4.1,6.5,8.1]]) 
E=matrix.identity(3)
M=matrix(SR,3,var('a,b,c,d,e,f,g,h,i'))
M1=matrix(SR,3,var('a1,b1,c1,d1,e1,f1,g1,h1,i1')) 
M2=matrix(SR,3,var('a2,b2,c2,d2,e2,f2,g2,h2,i2'))

In [71]:
[A.base_ring(),B.base_ring()]

[Integer Ring, Integer Ring]

In [72]:
pretty_print(A,B)
pretty_print(C,E)
print(A.ncols(),A.nrows(),A.dimensions())
print('\n'); print(html(A))
print('\n'); print(latex(C))

[78 38 22]
[37 91 17]
[46  9 39] [-35 -47 -81]
[-44 -82 -61]
[-11 -51 -37]

[1.10000000000000 3.20000000000000 5.00000000000000 7.60000000000000]
[2.20000000000000 4.10000000000000 6.50000000000000 8.10000000000000] [1 0 0]
[0 1 0]
[0 0 1]

(3, 3, (3, 3))


<script type="math/tex">\left(\begin{array}{rrr} 78 & 38 & 22 \\ 37 & 91 & 17 \\ 46 & 9 & 39 \end{array}\right)</script>


\left(\begin{array}{rrrr}
1.10000000000000 & 3.20000000000000 & 5.00000000000000 & 7.60000000000000 \\
2.20000000000000 & 4.10000000000000 & 6.50000000000000 & 8.10000000000000
\end{array}\right)


In [73]:
# python numpy, sympy
import numpy,sympy
A1=numpy.matrix(numpy.random.randint(0,100,size=(5,7)))
B1=numpy.matrix(numpy.random.randint(-100,0,size=(5,7)))
C1=numpy.matrix([[1,3,5,7],[2,4,6,8]])
E1=numpy.matrix(numpy.eye(3))
A2=sympy.Matrix([[-3,-3,-6,-3],[-4,-7,8,-7]])
B2=sympy.Matrix([[2,10,7],[-5,-6,-2],[-8,4,-8],[7,4,-6]])
C2=sympy.Matrix([[-8,-4,5,2],[3,-5,8,-2]])
E2=sympy.Identity(3)

In [74]:
print(A1); print(B1); print(C1); print(E1)
print(A1.shape,B1.shape,C1.shape,E1.shape)
sympy.pprint(A2); sympy.pprint(B2)
sympy.pprint(C2); sympy.pprint(E2.as_explicit())
sympy.pprint([A2.shape,B2.shape,C2.shape,E2.shape])

[[67 52  6 83 36 72 68]
 [89 19 99  2 61 10 57]
 [22 51 83 23 51 78 21]
 [62 98 81 82 67 92 31]
 [27 85 45 92 60 61 44]]
[[ -48  -77  -93  -77  -92  -97   -4]
 [-100  -88  -75  -31  -32  -52  -70]
 [ -39  -40  -75  -57  -25   -1  -24]
 [  -2  -10  -56  -54  -75  -89  -26]
 [ -80  -37  -13  -87  -58  -42  -81]]
[[1 3 5 7]
 [2 4 6 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
((5, 7), (5, 7), (2, 4), (3, 3))
⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡2   10  7 ⎤
⎢          ⎥
⎢-5  -6  -2⎥
⎢          ⎥
⎢-8  4   -8⎥
⎢          ⎥
⎣7   4   -6⎦
⎡-8  -4  5  2 ⎤
⎢             ⎥
⎣3   -5  8  -2⎦
⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦
[(2, 4), (4, 3), (2, 4), (3, 3)]


In [75]:
%%r
A<-matrix(rexp(25,rate=0.1),nrow=5,ncol=5)
B<-matrix(c(1,3,5,7,2,4,6,8),nrow=2,ncol=4)
C<-matrix(rexp(25,rate=0.2),nrow=5,ncol=5)
D<-matrix(sample.int(100,size=3*4,replace=T),nrow=3,ncol=4)
E<-matrix(0,5,5); diag(E)<-1; E

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    1    0    0    0
[3,]    0    0    1    0    0
[4,]    0    0    0    1    0
[5,]    0    0    0    0    1


In [76]:
%%r
cat(paste(c('| A ',dim(A),'| B ',dim(B),'| C ',
          dim(C),'| D ',dim(D),'| E ',
          dim(E),'| '),collapse=' '),'\n\n')
A

| A  5 5 | B  2 4 | C  5 5 | D  3 4 | E  5 5 |  

           [,1]       [,2]      [,3]      [,4]      [,5]
[1,] 21.0905482  6.0162296  6.717809  5.091534 17.684828
[2,]  0.9350975  7.3989648 23.675641 22.528338  4.502710
[3,]  4.1375419 12.8219271 19.834578 10.846607  5.523048
[4,]  4.8985733  0.6273488 12.643241 44.991424 11.835065
[5,]  1.6399288  1.6214455 14.165885 13.936266 10.956298


## 2. Операции над матрицами.
### 2.1 Умножение на число

In [80]:
pretty_print('2*',latex(A),' = ',latex(2*A))
pretty_print('k*'+latex(M)+' = '+latex(var('k')*M))
html(var('t')*M)

'2*' \left(\begin{array}{rrr}
78 & 38 & 22 \\
37 & 91 & 17 \\
46 & 9 & 39
\end{array}\right) ' = ' \left(\begin{array}{rrr}
156 & 76 & 44 \\
74 & 182 & 34 \\
92 & 18 & 78
\end{array}\right)

k* \left(\begin{array}{rrr}
a & b & c \\
d & e & f \\
g & h & i
\end{array}\right) = \left(\begin{array}{rrr}
a k & b k & c k \\
d k & e k & f k \\
g k & h k & i k
\end{array}\right)

<script type="math/tex">\left(\begin{array}{rrr} a t & b t & c t \\ d t & e t & f t \\ g t & h t & i t \end{array}\right)</script>

In [84]:
print(A1); print(-3*A1); print(20*'_=')
sympy.pprint(A2); sympy.pprint(1.5*A2)

[[67 52  6 83 36 72 68]
 [89 19 99  2 61 10 57]
 [22 51 83 23 51 78 21]
 [62 98 81 82 67 92 31]
 [27 85 45 92 60 61 44]]
[[-201 -156  -18 -249 -108 -216 -204]
 [-267  -57 -297   -6 -183  -30 -171]
 [ -66 -153 -249  -69 -153 -234  -63]
 [-186 -294 -243 -246 -201 -276  -93]
 [ -81 -255 -135 -276 -180 -183 -132]]
_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=
⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-4.5  -4.5   -9.0  -4.5 ⎤
⎢                        ⎥
⎣-6.0  -10.5  12.0  -10.5⎦


In [86]:
%%r
5*A

           [,1]      [,2]      [,3]      [,4]     [,5]
[1,] 105.452741 30.081148  33.58905  25.45767 88.42414
[2,]   4.675488 36.994824 118.37820 112.64169 22.51355
[3,]  20.687710 64.109635  99.17289  54.23303 27.61524
[4,]  24.492867  3.136744  63.21620 224.95712 59.17532
[5,]   8.199644  8.107228  70.82943  69.68133 54.78149


### 2.2 Сложение и вычитание матриц

In [87]:
html(M1+M2)

<script type="math/tex">\left(\begin{array}{rrr} a_{1} + a_{2} & b_{1} + b_{2} & c_{1} + c_{2} \\ d_{1} + d_{2} & e_{1} + e_{2} & f_{1} + f_{2} \\ g_{1} + g_{2} & h_{1} + h_{2} & i_{1} + i_{2} \end{array}\right)</script>

In [97]:
pretty_print(M1+M2); print('\n')
pretty_print('M1+M2=M2+M1: %s'%str(M1+M2==M2+M1))
pretty_print(M1-M2)

[a1 + a2 b1 + b2 c1 + c2]
[d1 + d2 e1 + e2 f1 + f2]
[g1 + g2 h1 + h2 i1 + i2]

'M1+M2=M2+M1: True'

[a1 - a2 b1 - b2 c1 - c2]
[d1 - d2 e1 - e2 f1 - f2]
[g1 - g2 h1 - h2 i1 - i2]

In [118]:
print('\nA1-B1\n')
print(A1); print(B1)
print(A1+B1)
sympy.pprint('\n'+15*'<>')
print('\nA2-C2\n')
sympy.pprint(A2)
sympy.pprint(C2)
sympy.pprint(A2-C2)


A1-B1

[[67 52  6 83 36 72 68]
 [89 19 99  2 61 10 57]
 [22 51 83 23 51 78 21]
 [62 98 81 82 67 92 31]
 [27 85 45 92 60 61 44]]
[[ -48  -77  -93  -77  -92  -97   -4]
 [-100  -88  -75  -31  -32  -52  -70]
 [ -39  -40  -75  -57  -25   -1  -24]
 [  -2  -10  -56  -54  -75  -89  -26]
 [ -80  -37  -13  -87  -58  -42  -81]]
[[ 19 -25 -87   6 -56 -25  64]
 [-11 -69  24 -29  29 -42 -13]
 [-17  11   8 -34  26  77  -3]
 [ 60  88  25  28  -8   3   5]
 [-53  48  32   5   2  19 -37]]
                              
<><><><><><><><><><><><><><><>

A2-C2

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-8  -4  5  2 ⎤
⎢             ⎥
⎣3   -5  8  -2⎦
⎡5   1   -11  -5⎤
⎢               ⎥
⎣-7  -2   0   -5⎦


In [121]:
%%r
print(A+C); A-C

          [,1]      [,2]     [,3]      [,4]      [,5]
[1,] 31.846807  7.053531 18.43540  7.966372 23.458350
[2,]  1.691899 15.609980 25.72911 24.119770  4.800403
[3,]  4.866080 13.896846 31.14437 20.707597  7.908694
[4,]  5.921144  1.178828 19.45609 45.503800 12.966823
[5,] 14.227084 16.709809 15.59155 21.806775 13.058209
            [,1]         [,2]      [,3]       [,4]      [,5]
[1,]  10.3342898   4.97892837 -4.999782  2.2166956 11.911306
[2,]   0.1782956  -0.81205007 21.622167 20.9369062  4.205017
[3,]   3.4090038  11.74700844  8.524782  0.9856156  3.137402
[4,]   3.8760024   0.07586927  5.830395 44.4790472 10.703307
[5,] -10.9472263 -13.46691812 12.740223  6.0657577  8.854387


### 2.3 Умножение матриц

In [122]:
# sage
M1,M2

(
[a1 b1 c1]  [a2 b2 c2]
[d1 e1 f1]  [d2 e2 f2]
[g1 h1 i1], [g2 h2 i2]
)

In [130]:
pretty_print(M1*M2)
pretty_print('M1*M2=M2*M1: %s'%str(M1*M2==M2*M1))
pretty_print(M2*M1)

[a1*a2 + b1*d2 + c1*g2 a1*b2 + b1*e2 + c1*h2 a1*c2 + b1*f2 + c1*i2]
[a2*d1 + d2*e1 + f1*g2 b2*d1 + e1*e2 + f1*h2 c2*d1 + e1*f2 + f1*i2]
[a2*g1 + d2*h1 + g2*i1 b2*g1 + e2*h1 + h2*i1 c2*g1 + f2*h1 + i1*i2]

'M1*M2=M2*M1: False'

[a1*a2 + b2*d1 + c2*g1 a2*b1 + b2*e1 + c2*h1 a2*c1 + b2*f1 + c2*i1]
[a1*d2 + d1*e2 + f2*g1 b1*d2 + e1*e2 + f2*h1 c1*d2 + e2*f1 + f2*i1]
[a1*g2 + d1*h2 + g1*i2 b1*g2 + e1*h2 + h1*i2 c1*g2 + f1*h2 + i1*i2]

In [140]:
# numpy, sympy
print(A1*B1.T); print(B1.T*A1)
print(numpy.dot(A1,B1.T)==A1*B1.T)
print('\n'+25*'<>'+'\n')
sympy.pprint(A2*C2.T)
A2*C2.T==C2.T*A2

[[-24737 -23955 -12478 -16348 -25203]
 [-21906 -24521 -14673 -12967 -17859]
 [-26815 -20784 -12291 -17757 -14662]
 [-39581 -32539 -19598 -24087 -27034]
 [-30723 -24579 -15689 -19465 -23500]]
[[-15258 -13381 -17187 -12605 -14751 -12562 -13365]
 [-15490 -11841 -14969 -11711 -13070 -12721 -13030]
 [-18379 -16679 -19329 -15382 -16280 -19241 -14482]
 [-14869 -20187 -16551 -20196 -16408 -20575 -13702]
 [-15778 -18947 -14480 -19761 -15044 -19332 -13482]
 [-17801 -18375 -14912 -19340 -15198 -18332 -14188]
 [-10825 -12195 -14697 -10608 -12240 -10193  -9136]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

<><><><><><><><><><><><><><><><><><><><><><><><><>

⎡0   -36⎤
⎢       ⎥
⎣86  101⎦


False

In [132]:
# python numpy 
# !!! умножение матриц отличается от умножения массивов !!!
a=numpy.random.random((3,3))
b=numpy.random.random((3,3))
a*b # elementwise product

array([[0.16096099, 0.57413651, 0.36124134],
       [0.03316927, 0.29869373, 0.03416351],
       [0.06421956, 0.15043653, 0.28818231]])

In [133]:
a*b==b*a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [134]:
a.dot(b) # matrix product

array([[0.22534055, 0.60665587, 0.50509927],
       [0.49880474, 0.92840029, 0.846394  ],
       [0.6556339 , 1.23259488, 1.12380801]])

In [135]:
a.dot(b)==b.dot(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [142]:
sympy.pprint(A2), sympy.pprint(C2.T), sympy.pprint(A2*C2.T);

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-8  3 ⎤
⎢      ⎥
⎢-4  -5⎥
⎢      ⎥
⎢5   8 ⎥
⎢      ⎥
⎣2   -2⎦
⎡0   -36⎤
⎢       ⎥
⎣86  101⎦


In [149]:
sympy.pprint(A2), sympy.pprint(C2.T), sympy.pprint(C2.T*A2);

⎡-3  -3  -6  -3⎤
⎢              ⎥
⎣-4  -7  8   -7⎦
⎡-8  3 ⎤
⎢      ⎥
⎢-4  -5⎥
⎢      ⎥
⎢5   8 ⎥
⎢      ⎥
⎣2   -2⎦
⎡12    3   72    3 ⎤
⎢                  ⎥
⎢32   47   -16  47 ⎥
⎢                  ⎥
⎢-47  -71  34   -71⎥
⎢                  ⎥
⎣ 2    8   -28   8 ⎦


#### in R
- $A * B$ - element-wise multiplication

- $A \%*\% B$	- matrix multiplication

- $A \% o \% B$	- outer product AB'

In [146]:
%%r
A%*%C

         [,1]     [,2]     [,3]     [,4]      [,5]
[1,] 464.1108 348.1407 395.3621 278.2480 182.51837
[2,] 112.6194 167.5348 453.8188 294.9101  99.04406
[3,] 149.2693 220.2089 380.9068 276.9153  98.90817
[4,] 257.3529 227.2065 525.0726 255.9564 134.42674
[5,] 181.3464 203.2402 293.3245 240.3569  82.54730


In [147]:
%%r
C%*%A

          [,1]      [,2]     [,3]     [,4]      [,5]
[1,] 299.85816 233.79415 447.3651 415.0350 356.89039
[2,]  40.41974  93.11667 264.5528 286.8565  83.79348
[3,] 115.38226 167.40420 413.1383 627.5054 223.03199
[4,]  54.63662  99.74273 177.5664 130.3517  76.65870
[5,] 327.47908 213.99091 599.3464 802.8655 414.59134


In [148]:
%%r
A%*%C==C%*%A

      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE
[4,] FALSE FALSE FALSE FALSE FALSE
[5,] FALSE FALSE FALSE FALSE FALSE


In [150]:
%%r
matrix(c(A%*%C==C%*%A,
         A%*%C==A*C,C%*%A==A*C,
         A%*%C),nrow=5)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[2,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[3,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[4,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
[5,]    0    0    0    0    0    0    0    0    0     0     0     0     0     0
     [,15]    [,16]    [,17]    [,18]    [,19]     [,20]
[1,]     0 464.1108 348.1407 395.3621 278.2480 182.51837
[2,]     0 112.6194 167.5348 453.8188 294.9101  99.04406
[3,]     0 149.2693 220.2089 380.9068 276.9153  98.90817
[4,]     0 257.3529 227.2065 525.0726 255.9564 134.42674
[5,]     0 181.3464 203.2402 293.3245 240.3569  82.54730


## 3. Задание.

Инициировать матрицы $A(2x4)$ и $B(4x2)$ и рассчитать их сумму ($A+B$) и произведения ($A*B, \ B*A$)

с использованием SageMath, Numpy, SymPy, R.