<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №0</h1>

<a href="https://olgabelitskaya.github.io/README.html">&#x1F300; &nbsp; Home Page</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_1.ipynb">📓 &nbsp; Next</a>

### Программные средства

[LaTeX. Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Sage. Basic Algebra and Calculus](http://doc.sagemath.org/html/en/tutorial/tour_algebra.html)

[Sympy. Iterables](https://docs.sympy.org/latest/modules/utilities/iterables.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[R Tutorial](https://www.tutorialspoint.com/r/index.htm)

### Конспекты лекций

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

[Computational Mathematics with SageMath](http://dl.lateralis.org/public/sagebook/sagebook-ba6596d.pdf)

[Семинары по алгебре](https://www.mccme.ru/~yasinsky/teaching/)

[Python Data Science Handbook by Jake VanderPlas](https://www.oreilly.com/library/view/python-data-science/9781491912126/ch04.html)

# Подстановка (таблица перестановки элементов)
## 1. Перестановки, размещения, сочетания

In [1]:
# sage
S=["☜","☞","☝︎","☟"]
S=Arrangements(S,4).list()
for i in range(len(S)):
    print(ascii_art(S[i][0],S[i][1],
                    S[i][2],S[i][3],
                    sep=' || '))
len(S)==factorial(4)

☜ || ☞ || ☝︎ || ☟
☜ || ☞ || ☟ || ☝︎
☜ || ☝︎ || ☞ || ☟
☜ || ☝︎ || ☟ || ☞
☜ || ☟ || ☞ || ☝︎
☜ || ☟ || ☝︎ || ☞
☞ || ☜ || ☝︎ || ☟
☞ || ☜ || ☟ || ☝︎
☞ || ☝︎ || ☜ || ☟
☞ || ☝︎ || ☟ || ☜
☞ || ☟ || ☜ || ☝︎
☞ || ☟ || ☝︎ || ☜
☝︎ || ☜ || ☞ || ☟
☝︎ || ☜ || ☟ || ☞
☝︎ || ☞ || ☜ || ☟
☝︎ || ☞ || ☟ || ☜
☝︎ || ☟ || ☜ || ☞
☝︎ || ☟ || ☞ || ☜
☟ || ☜ || ☞ || ☝︎
☟ || ☜ || ☝︎ || ☞
☟ || ☞ || ☜ || ☝︎
☟ || ☞ || ☝︎ || ☜
☟ || ☝︎ || ☜ || ☞
☟ || ☝︎ || ☞ || ☜


True

In [2]:
S=["🍊","🍋","🍎","🍐","🍑"]
S=Arrangements(S,3).list() 
for i in range(len(S)):
    print(ascii_art(S[i][0],S[i][1],
                    S[i][2],
                    sep=' |*| '))
len(S)==factorial(5)/factorial(5-3)

🍊 |*| 🍋 |*| 🍎
🍊 |*| 🍋 |*| 🍐
🍊 |*| 🍋 |*| 🍑
🍊 |*| 🍎 |*| 🍋
🍊 |*| 🍎 |*| 🍐
🍊 |*| 🍎 |*| 🍑
🍊 |*| 🍐 |*| 🍋
🍊 |*| 🍐 |*| 🍎
🍊 |*| 🍐 |*| 🍑
🍊 |*| 🍑 |*| 🍋
🍊 |*| 🍑 |*| 🍎
🍊 |*| 🍑 |*| 🍐
🍋 |*| 🍊 |*| 🍎
🍋 |*| 🍊 |*| 🍐
🍋 |*| 🍊 |*| 🍑
🍋 |*| 🍎 |*| 🍊
🍋 |*| 🍎 |*| 🍐
🍋 |*| 🍎 |*| 🍑
🍋 |*| 🍐 |*| 🍊
🍋 |*| 🍐 |*| 🍎
🍋 |*| 🍐 |*| 🍑
🍋 |*| 🍑 |*| 🍊
🍋 |*| 🍑 |*| 🍎
🍋 |*| 🍑 |*| 🍐
🍎 |*| 🍊 |*| 🍋
🍎 |*| 🍊 |*| 🍐
🍎 |*| 🍊 |*| 🍑
🍎 |*| 🍋 |*| 🍊
🍎 |*| 🍋 |*| 🍐
🍎 |*| 🍋 |*| 🍑
🍎 |*| 🍐 |*| 🍊
🍎 |*| 🍐 |*| 🍋
🍎 |*| 🍐 |*| 🍑
🍎 |*| 🍑 |*| 🍊
🍎 |*| 🍑 |*| 🍋
🍎 |*| 🍑 |*| 🍐
🍐 |*| 🍊 |*| 🍋
🍐 |*| 🍊 |*| 🍎
🍐 |*| 🍊 |*| 🍑
🍐 |*| 🍋 |*| 🍊
🍐 |*| 🍋 |*| 🍎
🍐 |*| 🍋 |*| 🍑
🍐 |*| 🍎 |*| 🍊
🍐 |*| 🍎 |*| 🍋
🍐 |*| 🍎 |*| 🍑
🍐 |*| 🍑 |*| 🍊
🍐 |*| 🍑 |*| 🍋
🍐 |*| 🍑 |*| 🍎
🍑 |*| 🍊 |*| 🍋
🍑 |*| 🍊 |*| 🍎
🍑 |*| 🍊 |*| 🍐
🍑 |*| 🍋 |*| 🍊
🍑 |*| 🍋 |*| 🍎
🍑 |*| 🍋 |*| 🍐
🍑 |*| 🍎 |*| 🍊
🍑 |*| 🍎 |*| 🍋
🍑 |*| 🍎 |*| 🍐
🍑 |*| 🍐 |*| 🍊
🍑 |*| 🍐 |*| 🍋
🍑 |*| 🍐 |*| 🍎


True

In [3]:
S=["♔","♕","♖","♗","♘","♙"]
S=Combinations(S,3).list()
for i in range(len(S)):
    print(ascii_art(S[i][0],S[i][1],
                    S[i][2], sep=' || '))
len(S)==factorial(6)/(factorial(6-3)*factorial(3))

♔ || ♕ || ♖
♔ || ♕ || ♗
♔ || ♕ || ♘
♔ || ♕ || ♙
♔ || ♖ || ♗
♔ || ♖ || ♘
♔ || ♖ || ♙
♔ || ♗ || ♘
♔ || ♗ || ♙
♔ || ♘ || ♙
♕ || ♖ || ♗
♕ || ♖ || ♘
♕ || ♖ || ♙
♕ || ♗ || ♘
♕ || ♗ || ♙
♕ || ♘ || ♙
♖ || ♗ || ♘
♖ || ♗ || ♙
♖ || ♘ || ♙
♗ || ♘ || ♙


True

In [4]:
# python sympy module
import sympy
sympy.init_printing(use_unicode=True)
C=0; S=["☜","☞","☝︎","☟"]
S=sympy.utilities.iterables.multiset_permutations(S)
for s in S: print(ascii_art(s)); C +=1
C==sympy.factorial(4)

[ ☜, ☝︎, ☞, ☟ ]
[ ☜, ☝︎, ☟, ☞ ]
[ ☜, ☞, ☝︎, ☟ ]
[ ☜, ☞, ☟, ☝︎ ]
[ ☜, ☟, ☝︎, ☞ ]
[ ☜, ☟, ☞, ☝︎ ]
[ ☝︎, ☜, ☞, ☟ ]
[ ☝︎, ☜, ☟, ☞ ]
[ ☝︎, ☞, ☜, ☟ ]
[ ☝︎, ☞, ☟, ☜ ]
[ ☝︎, ☟, ☜, ☞ ]
[ ☝︎, ☟, ☞, ☜ ]
[ ☞, ☜, ☝︎, ☟ ]
[ ☞, ☜, ☟, ☝︎ ]
[ ☞, ☝︎, ☜, ☟ ]
[ ☞, ☝︎, ☟, ☜ ]
[ ☞, ☟, ☜, ☝︎ ]
[ ☞, ☟, ☝︎, ☜ ]
[ ☟, ☜, ☝︎, ☞ ]
[ ☟, ☜, ☞, ☝︎ ]
[ ☟, ☝︎, ☜, ☞ ]
[ ☟, ☝︎, ☞, ☜ ]
[ ☟, ☞, ☜, ☝︎ ]
[ ☟, ☞, ☝︎, ☜ ]


True

In [5]:
C=0; S=["🍊","🍋","🍎","🍐","🍑"]
S=sympy.utilities.iterables.multiset_permutations(S,3)
for s in S: print(ascii_art(s)); C +=1
C==sympy.factorial(5)/sympy.factorial(5-3)

[ 🍊, 🍋, 🍎 ]
[ 🍊, 🍋, 🍐 ]
[ 🍊, 🍋, 🍑 ]
[ 🍊, 🍎, 🍋 ]
[ 🍊, 🍎, 🍐 ]
[ 🍊, 🍎, 🍑 ]
[ 🍊, 🍐, 🍋 ]
[ 🍊, 🍐, 🍎 ]
[ 🍊, 🍐, 🍑 ]
[ 🍊, 🍑, 🍋 ]
[ 🍊, 🍑, 🍎 ]
[ 🍊, 🍑, 🍐 ]
[ 🍋, 🍊, 🍎 ]
[ 🍋, 🍊, 🍐 ]
[ 🍋, 🍊, 🍑 ]
[ 🍋, 🍎, 🍊 ]
[ 🍋, 🍎, 🍐 ]
[ 🍋, 🍎, 🍑 ]
[ 🍋, 🍐, 🍊 ]
[ 🍋, 🍐, 🍎 ]
[ 🍋, 🍐, 🍑 ]
[ 🍋, 🍑, 🍊 ]
[ 🍋, 🍑, 🍎 ]
[ 🍋, 🍑, 🍐 ]
[ 🍎, 🍊, 🍋 ]
[ 🍎, 🍊, 🍐 ]
[ 🍎, 🍊, 🍑 ]
[ 🍎, 🍋, 🍊 ]
[ 🍎, 🍋, 🍐 ]
[ 🍎, 🍋, 🍑 ]
[ 🍎, 🍐, 🍊 ]
[ 🍎, 🍐, 🍋 ]
[ 🍎, 🍐, 🍑 ]
[ 🍎, 🍑, 🍊 ]
[ 🍎, 🍑, 🍋 ]
[ 🍎, 🍑, 🍐 ]
[ 🍐, 🍊, 🍋 ]
[ 🍐, 🍊, 🍎 ]
[ 🍐, 🍊, 🍑 ]
[ 🍐, 🍋, 🍊 ]
[ 🍐, 🍋, 🍎 ]
[ 🍐, 🍋, 🍑 ]
[ 🍐, 🍎, 🍊 ]
[ 🍐, 🍎, 🍋 ]
[ 🍐, 🍎, 🍑 ]
[ 🍐, 🍑, 🍊 ]
[ 🍐, 🍑, 🍋 ]
[ 🍐, 🍑, 🍎 ]
[ 🍑, 🍊, 🍋 ]
[ 🍑, 🍊, 🍎 ]
[ 🍑, 🍊, 🍐 ]
[ 🍑, 🍋, 🍊 ]
[ 🍑, 🍋, 🍎 ]
[ 🍑, 🍋, 🍐 ]
[ 🍑, 🍎, 🍊 ]
[ 🍑, 🍎, 🍋 ]
[ 🍑, 🍎, 🍐 ]
[ 🍑, 🍐, 🍊 ]
[ 🍑, 🍐, 🍋 ]
[ 🍑, 🍐, 🍎 ]


True

In [6]:
C=0; S=["♔","♕","♖","♗","♘","♙"]
S=sympy.utilities.iterables.multiset_combinations(S,3)
for s in S: print(ascii_art(s)); C +=1
C==sympy.factorial(6)/(sympy.factorial(6-3)*sympy.factorial(3))

[ ♔, ♕, ♖ ]
[ ♔, ♕, ♗ ]
[ ♔, ♕, ♘ ]
[ ♔, ♕, ♙ ]
[ ♔, ♖, ♗ ]
[ ♔, ♖, ♘ ]
[ ♔, ♖, ♙ ]
[ ♔, ♗, ♘ ]
[ ♔, ♗, ♙ ]
[ ♔, ♘, ♙ ]
[ ♕, ♖, ♗ ]
[ ♕, ♖, ♘ ]
[ ♕, ♖, ♙ ]
[ ♕, ♗, ♘ ]
[ ♕, ♗, ♙ ]
[ ♕, ♘, ♙ ]
[ ♖, ♗, ♘ ]
[ ♖, ♗, ♙ ]
[ ♖, ♘, ♙ ]
[ ♗, ♘, ♙ ]


True

In [7]:
# python itertools, numpy modules
import itertools,numpy
C=0; S=["☜","☞","☝︎","☟"]
S=itertools.permutations(S,4)
for s in S: print(ascii_art(s)); C+=1
C==numpy.math.factorial(4)  

( ☜, ☞, ☝︎, ☟ )
( ☜, ☞, ☟, ☝︎ )
( ☜, ☝︎, ☞, ☟ )
( ☜, ☝︎, ☟, ☞ )
( ☜, ☟, ☞, ☝︎ )
( ☜, ☟, ☝︎, ☞ )
( ☞, ☜, ☝︎, ☟ )
( ☞, ☜, ☟, ☝︎ )
( ☞, ☝︎, ☜, ☟ )
( ☞, ☝︎, ☟, ☜ )
( ☞, ☟, ☜, ☝︎ )
( ☞, ☟, ☝︎, ☜ )
( ☝︎, ☜, ☞, ☟ )
( ☝︎, ☜, ☟, ☞ )
( ☝︎, ☞, ☜, ☟ )
( ☝︎, ☞, ☟, ☜ )
( ☝︎, ☟, ☜, ☞ )
( ☝︎, ☟, ☞, ☜ )
( ☟, ☜, ☞, ☝︎ )
( ☟, ☜, ☝︎, ☞ )
( ☟, ☞, ☜, ☝︎ )
( ☟, ☞, ☝︎, ☜ )
( ☟, ☝︎, ☜, ☞ )
( ☟, ☝︎, ☞, ☜ )


True

In [8]:
C=0; S=["🍊","🍋","🍎","🍐","🍑"]
S=itertools.permutations(S,3)
for s in S: print(ascii_art(s)); C+=1
C==numpy.math.factorial(5)/numpy.math.factorial(5-3)

( 🍊, 🍋, 🍎 )
( 🍊, 🍋, 🍐 )
( 🍊, 🍋, 🍑 )
( 🍊, 🍎, 🍋 )
( 🍊, 🍎, 🍐 )
( 🍊, 🍎, 🍑 )
( 🍊, 🍐, 🍋 )
( 🍊, 🍐, 🍎 )
( 🍊, 🍐, 🍑 )
( 🍊, 🍑, 🍋 )
( 🍊, 🍑, 🍎 )
( 🍊, 🍑, 🍐 )
( 🍋, 🍊, 🍎 )
( 🍋, 🍊, 🍐 )
( 🍋, 🍊, 🍑 )
( 🍋, 🍎, 🍊 )
( 🍋, 🍎, 🍐 )
( 🍋, 🍎, 🍑 )
( 🍋, 🍐, 🍊 )
( 🍋, 🍐, 🍎 )
( 🍋, 🍐, 🍑 )
( 🍋, 🍑, 🍊 )
( 🍋, 🍑, 🍎 )
( 🍋, 🍑, 🍐 )
( 🍎, 🍊, 🍋 )
( 🍎, 🍊, 🍐 )
( 🍎, 🍊, 🍑 )
( 🍎, 🍋, 🍊 )
( 🍎, 🍋, 🍐 )
( 🍎, 🍋, 🍑 )
( 🍎, 🍐, 🍊 )
( 🍎, 🍐, 🍋 )
( 🍎, 🍐, 🍑 )
( 🍎, 🍑, 🍊 )
( 🍎, 🍑, 🍋 )
( 🍎, 🍑, 🍐 )
( 🍐, 🍊, 🍋 )
( 🍐, 🍊, 🍎 )
( 🍐, 🍊, 🍑 )
( 🍐, 🍋, 🍊 )
( 🍐, 🍋, 🍎 )
( 🍐, 🍋, 🍑 )
( 🍐, 🍎, 🍊 )
( 🍐, 🍎, 🍋 )
( 🍐, 🍎, 🍑 )
( 🍐, 🍑, 🍊 )
( 🍐, 🍑, 🍋 )
( 🍐, 🍑, 🍎 )
( 🍑, 🍊, 🍋 )
( 🍑, 🍊, 🍎 )
( 🍑, 🍊, 🍐 )
( 🍑, 🍋, 🍊 )
( 🍑, 🍋, 🍎 )
( 🍑, 🍋, 🍐 )
( 🍑, 🍎, 🍊 )
( 🍑, 🍎, 🍋 )
( 🍑, 🍎, 🍐 )
( 🍑, 🍐, 🍊 )
( 🍑, 🍐, 🍋 )
( 🍑, 🍐, 🍎 )


True

In [9]:
C=0; S=["♔","♕","♖","♗","♘","♙"]
S=itertools.combinations(S,3)
for s in S: print(ascii_art(s)); C+=1
C==numpy.math.factorial(6)/\
   (numpy.math.factorial(6-3)*numpy.math.factorial(3))

( ♔, ♕, ♖ )
( ♔, ♕, ♗ )
( ♔, ♕, ♘ )
( ♔, ♕, ♙ )
( ♔, ♖, ♗ )
( ♔, ♖, ♘ )
( ♔, ♖, ♙ )
( ♔, ♗, ♘ )
( ♔, ♗, ♙ )
( ♔, ♘, ♙ )
( ♕, ♖, ♗ )
( ♕, ♖, ♘ )
( ♕, ♖, ♙ )
( ♕, ♗, ♘ )
( ♕, ♗, ♙ )
( ♕, ♘, ♙ )
( ♖, ♗, ♘ )
( ♖, ♗, ♙ )
( ♖, ♘, ♙ )
( ♗, ♘, ♙ )


True

In [10]:
%%r
elements<-c("☜","☞","☝︎","☟")
n<-length(elements)
S<-unique(t(sapply(1:10^3,
                   function(x) sample(elements,n)))) 
S<-apply(S,1,function(x) paste0(x,collapse=""))
print(length(S)==factorial(4)); S

[1] TRUE
 [1] "☜☝︎☟☞" "☝︎☜☟☞" "☜☞☟☝︎" "☞☝︎☟☜" "☟☝︎☞☜" "☞☟☝︎☜" "☟☞☜☝︎" "☜☝︎☞☟" "☝︎☞☟☜" "☞☝︎☜☟"
[11] "☝︎☞☜☟" "☟☝︎☜☞" "☟☜☝︎☞" "☝︎☟☜☞" "☜☞☝︎☟" "☝︎☟☞☜" "☟☜☞☝︎" "☜☟☞☝︎" "☞☟☜☝︎" "☟☞☝︎☜"
[21] "☜☟☝︎☞" "☞☜☟☝︎" "☞☜☝︎☟" "☝︎☜☞☟"


In [11]:
%%r
elements<-c("🍊","🍋","🍎","🍐","🍑"); 
S<-unique(t(sapply(1:10^3,
           function(x) sample(elements,3)))) 
S<-apply(S,1,function(x) paste0(x,collapse=""))
for (i in c(1:6)){
    cat(paste(S[(10*i-9):(10*i)],collapse=" "),"\n")}
length(S)==factorial(5)/factorial(5-3)

🍐🍋🍑 🍋🍐🍊 🍐🍊🍋 🍐🍑🍎 🍊🍎🍐 🍐🍋🍊 🍋🍎🍐 🍑🍐🍊 🍋🍐🍎 🍊🍋🍎 
🍎🍐🍊 🍋🍑🍐 🍎🍑🍋 🍎🍊🍑 🍊🍋🍐 🍑🍋🍎 🍐🍑🍊 🍎🍋🍊 🍊🍐🍑 🍊🍎🍋 
🍎🍋🍐 🍐🍊🍎 🍊🍐🍎 🍊🍐🍋 🍑🍎🍋 🍎🍐🍑 🍑🍊🍐 🍋🍊🍐 🍑🍐🍋 🍊🍑🍎 
🍎🍑🍐 🍋🍑🍊 🍊🍋🍑 🍑🍐🍎 🍋🍊🍑 🍊🍎🍑 🍊🍑🍐 🍐🍎🍊 🍋🍊🍎 🍎🍊🍋 
🍑🍎🍊 🍑🍊🍎 🍋🍎🍊 🍎🍑🍊 🍋🍐🍑 🍐🍎🍑 🍎🍊🍐 🍑🍊🍋 🍐🍎🍋 🍋🍎🍑 
🍐🍋🍎 🍑🍎🍐 🍎🍋🍑 🍊🍑🍋 🍐🍊🍑 🍑🍋🍐 🍑🍋🍊 🍐🍑🍋 🍎🍐🍋 🍋🍑🍎 
[1] TRUE


In [12]:
%%r
elements<-c("♔","♕","♖","♗","♘","♙")
S<-t(combn(elements,3)) 
S<-apply(S,1,function(x) paste0(x,collapse=""))
for (i in c(1,2,3)){
    cat(paste(S[(7*i-6):(7*i)],collapse=" "),"\n")}
c(length(S)==factorial(6)/(factorial(6-3)*factorial(3)),
  length(S)==choose(6,3))

♔♕♖ ♔♕♗ ♔♕♘ ♔♕♙ ♔♖♗ ♔♖♘ ♔♖♙ 
♔♗♘ ♔♗♙ ♔♘♙ ♕♖♗ ♕♖♘ ♕♖♙ ♕♗♘ 
♕♗♙ ♕♘♙ ♖♗♘ ♖♗♙ ♖♘♙ ♗♘♙ NA 
[1] TRUE TRUE


## 2. Свойства перестановок
Пример для конечного множества элементов

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_3 a_2 a_4 a_1 a_5 a_7 a_6\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
3 \ 2 \ 4 \ 1 \ 5 \ 7 \ 6 
\end{cases}$

Тождественная перестановка

$ e = 
\begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7
\end{cases}$

$\tau \circ e = e \circ \tau = \tau \\
\tau \circ \tau ^{-1} = \tau ^ {-1} \circ \tau = e \\
\tau_1 \circ (\tau_2 \circ \tau_3) = (\tau_1 \circ \tau_2) \circ \tau_3$

В общем случае

$\tau_1 \circ \tau_2 \neq \tau_2 \circ \tau_1$

Цикл

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_2 a_3 a_4 a_5 a_6 a_7 a_1\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
2 \ 3 \ 4 \ 5 \ 6 \ 7 \ 1 
\end{cases}$

Любая перестановка - произведение циклов.

Транспозиция

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_2 a_1 a_3 a_4 a_5 a_6 a_7\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
2 \ 1 \ 3 \ 4 \ 5 \ 6 \ 7  
\end{cases}$

Любой цикл - произведение транспозиций. $\implies$ Любая перестановка - произведение транспозиций.

Инверсии в подстановке

$\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
3 \ 2 \ 4 \ 1 \ 5 \ 7 \ 6 
\end{cases} \\
(2,1), (3,1), (4,1), \\ (3,2), \\ (7,6)$

Четность подстановки определяется числом инверсий.

In [13]:
# sage
X=[3,2,4,1,5,7,6]; P=Permutation(X)
X1,X2=[3,2,4,1,5,6,7],[1,2,3,4,5,7,6]
ST=['Cycles in P: ',P.to_cycles(),
    'Product of P cycles: ',
    Permutation(X1)*Permutation(X2),
    'Inversions in P: ',P.inversions(),
    'Even? ',[P.number_of_inversions(),
              P.is_even()],
    'P matrix: ',P.to_matrix()]
for st in ST: print(st)

Cycles in P: 
[(1, 3, 4), (2,), (5,), (6, 7)]
Product of P cycles: 
[3, 2, 4, 1, 5, 7, 6]
Inversions in P: 
[(1, 2), (1, 4), (2, 4), (3, 4), (6, 7)]
Even? 
[5, False]
P matrix: 
[0 0 0 1 0 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[0 0 0 0 0 1 0]


In [21]:
# sympy
from sympy.combinatorics import permutations
X=[3,2,4,1,5,7,6]
X1,X2=[2,1,3,0,4,5,6],[0,1,2,3,4,6,5]
P=permutations.Permutation([x-1 for x in X])
ST=['Permutation indices: ',
    [P.list(),P.array_form],P.atoms(),
    P.size,[P.ascents(),P.descents()],
    'Cycles in P: ',
    P.cyclic_form,P.full_cyclic_form,
    'Product of cycles == P',
    permutations.Permutation(X1)*\
    permutations.Permutation(X2)==P,
    'Transpositions in P: ',
    P.transpositions(),
    'Inversions in P: ',
    [P.inversion_vector(), P.inversions()],
    'Adjacency matrix: ']
for st in ST: print(st)
sympy.pprint(P.get_adjacency_matrix())

Permutation indices: 
[[2, 1, 3, 0, 4, 6, 5], [2, 1, 3, 0, 4, 6, 5]]
set([0, 1, 2, 3, 4, 5, 6])
7
[[1, 3, 4], [0, 2, 5]]
Cycles in P: 
[[0, 2, 3], [5, 6]]
[[0, 2, 3], [1], [4], [5, 6]]
Product of cycles == P
True
Transpositions in P: 
[(0, 3), (0, 2), (5, 6)]
Inversions in P: 
[[2, 1, 1, 0, 0, 1], 5]
Adjacency matrix: 
⎡0  0  0  0  1  0  0⎤
⎢                   ⎥
⎢0  0  0  1  0  0  0⎥
⎢                   ⎥
⎢0  1  0  0  0  0  0⎥
⎢                   ⎥
⎢1  0  0  0  0  0  0⎥
⎢                   ⎥
⎢0  0  0  0  0  0  1⎥
⎢                   ⎥
⎢0  0  0  0  0  0  0⎥
⎢                   ⎥
⎣0  0  0  0  0  1  0⎦


In [15]:
%%r
library(Matrix)
p<-c(3,2,4,1,5,7,6); P<-as(p,"pMatrix")
c(P,paste(P@perm,collapse=" "),
  t(P),determinant(P)$sign)

[[1]]
7 x 7 sparse Matrix of class "pMatrix"
                  
[1,] . . | . . . .
[2,] . | . . . . .
[3,] . . . | . . .
[4,] | . . . . . .
[5,] . . . . | . .
[6,] . . . . . . |
[7,] . . . . . | .

[[2]]
[1] "3 2 4 1 5 7 6"

[[3]]
7 x 7 sparse Matrix of class "pMatrix"
                  
[1,] . . . | . . .
[2,] . | . . . . .
[3,] | . . . . . .
[4,] . . | . . . .
[5,] . . . . | . .
[6,] . . . . . . |
[7,] . . . . . | .

[[4]]
[1] -1


## 3. В формуле определителя n-ого порядка

$\large{\displaystyle{| \Delta | = \sum_i (-1)^{t(j)} a_{1j_1}a_{2j_2}}...a_{nj_n}}$, где

$\{j_1, j_2, ..., j_n\}$ - все возможные перестановки из чисел $\{1, 2, ..., n\}$;

$t(j)$ - число инверсий для перехода от $\{1, 2, ..., n\}$ к $\{j_1, j_2, ..., j_n\}$. 

In [44]:
# sage
for n in [1..4]:
    aa=" ".join(['a_%d%d' %(i,j) 
                 for i in [1..n] for j in [1..n]])
    A=matrix(SR,n,var(aa))
    print(A); print(A.det())

[a_11]
a_11
[a_11 a_12]
[a_21 a_22]
-a_12*a_21 + a_11*a_22
[a_11 a_12 a_13]
[a_21 a_22 a_23]
[a_31 a_32 a_33]
-(a_23*a_32 - a_22*a_33)*a_11 + (a_13*a_32 - a_12*a_33)*a_21 - (a_13*a_22 - a_12*a_23)*a_31
[a_11 a_12 a_13 a_14]
[a_21 a_22 a_23 a_24]
[a_31 a_32 a_33 a_34]
[a_41 a_42 a_43 a_44]
a_14*a_23*a_32*a_41 - a_13*a_24*a_32*a_41 - a_14*a_22*a_33*a_41 + a_12*a_24*a_33*a_41 + a_13*a_22*a_34*a_41 - a_12*a_23*a_34*a_41 - a_14*a_23*a_31*a_42 + a_13*a_24*a_31*a_42 + a_14*a_21*a_33*a_42 - a_11*a_24*a_33*a_42 - a_13*a_21*a_34*a_42 + a_11*a_23*a_34*a_42 + a_14*a_22*a_31*a_43 - a_12*a_24*a_31*a_43 - a_14*a_21*a_32*a_43 + a_11*a_24*a_32*a_43 + a_12*a_21*a_34*a_43 - a_11*a_22*a_34*a_43 - a_13*a_22*a_31*a_44 + a_12*a_23*a_31*a_44 + a_13*a_21*a_32*a_44 - a_11*a_23*a_32*a_44 - a_12*a_21*a_33*a_44 + a_11*a_22*a_33*a_44


In [40]:
# sympy
import sympy; n=4
sympy.init_printing(use_unicode=True)
aa=['a_%d%d' %(i,j) 
    for i in (1..n) for j in (1..n)]
aa=sympy.symbols(" ".join(aa))
A=sympy.Matrix(int(n),int(n),aa)
sympy.pprint(A); sympy.pprint(A.det())

⎡a₁₁  a₁₂  a₁₃  a₁₄⎤
⎢                  ⎥
⎢a₂₁  a₂₂  a₂₃  a₂₄⎥
⎢                  ⎥
⎢a₃₁  a₃₂  a₃₃  a₃₄⎥
⎢                  ⎥
⎣a₄₁  a₄₂  a₄₃  a₄₄⎦
a₁₁⋅a₂₂⋅a₃₃⋅a₄₄ - a₁₁⋅a₂₂⋅a₃₄⋅a₄₃ - a₁₁⋅a₂₃⋅a₃₂⋅a₄₄ + a₁₁⋅a₂₃⋅a₃₄⋅a₄₂ + a₁₁⋅a₂
₄⋅a₃₂⋅a₄₃ - a₁₁⋅a₂₄⋅a₃₃⋅a₄₂ - a₁₂⋅a₂₁⋅a₃₃⋅a₄₄ + a₁₂⋅a₂₁⋅a₃₄⋅a₄₃ + a₁₂⋅a₂₃⋅a₃₁⋅
a₄₄ - a₁₂⋅a₂₃⋅a₃₄⋅a₄₁ - a₁₂⋅a₂₄⋅a₃₁⋅a₄₃ + a₁₂⋅a₂₄⋅a₃₃⋅a₄₁ + a₁₃⋅a₂₁⋅a₃₂⋅a₄₄ - 
a₁₃⋅a₂₁⋅a₃₄⋅a₄₂ - a₁₃⋅a₂₂⋅a₃₁⋅a₄₄ + a₁₃⋅a₂₂⋅a₃₄⋅a₄₁ + a₁₃⋅a₂₄⋅a₃₁⋅a₄₂ - a₁₃⋅a₂
₄⋅a₃₂⋅a₄₁ - a₁₄⋅a₂₁⋅a₃₂⋅a₄₃ + a₁₄⋅a₂₁⋅a₃₃⋅a₄₂ + a₁₄⋅a₂₂⋅a₃₁⋅a₄₃ - a₁₄⋅a₂₂⋅a₃₃⋅
a₄₁ - a₁₄⋅a₂₃⋅a₃₁⋅a₄₂ + a₁₄⋅a₂₃⋅a₃₂⋅a₄₁


# 4. Задание

Представить подстановку в виде произведения циклов и транспозиций, 

найти инверсии в подстановке, используя SageMath, Numpy, SymPy, R.

$\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \ 8 \\ 
3 \ 5 \ 4 \ 1 \ 2 \ 8 \ 6 \ 7
\end{cases}$