<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №0</h1>

### Программные средства

[LaTeX. Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Sage. Basic Algebra and Calculus](http://doc.sagemath.org/html/en/tutorial/tour_algebra.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[R Tutorial](https://www.tutorialspoint.com/r/index.htm)

### Конспекты лекций

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

[Computational Mathematics with SageMath](http://dl.lateralis.org/public/sagebook/sagebook-ba6596d.pdf)

[Семинары по алгебре](https://www.mccme.ru/~yasinsky/teaching/)

# Подстановка (таблица перестановки элементов)
## 1. Перестановки, размещения, сочетания

In [35]:
Arrangements(["A","B","C","D"],4).list()

[['A', 'B', 'C', 'D'],
 ['A', 'B', 'D', 'C'],
 ['A', 'C', 'B', 'D'],
 ['A', 'C', 'D', 'B'],
 ['A', 'D', 'B', 'C'],
 ['A', 'D', 'C', 'B'],
 ['B', 'A', 'C', 'D'],
 ['B', 'A', 'D', 'C'],
 ['B', 'C', 'A', 'D'],
 ['B', 'C', 'D', 'A'],
 ['B', 'D', 'A', 'C'],
 ['B', 'D', 'C', 'A'],
 ['C', 'A', 'B', 'D'],
 ['C', 'A', 'D', 'B'],
 ['C', 'B', 'A', 'D'],
 ['C', 'B', 'D', 'A'],
 ['C', 'D', 'A', 'B'],
 ['C', 'D', 'B', 'A'],
 ['D', 'A', 'B', 'C'],
 ['D', 'A', 'C', 'B'],
 ['D', 'B', 'A', 'C'],
 ['D', 'B', 'C', 'A'],
 ['D', 'C', 'A', 'B'],
 ['D', 'C', 'B', 'A']]

In [40]:
len(Arrangements(["A","B","C","D"],4).list()) == factorial(4)

True

In [43]:
Arrangements(["A","B","C","D","E"],3).list()

[['A', 'B', 'C'],
 ['A', 'B', 'D'],
 ['A', 'B', 'E'],
 ['A', 'C', 'B'],
 ['A', 'C', 'D'],
 ['A', 'C', 'E'],
 ['A', 'D', 'B'],
 ['A', 'D', 'C'],
 ['A', 'D', 'E'],
 ['A', 'E', 'B'],
 ['A', 'E', 'C'],
 ['A', 'E', 'D'],
 ['B', 'A', 'C'],
 ['B', 'A', 'D'],
 ['B', 'A', 'E'],
 ['B', 'C', 'A'],
 ['B', 'C', 'D'],
 ['B', 'C', 'E'],
 ['B', 'D', 'A'],
 ['B', 'D', 'C'],
 ['B', 'D', 'E'],
 ['B', 'E', 'A'],
 ['B', 'E', 'C'],
 ['B', 'E', 'D'],
 ['C', 'A', 'B'],
 ['C', 'A', 'D'],
 ['C', 'A', 'E'],
 ['C', 'B', 'A'],
 ['C', 'B', 'D'],
 ['C', 'B', 'E'],
 ['C', 'D', 'A'],
 ['C', 'D', 'B'],
 ['C', 'D', 'E'],
 ['C', 'E', 'A'],
 ['C', 'E', 'B'],
 ['C', 'E', 'D'],
 ['D', 'A', 'B'],
 ['D', 'A', 'C'],
 ['D', 'A', 'E'],
 ['D', 'B', 'A'],
 ['D', 'B', 'C'],
 ['D', 'B', 'E'],
 ['D', 'C', 'A'],
 ['D', 'C', 'B'],
 ['D', 'C', 'E'],
 ['D', 'E', 'A'],
 ['D', 'E', 'B'],
 ['D', 'E', 'C'],
 ['E', 'A', 'B'],
 ['E', 'A', 'C'],
 ['E', 'A', 'D'],
 ['E', 'B', 'A'],
 ['E', 'B', 'C'],
 ['E', 'B', 'D'],
 ['E', 'C', 'A'],
 ['E', 'C'

In [46]:
len(Arrangements(["A","B","C","D","E"],3).list()) == factorial(5)/factorial(5-3)

True

In [47]:
Combinations(["A","B","C","D","E"],3).list()

[['A', 'B', 'C'],
 ['A', 'B', 'D'],
 ['A', 'B', 'E'],
 ['A', 'C', 'D'],
 ['A', 'C', 'E'],
 ['A', 'D', 'E'],
 ['B', 'C', 'D'],
 ['B', 'C', 'E'],
 ['B', 'D', 'E'],
 ['C', 'D', 'E']]

In [48]:
len(Combinations(["A","B","C","D","E"],3).list()) == factorial(5)/(factorial(5-3)*factorial(3))

True

## 2. Свойства перестановок
Пример для конечного множества элементов

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_3 a_2 a_4 a_1 a_5 a_7 a_6\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
3 \ 2 \ 4 \ 1 \ 5 \ 7 \ 6 
\end{cases}$

Тождественная перестановка

$ e = 
\begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7
\end{cases}$

$\tau \circ e = e \circ \tau = \tau \\
\tau \circ \tau ^{-1} = \tau ^ {-1} \circ \tau = e \\
\tau_1 \circ (\tau_2 \circ \tau_3) = (\tau_1 \circ \tau_2) \circ \tau_3$

В общем случае

$\tau_1 \circ \tau_2 \neq \tau_2 \circ \tau_1$

Цикл

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_2 a_3 a_4 a_5 a_6 a_7 a_1\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
2 \ 3 \ 4 \ 5 \ 6 \ 7 \ 1 
\end{cases}$

Любая перестановка - произведение циклов.

Транспозиция

$\{a_1 a_2 a_3 a_4 a_5 a_6 a_7\} \to \{a_2 a_1 a_3 a_4 a_5 a_6 a_7\} \\
\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
2 \ 1 \ 3 \ 4 \ 5 \ 6 \ 7  
\end{cases}$

Любой цикл - произведение транспозиций, любая перестановка - произведение транспозиций.

Инверсии в подстановке

$\tau = \begin {cases}
1 \ 2 \ 3 \ 4 \ 5 \ 6 \ 7 \\ 
3 \ 2 \ 4 \ 1 \ 5 \ 7 \ 6 
\end{cases} \\
(2,1), (3,1), (4,1), \\ (3,2), \\ (7,6)$

Четность подстановки - количество инверсий.

In [19]:
Permutation([3,2,4,1,5,7,6]).to_cycles()

[(1, 3, 4), (2,), (5,), (6, 7)]

In [28]:
Permutation([3,2,4,1,5,6,7]) * Permutation([1,2,3,4,5,7,6]) 

[3, 2, 4, 1, 5, 7, 6]

In [24]:
Permutation([3,2,4,1,5,7,6]).fixed_points()

[2, 5]

In [20]:
Permutation([3,2,4,1,5,7,6]).inversions()

[(1, 2), (1, 4), (2, 4), (3, 4), (6, 7)]

In [22]:
Permutation([3,2,4,1,5,7,6]).number_of_inversions()

5

In [23]:
Permutation([3,2,4,1,5,7,6]).is_even()

False

In [27]:
Permutation([3,2,4,1,5,7,6]).to_matrix()

[0 0 0 1 0 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[0 0 0 0 0 1 0]

## 3. В формуле определителя n-ого порядка

$\large{\displaystyle{| \Delta | = \sum_i (-1)^{t(j)} a_{1j_1}a_{2j_2}}...a_{nj_n}}$, где

$\{j_1, j_2, ..., j_n\}$ - все возможные перестановки из чисел $\{1, 2, ..., n\}$;

$t(j)$ - число транспозиций для перехода от $\{1, 2, ..., n\}$ к $\{j_1, j_2, ..., j_n\}$. 

In [1]:
aa = " ".join(list('a_%d%d' %(i,j) for i in (1..2) for j in (1..2)))
A = matrix(SR, 2, var(aa))
A.det() 

-a_12*a_21 + a_11*a_22

In [2]:
aa = " ".join(list('a_%d%d' %(i,j) for i in (1..3) for j in (1..3)))
A = matrix(SR, 3, var(aa))
A.det().expand()   

-a_13*a_22*a_31 + a_12*a_23*a_31 + a_13*a_21*a_32 - a_11*a_23*a_32 - a_12*a_21*a_33 + a_11*a_22*a_33

In [3]:
aa = " ".join(list('a_%d%d' %(i,j) for i in (1..4) for j in (1..4)))
A = matrix(SR, 4, var(aa))
A.det().expand() 

a_14*a_23*a_32*a_41 - a_13*a_24*a_32*a_41 - a_14*a_22*a_33*a_41 + a_12*a_24*a_33*a_41 + a_13*a_22*a_34*a_41 - a_12*a_23*a_34*a_41 - a_14*a_23*a_31*a_42 + a_13*a_24*a_31*a_42 + a_14*a_21*a_33*a_42 - a_11*a_24*a_33*a_42 - a_13*a_21*a_34*a_42 + a_11*a_23*a_34*a_42 + a_14*a_22*a_31*a_43 - a_12*a_24*a_31*a_43 - a_14*a_21*a_32*a_43 + a_11*a_24*a_32*a_43 + a_12*a_21*a_34*a_43 - a_11*a_22*a_34*a_43 - a_13*a_22*a_31*a_44 + a_12*a_23*a_31*a_44 + a_13*a_21*a_32*a_44 - a_11*a_23*a_32*a_44 - a_12*a_21*a_33*a_44 + a_11*a_22*a_33*a_44