<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №4</h1>

### Программные средства

[LaTeX. Mathematics. Matrices & Arrays](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays)

[Sage. Matrices & Spaces of Matrices](https://doc.sagemath.org/html/en/reference/matrices/index.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

[Quick-R. Matrix Algebra](https://www.statmethods.net/advstats/matrix.html)

[R - Matrices](https://www.tutorialspoint.com/r/r_matrices.htm)

### Конспекты лекций

[Матрицы. Системы линейных уравнений. Алгоритм Гаусса](http://matematika.phys.msu.ru/files/a_stud_gen/246/AG-08_2009-2010.pdf)

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

# Матрицы

## 1. Обратная матрица

In [11]:
M = matrix(SR, 2, var('a,b,c,d')) 
html(M^(-1))

<script type="math/tex">\left(\begin{array}{rr} \frac{1}{a} - \frac{b c}{a^{2} {\left(\frac{b c}{a} - d\right)}} & \frac{b}{a {\left(\frac{b c}{a} - d\right)}} \\ \frac{c}{a {\left(\frac{b c}{a} - d\right)}} & -\frac{1}{\frac{b c}{a} - d} \end{array}\right)</script>

In [12]:
html(M.inverse())

<script type="math/tex">\left(\begin{array}{rr} \frac{1}{a} - \frac{b c}{a^{2} {\left(\frac{b c}{a} - d\right)}} & \frac{b}{a {\left(\frac{b c}{a} - d\right)}} \\ \frac{c}{a {\left(\frac{b c}{a} - d\right)}} & -\frac{1}{\frac{b c}{a} - d} \end{array}\right)</script>

In [15]:
html(M * M^(-1))

<script type="math/tex">\left(\begin{array}{rr} a {\left(\frac{1}{a} - \frac{b c}{a^{2} {\left(\frac{b c}{a} - d\right)}}\right)} + \frac{b c}{a {\left(\frac{b c}{a} - d\right)}} & 0 \\ c {\left(\frac{1}{a} - \frac{b c}{a^{2} {\left(\frac{b c}{a} - d\right)}}\right)} + \frac{c d}{a {\left(\frac{b c}{a} - d\right)}} & \frac{b c}{a {\left(\frac{b c}{a} - d\right)}} - \frac{d}{\frac{b c}{a} - d} \end{array}\right)</script>

In [32]:
(M * M^(-1)).simplify_rational()

[1 0]
[0 1]

In [33]:
html(M^(-1) * M)

<script type="math/tex">\left(\begin{array}{rr} a {\left(\frac{1}{a} - \frac{b c}{a^{2} {\left(\frac{b c}{a} - d\right)}}\right)} + \frac{b c}{a {\left(\frac{b c}{a} - d\right)}} & b {\left(\frac{1}{a} - \frac{b c}{a^{2} {\left(\frac{b c}{a} - d\right)}}\right)} + \frac{b d}{a {\left(\frac{b c}{a} - d\right)}} \\ 0 & \frac{b c}{a {\left(\frac{b c}{a} - d\right)}} - \frac{d}{\frac{b c}{a} - d} \end{array}\right)</script>

In [34]:
(M^(-1) * M).simplify_rational()

[1 0]
[0 1]

In [36]:
(M * M^(-1)).simplify_rational() == (M^(-1) * M).simplify_rational() == identity_matrix(2)

True

In [49]:
# sage
A1 = random_matrix(ZZ,2,x=0,y=100)
B1 = random_matrix(ZZ,3,x=-100,y=0)
C1 = random_matrix(ZZ,4,x=-100,y=100)
A1, B1, C1

(
                        [ 41 -58  -7  45]
         [ -1 -21 -57]  [ 70   8  60  69]
[61 81]  [-16 -12 -18]  [  9  93  68  74]
[96  6], [-88 -46 -25], [ 50  95 -86 -52]
)

In [50]:
A1.inverse(), B1.inverse(), C1.inverse()

(
                                                      [ -263018/60198711   299232/20066237  -499469/60198711   252779/60198711]
                     [   11/127 -699/2032   51/1016]  [ -160034/60198711   -33686/20066237   340156/60198711   211481/60198711]
[ -1/1235  27/2470]  [  -74/381 4991/6096 -149/1016]  [-1059131/60198711   299675/20066237  -415781/60198711  -315307/60198711]
[ 16/1235 -61/7410], [   20/381 -901/3048    27/508], [ 1206368/60198711  -269435/20066237   828818/60198711    -6782/60198711]
)

In [51]:
A1 * A1^(-1), B1 * B1^(-1), C1 * C1^(-1)

(
                [1 0 0 0]
       [1 0 0]  [0 1 0 0]
[1 0]  [0 1 0]  [0 0 1 0]
[0 1], [0 0 1], [0 0 0 1]
)

In [71]:
B1_m = B1.minors(2)
B1_m.reverse()
C1_m = C1.minors(3)
C1_m.reverse()
B1_M = matrix(3, B1_m).T
C1_M = matrix(4, C1_m).T
B1_M, C1_M

(
                     [ -263018  -897696  -499469  -252779]
[ -528 -2097  -306]  [  160034  -101058  -340156   211481]
[-1184 -4991  -894]  [-1059131  -899025  -415781   315307]
[ -320 -1802  -324], [-1206368  -808305  -828818    -6782]
)

In [72]:
B1.adjoint(), C1.adjoint()

(
                     [ -263018   897696  -499469   252779]
[ -528  2097  -306]  [ -160034  -101058   340156   211481]
[ 1184 -4991   894]  [-1059131   899025  -415781  -315307]
[ -320  1802  -324], [ 1206368  -808305   828818    -6782]
)

In [74]:
B1.adjoint()/B1.det() == B1.inverse(), C1.adjoint()/B1.det() == C1.inverse()

(True, False)

In [76]:
%%latex
$| M | = 
\begin{vmatrix}
A & B \\
C & D
\end{vmatrix} = | A | * |D - C * A^{-1} * B|$

<IPython.core.display.Latex object>

In [75]:
M = random_matrix(ZZ,4,x=-100,y=100)
M, M.det()

(
[-91   9 -81 -59]           
[ 47 -13   7  -3]           
[-59  40 -77 -41]           
[ 80 -15 -78  43], -15180522
)

In [77]:
A, B, C, D = M[0:2,0:2], M[0:2,2:4], M[2:4,0:2], M[2:4,2:4]
A, B, C, D

(
[-91   9]  [-81 -59]  [-59  40]  [-77 -41]
[ 47 -13], [  7  -3], [ 80 -15], [-78  43]
)

In [78]:
A.det() * (D - C * A.inverse() * B).det() == M.det()

True

In [143]:
# python numpy
import numpy
A2 = numpy.matrix(numpy.random.randint(0, 100, size=(2,2)))
B2 = numpy.matrix(numpy.random.randint(-100, 0, size=(3,3)))
C2 = numpy.matrix(numpy.random.randint(-100, 100, size=(4,4)))
print(A2)
print(B2)
print(C2)

[[89 79]
 [91 79]]
[[-90 -70 -56]
 [-59  -3 -82]
 [-95  -8 -88]]
[[  5 -57 -58 -16]
 [ 10  -8  73 -35]
 [-82  15 -61 -65]
 [-71 -34  25 -89]]


In [144]:
print(numpy.linalg.inv(A2))
print(numpy.linalg.inv(B2))
print(numpy.linalg.inv(C2))

[[-0.5         0.5       ]
 [ 0.57594937 -0.56329114]]
[[ 0.00249599  0.03637012 -0.03547869]
 [-0.01654229 -0.01655503  0.02595319]
 [-0.00119069 -0.03775819  0.02457785]]
[[ 0.0138232   0.03064886  0.01352754 -0.02441765]
 [-0.00517495  0.01546846  0.01640867 -0.01713663]
 [-0.00785836 -0.00388364 -0.00951597  0.00988988]
 [-0.01125795 -0.03145042 -0.01973314  0.01756793]]


In [145]:
print(round(A2 * numpy.linalg.inv(A2))) 
print(round(B2 * numpy.linalg.inv(B2)))
print(round(C2 * numpy.linalg.inv(C2))) 

[[ 1.  0.]
 [ 0.  1.]]
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]
[[ 1.  0.  0. -0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


In [188]:
def minor_matrix(M, x, y):
    return numpy.matrix([[M[i,j] for j in range(len(M)) if j != y] \
                         for i in range(len(M)) if i != x])
def minor(M, x, y):
    return numpy.linalg.det(minor_matrix(M, x, y))

def cofactor_matrix(M):
    return numpy.matrix([[(-1) ** (i + j) * minor(M,i,j) for j in range(len(M))]\
                         for i in range(len(M))])

print(B2)
print
print('element: ' + str(B2[0,0]) + '  <=>')
print(minor_matrix(B2,0,0))
print('minor: ' + str(int(round(minor(B2,0,0)))))
print
print(cofactor_matrix(B2).T / numpy.linalg.det(B2))
print(numpy.linalg.inv(B2))

[[-90 -70 -56]
 [-59  -3 -82]
 [-95  -8 -88]]

element: -90  <=>
[[ -3 -82]
 [ -8 -88]]
minor: -392

[[ 0.00249599  0.03637012 -0.03547869]
 [-0.01654229 -0.01655503  0.02595319]
 [-0.00119069 -0.03775819  0.02457785]]
[[ 0.00249599  0.03637012 -0.03547869]
 [-0.01654229 -0.01655503  0.02595319]
 [-0.00119069 -0.03775819  0.02457785]]


In [183]:
cofactor_matrix(B2).T / numpy.linalg.det(B2) == numpy.linalg.inv(B2)

matrix([[False, False, False],
        [False, False, False],
        [False, False, False]], dtype=bool)

In [182]:
numpy.round(cofactor_matrix(B2).T/numpy.linalg.det(B2),16) == numpy.round(numpy.linalg.inv(B2),16)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [79]:
M = numpy.matrix(numpy.random.randint(0, 100, size=(4,4)))
print(M)

[[99 31 84 41]
 [57 37 16 39]
 [78 62 35 50]
 [14 96 85  4]]


In [80]:
A, B, C, D = M[0:2,0:2], M[0:2,2:4], M[2:4,0:2], M[2:4,2:4]
print(A); print(B); print(C); print(D)

[[99 31]
 [57 37]]
[[84 41]
 [16 39]]
[[78 62]
 [14 96]]
[[35 50]
 [85  4]]


In [85]:
numpy.linalg.det(A) * numpy.linalg.det(D - C * numpy.linalg.inv(A) * B), numpy.linalg.det(M)

(782647.99999999371, 782647.99999999721)

In [84]:
round(numpy.linalg.det(A) * numpy.linalg.det(D - C * numpy.linalg.inv(A) * B)) == \
round(numpy.linalg.det(M))

True