<h1 style="color: #3636ff;">Линейная алгебра. Практическая работа №7</h1>

<a href="https://olgabelitskaya.github.io/README.html">&#x1F300; &nbsp; Home Page</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_6.ipynb">📓 &nbsp; Previous</a> &nbsp; &nbsp; <a href="https://github.com/OlgaBelitskaya/linear_algebra_practice/blob/master/work1_8.ipynb">📓 &nbsp; Next</a>

### Программные средства

[LaTeX. Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Sage. Linear Algebra](http://doc.sagemath.org/html/en/tutorial/tour_linalg.html)

[Numpy. Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html#linear-algebra)

[SymPy. Vector & ReferenceFrame](https://docs.sympy.org/latest/modules/physics/vector/vectors.html)

[Quick-R. Data Types](https://www.statmethods.net/input/datatypes.html)

[R Vectors - TutorialsPoint](https://www.tutorialspoint.com/r/r_vectors.htm)

### Конспекты лекций

[АЛГЕБРА И ГЕОМЕТРИЯ ДЛЯ СТУДЕНТОВ-ФИЗИКОВ](http://math.phys.msu.ru/data/24/Algebra_and_geometry.pdf)

[Computational Mathematics with SageMath](http://dl.lateralis.org/public/sagebook/sagebook-ba6596d.pdf)

# Векторы

## 1. Векторы в пространстве. Сумма векторов

In [26]:
var('a1 a2 a3 b1 b2 b3 e1 e2 e3')
e,a,b=vector(SR,[e1,e2,e3]),vector(SR,[a1,a2,a3]),vector(SR,[b1,b2,b3]) 
i,j,k=vector(SR,[1,0,0]),vector(SR,[0,1,0]),vector(SR,[0,0,1])
v=vector(SR,[2,3,2])
v1,v2,v3=vector(SR,[2,0,0]),vector(SR,[0,3,0]),vector(SR,[0,0,2])
c,d=vector(SR,[2,0,-2]),vector(SR,[1,2,1])

In [2]:
vs1=[i,j,k,v]; vs2=[v1,v2,v3]
vl1=['i','j','k','v']; vl2=['v1','v2','v3']
colors=['#3636ff','#36ff36','#ff3636','#ff36ff']
p1=sum([arrow3d([0,0,0],vs1[n],color=colors[n],width=2)+\
   text3d(vl1[n],vs1[n]*1.1) for n in [0..3]])
p2=sum([arrow3d([0,0,0],vs2[n],
                color=colors[n],width=2,alpha=0.3)+\
   text3d(vl2[n],vs2[n]*1.1) for n in [0..2]])
p3=arrow3d([0,0,0],v1+v2,color='#36ffff',width=2,alpha=0.3)+\
   text3d('v1+v2',(v1+v2)*1.1)
p4=arrow3d(v1+v2,v,color='#ff3636',width=2,alpha=0.3)+\
   text3d('v3',[2,3,2*1.1])
(p1+p2+p3+p4).show()

Graphics3d Object

In [3]:
v.norm(),v.norm().n(),2*i+3*j+2*k==v

(sqrt(17), 4.12310562561766, True)

In [4]:
a+b,c+d

((a1 + b1, a2 + b2, a3 + b3), (3, 2, -1))

In [5]:
import numpy,sympy,sympy.vector
from scipy.optimize import fsolve 
sympy.init_printing(use_unicode=True)
ni,nj=numpy.array([1,0,0]),numpy.array([0,1,0])
nk,nv=numpy.array([0,0,1]),numpy.array([2,3,2])
na=numpy.array(['a1','a2','a3'],dtype='U')
nb=numpy.array(['+b1','+b2','+b3'],dtype='U')
nc,nd=numpy.array([2,0,-2]),numpy.array([1,2,1])
se=sympy.vector.CoordSys3D('se'); sv=2*se.i+3*se.j+2*se.k
a1,a2,a3,b1,b2,b3=sympy.symbols('a1 a2 a3 b1 b2 b3')
sa=a1*se.i+a2*se.j+a3*se.k; sb=b1*se.i+b2*se.j+b3*se.k
sc=2*se.i+0*se.j-2*se.k; sd=1*se.i+2*se.j+1*se.k

In [10]:
print(2*ni+3*nj+2*nk==nv,numpy.linalg.norm(nv))
print([sv,sv.to_matrix(se).norm(),
 sv.to_matrix(se).norm().evalf()])

(array([ True,  True,  True]), 4.123105625617661)
[2*se.i + 3*se.j + 2*se.k, sqrt(17), 4.12310562561766]


In [12]:
print(numpy.core.defchararray.add(na,nb),nc+nd)
print([sa+sb,sc+sd])

(array([u'a1+b1', u'a2+b2', u'a3+b3'], dtype='<U5'), array([ 3,  2, -1]))
[(a1 + b1)*se.i + (a2 + b2)*se.j + (a3 + b3)*se.k, 3*se.i + 2*se.j + (-1)*se.k]


In [13]:
%%r
i<-c(1,0,0); j<-c(0,1,0); k<-c(0,0,1)
v<-c(2,3,2)
a<-c('a1','a2','a3')
b<-c('+ b1','+ b2','+ b3')
c<-c(2,0,-2); d<-c(1,2,1)
library(Matrix)

[1] "Matrix"    "tools"     "stats"     "graphics"  "grDevices" "utils"    
[7] "datasets"  "methods"   "base"


In [14]:
%%r
list(matrix(c(i,j,k,v),4,3,byrow=T),
     v==2*i+3*j+2*k,norm(matrix(v),'f'))

[[1]]
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1
[4,]    2    3    2

[[2]]
[1] TRUE TRUE TRUE

[[3]]
[1] 4.123106


In [16]:
%%r
print(paste(a,b)); c+d

[1] "a1 + b1" "a2 + b2" "a3 + b3"
[1]  3  2 -1


## 2. Скалярное произведение.

In [17]:
print(c.dot_product(d))
a.dot_product(b)

0


a1*b1 + a2*b2 + a3*b3

In [18]:
print(nc.dot(nd))
sympy.pprint(sc.dot(sd))
sympy.pprint(sa.dot(sb))

0
0
a₁⋅b₁ + a₂⋅b₂ + a₃⋅b₃


In [19]:
%%r
c%*%d

     [,1]
[1,]    0


## 3. Векторное произведение.

In [20]:
print(matrix([e,a,b]).det().collect(e2).collect(e3))
print(a.cross_product(b))
c.cross_product(d)

-(a3*b2 - a2*b3)*e1 + (a3*b1 - a1*b3)*e2 - (a2*b1 - a1*b2)*e3
(-a3*b2 + a2*b3, a3*b1 - a1*b3, -a2*b1 + a1*b2)


(4, -4, 4)

In [21]:
vs=[c,d,c+d,c.cross_product(d)]
vl=['c','d','c+d','cxd']
colors=['#3636ff','#36ff36','#ff3636','#ff36ff']
sum([arrow3d([0,0,0],vs[n],color=colors[n],width=3)+\
text3d(vl[n],vs[n]*1.1) for n in [0..3]]).show()

Graphics3d Object

In [22]:
print(numpy.cross(nc,nd))
sympy.pprint(sc.cross(sd))
sympy.pprint(sa.cross(sb))

[ 4 -4  4]
(4) se_i + (-4) se_j + (4) se_k
(a₂⋅b₃ - a₃⋅b₂) se_i + (-a₁⋅b₃ + a₃⋅b₁) se_j + (a₁⋅b₂ - a₂⋅b₁) se_k


In [23]:
%%r
vector_product3d<-function(x,y){
    c(x[2]*y[3]-x[3]*y[2],
      -x[1]*y[3]+x[3]*y[1],
      x[1]*y[2]-x[2]*y[1])}
vector_product3d(c,d)

[1]  4 -4  4


## 4. Пример типового расчета.

In [24]:
%%html
<p style="color:slategray;">
$\mathscr{\overrightarrow{C} (3,4,1); \ \overrightarrow{D} (1,2,1) \\
\overrightarrow{A} + \overrightarrow{B} = \overrightarrow{C}; \\ 
\overrightarrow{A} \perp \overrightarrow{D} \ 
(\overrightarrow{A} \cdot \overrightarrow{D} = 0) ;\\ 
\overrightarrow{B} \parallel \overrightarrow{D} \ 
(\overrightarrow{D} * k = \overrightarrow{B});\\
\overrightarrow{A}(a_1, a_2, a_3), \ 
\overrightarrow{B} (b_1, b_2, b_3), \ k = \ ?}$</p>

In [27]:
var('k')
A,B=vector(SR,[a1,a2,a3]),vector(SR,[b1,b2,b3])
C,D=vector(SR,[3,4,1]),vector(SR,[1,2,1])
solution=\
solve([(A+B-C)[0]==0,(A+B-C)[1]==0,(A+B-C)[2]==0,#A+B=C
       A.dot_product(D)==0,#A⊥D
       (k*D-B)[0]==0,(k*D-B)[1]==0,(k*D-B)[2]==0],#B||D
      a1,a2,a3,b1,b2,b3,k)
A=vector(SR,[solution[0][0].rhs(),
             solution[0][1].rhs(),
             solution[0][2].rhs()])
B=vector(SR,[solution[0][3].rhs(),
             solution[0][4].rhs(),
             solution[0][5].rhs()])
solution

[[a1 == 1, a2 == 0, a3 == -1, b1 == 2, b2 == 4, b3 == 2, k == 2]]

In [28]:
vs=[A,B,C,D]; vl=['A','B','C','D']
colors=['#3636ff','#36ff36','#ff3636','#ff36ff']
sum([arrow3d([0,0,0],vs[n],color=colors[n],width=3)+\
text3d(vl[n],vs[n]*1.1) for n in [0..3]]).show()

Graphics3d Object

In [29]:
def equations(v):
    a1,a2,a3,b1,b2,b3,k=v
    f1=a1+b1-3; f2=a2+b2-4; f3=a3+b3-1 #A+B=C
    f4=a1*1+a2*2+a3*1 #A⊥D
    f5=k*1-b1; f6=k*2-b2; f7=k*1-b3 #B||D 
    return (f1,f2,f3,f4,f5,f6,f7)
a1,a2,a3,b1,b2,b3,k=\
round(fsolve(equations,(0,0,0,0,0,0,0)))
[(a1,a2,a3),(b1,b2,b3),k]

In [30]:
a1,a2,a3,b1,b2,b3,k=sympy.symbols('a1 a2 a3 b1 b2 b3 k')
A,B=sympy.Matrix([a1,a2,a3]),sympy.Matrix([b1,b2,b3])
C,D=sympy.Matrix([3,4,1]),sympy.Matrix([1,2,1])
a1,a2,a3,b1,b2,b3,k=\
sympy.nsolve(((A+B-C)[0],(A+B-C)[1],(A+B-C)[2],#A+B=C
              A.dot(D),#A⊥D
              (k*D-B)[0],(k*D-B)[1],(k*D-B)[2]),#B||D
              (a1,a2,a3,b1,b2,b3,k),(0,0,0,0,0,0,0))
[(a1,a2,a3),(b1,b2,b3),k]

In [31]:
%%r
check_decision<-function(x){
    d<-c(x[1]+x[4]-3==0,#A+B=C
         x[2]+x[5]-4==0, 
         x[3]+x[6]-1==0, 
         x[1]*1+x[2]*2+x[3]*1==0,#A⊥D
         x[7]*1-x[4]==0,#B||D 
         x[7]*2-x[5]==0, 
         x[7]*1-x[6]==0)
    sum(d)==length(d)}
check_decision(c(1,0,-1,2,4,2,2))

[1] TRUE


In [108]:
%%r
library(pracma)
problem_decision<-function(x){
    c(x[1]+x[4]-3, # A + B = C
      x[2]+x[5]-4, 
      x[3]+x[6]-1, 
      x[1]*1+x[2]*2+x[3]*1, # A ⊥ D
      x[7]*1-x[4], # B || D 
      x[7]*2-x[5], 
      x[7]*1-x[6])}
print('a1 a2 a3 b1 b2 b2 k')
round(fsolve(problem_decision,c(0,0,0,0,0,0,0))$x)











[1] "a1 a2 a3 b1 b2 b2 k"
[1]  1  0 -1  2  4  2  2


## 5. Задание
Зная стороны $\overrightarrow{AB}(3,-4,0), \ \overrightarrow{BC}(1,5,0)$ в $\triangle ABC$, найти высоту $\overrightarrow{CD}$, 

используя SageMath, Python, R.